In [1]:
dataFilePath = "/Users/dharshid/CDIPS_Project/data/EP_data.csv"
import pandas as pd
EPData = pd.read_csv(dataFilePath)

In [3]:
EPData.columns

Index([u'gender', u'num_groups', u'num_entries', u'num_fans', u'num_friends',
       u'created', u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments'],
      dtype='object')

In [9]:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

In [11]:
noGroupsUsers = EPData[EPData['num_groups'] == 0]

In [14]:
noGroupsUsers

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
2,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,49025,I accept the wisdom of all religions and disca...,2015-01-01 00:00:49,10,1
75,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,275667,Thongs and g-strings for me. They are my favor...,2015-01-01 00:30:17,8,3
85,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,655763,I cuddle you... You no cuddle me. (Only on spe...,2015-01-01 00:36:25,0,0
112,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,30197,I pray for my cousin as I know what's happenin...,2015-01-01 00:48:02,3,1
167,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,207878,I am rethinking everything I once thought abou...,2015-01-01 01:06:04,0,0
173,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,111499,I don't let my plants die. I let them live. If...,2015-01-01 01:08:35,4,1
176,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,1159,I am unemployed. I also like living the fast l...,2015-01-01 01:09:17,0,2
201,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,1431,I was watchin tv and i came across a glade com...,2015-01-01 01:19:16,1,2
220,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,310364,You know you're loser when you unadd everyone ...,2015-01-01 01:25:48,3,2
231,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,438995,"I wet bed again, it was so warm but now the co...",2015-01-01 01:30:21,33,7
260,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,972286,"I am in my late 20s, i have been to college fo...",2015-01-01 01:37:48,2,1
399,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,6466,I am a very big hopeless romantic but at times...,2015-01-01 02:47:34,3,0
418,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,60,He is my dream come true ðŸ˜˜ðŸ˜â¤ï¸,2015-01-01 03:00:03,6,1
479,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,199746,I'm forming a pack. Anyone wanna join?,2015-01-01 03:42:41,4,4
490,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,64973,Moonlit night at the beach 4 minutes before mi...,2015-01-01 03:58:42,1,0
503,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,335,Somebody talk so bored and lonely need someone...,2015-01-01 04:13:33,3,1
506,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,36348,I don't have high expectations but I know I de...,2015-01-01 04:15:35,1,0
549,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,972266,Can't you feel that change is in the air? It'...,2015-01-01 04:43:51,3,0
553,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,178886,I want to make a 'sharing' friend in the UK. I...,2015-01-01 04:46:57,9,5
657,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,193494,"Girls can't find their car keys, shoes or chap...",2015-01-01 05:58:57,8,2
720,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,273296,It's health related and has me knocked for a l...,2015-01-01 06:42:12,1,0
725,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,516393,We all do actually. Mom sister and I (dad when...,2015-01-01 06:47:59,10,4
741,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,426358,I've found Shemales with females is really pre...,2015-01-01 06:57:34,7,3
758,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,50780,I have a Flickr page. I use or upload photos d...,2015-01-01 07:09:47,0,1
788,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,1431,"I need you tonight - INXS, dedicating this to ...",2015-01-01 07:37:55,3,0
869,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,651297,"A few years ago, my husband and I went to a di...",2015-01-01 08:15:34,12,11
884,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,117528,hoo hoo ha ha I am new at ep love this site,2015-01-01 08:23:22,0,1
893,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,5273,born in august I will prove I am real Leo wann...,2015-01-01 08:26:11,3,3
899,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,296125,If you want my yahoo Id just message me,2015-01-01 08:29:17,0,1
903,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,2212,I love to dance in rain sometimes I enjoy rain...,2015-01-01 08:30:52,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531099,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,3657,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:00:55,0,0
531102,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044635,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:02:43,0,0
531182,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,290634,ISSS NUUUUUUUUUUDDDDDDDDDES,2015-07-09 05:46:11,4,2
531232,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,779919,I want to be with a woman. To feel her soft li...,2015-07-09 06:13:04,6,3
531235,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,616813,Ask me anything I'll answer!,2015-07-09 06:14:11,1,3
531365,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044661,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 07:10:06,0,0
531420,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,414720,I want to be with several people at one time. ...,2015-07-09 07:44:12,0,0
531513,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044685,Sylvia Plath<br />\n(1932 - 1963)<br />\nOn Lo...,2015-07-09 08:28:05,0,0
531806,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044717,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 10:32:37,0,0
531921,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,12609,<img src='http://content-img.experienceproject...,2015-07-09 11:22:52,0,0
532050,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,443195,A woman came home to find her retired husband ...,2015-07-09 12:15:04,0,0
532265,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,668668,My first time peeing at the cinema was with my...,2015-07-09 13:33:30,7,2
532270,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,571409,I'm looking for someone to control my bladder....,2015-07-09 13:35:10,5,1
532675,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,967,I met my bf on a dating app. Turns out he stil...,2015-07-09 16:01:53,0,1
532681,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,60638,Bf tied me up earlier and pounded me. The chai...,2015-07-09 16:02:48,5,2
532692,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,269780,Me and bf use a spider gag when he face bangs me,2015-07-09 16:05:36,0,0
533222,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,60049,It's been about 3-4 weeks since my man has bee...,2015-07-09 19:12:09,1,0
533330,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,101959,I absolutely adore them :) nothing more sexy t...,2015-07-09 19:52:15,3,1
533389,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,672527,I fit well in this category. I've always been ...,2015-07-09 20:08:28,19,10
533452,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,107900,"I'm bi and not ashamed but still not ""coming o...",2015-07-09 20:32:28,1,3
533455,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,5577,I am but not really into masculine guys i pref...,2015-07-09 20:33:45,2,2
533466,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,759408,I don't use them personally. It removes a lot ...,2015-07-09 20:37:29,12,4
533471,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,3543,Is anyone interested in some rp with me?,2015-07-09 20:39:10,4,1
533582,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,599269,Would someone like to rp? Message me please.,2015-07-09 21:30:57,8,6
533588,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,595035,someone tell me how to delete it,2015-07-09 21:32:05,0,1
533642,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,851475,I am :) i like taking sexy pics in them,2015-07-09 21:52:11,0,0
533652,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,69947,I am looking for my daddy ;* message me if you...,2015-07-09 21:55:43,1,1
533661,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,4603,Today I have been frustrated and stuff. My gir...,2015-07-09 22:00:15,0,1
533771,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,41615,it was absolutely fun to be nude on beach.. i ...,2015-07-09 22:38:10,3,0
533967,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,334564,I want to do a tranny or cd :) i love looking ...,2015-07-09 23:40:51,0,0

In [15]:
EPData.loc[531099,:]

gender                                                                  F
num_groups                                                              0
num_entries                                                            28
num_fans                                                                1
num_friends                                                             0
created                                                        2015-06-20
last_login                                            2015-07-09 10:25:36
num_logins                                                             57
last_wall_activity                                    2015-07-09 12:57:31
last_circle_activity                                  2015-07-07 13:44:18
birthdate                                                      1964-11-30
gid                                                                  3657
content                 <iframe title="YouTube video player" class="yo...
date_posted                                           2015-07-09 05:00:55
votes                                                                   0
num_comments                                                            0
Name: 531099, dtype: object

In [17]:
noGroupsFemales = noGroupsUsers[noGroupsUsers['gender']=='F']

In [18]:
noGroupsFemales.sort(columns='created')

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
388303,F,0,2,1,0,2010-02-18,2015-04-02 10:53:19,5,0000-00-00 00:00:00,2010-12-03 21:55:25,1997-03-07,2475,I was in my exs house and we were in the livin...,2015-03-31 22:36:36,0,0
346613,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,In a really bad mood.<br />\nI feel like this ...,2015-05-12 09:06:54,3,1
139524,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,Relapsing- Part II<br />\n<br />\nI figured it...,2015-02-22 13:14:08,0,2
495416,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,Went on a date today.<br />\nSpent 4 hours wit...,2015-06-28 22:32:14,0,0
123029,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,"Aww Man, <br />\n<br />\nI notice that this fe...",2015-02-15 21:31:14,1,0
127956,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,192737,It's a white winter morning. There is a stilln...,2015-02-17 20:32:28,0,0
197590,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,192737,I have been waiting a very long time.<br />\nI...,2015-03-16 22:36:48,0,0
405651,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,What just happened to my story!? Ugh. I lost i...,2015-05-31 02:57:10,1,0
408193,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,I'm struggling with something that I wanted to...,2015-05-31 23:25:17,2,2
391019,F,0,2,1,0,2011-04-21,2015-03-15 14:01:51,13,2015-03-15 08:28:13,0000-00-00 00:00:00,1997-03-07,154884,I'm addicted. I use sex as a way to tear away ...,2015-03-14 09:55:04,2,1
391018,F,0,2,1,0,2011-04-21,2015-03-15 14:01:51,13,2015-03-15 08:28:13,0000-00-00 00:00:00,1997-03-07,154884,I'm addicted. I use sex as a way to tear away ...,2015-03-14 09:52:49,1,1
391281,F,0,8,3,0,2011-12-01,2015-07-08 03:53:48,59,2015-04-07 20:32:40,2012-01-12 13:39:02,1979-03-12,154884,Its over 3 years since we have spoken.Â <br />...,2015-03-25 23:38:03,0,0
230785,F,0,30,71,3,2012-02-19,2015-07-07 20:32:59,1445,2015-06-21 10:53:34,2015-01-18 17:47:38,1989-03-09,635569,I'd choose you every time! If I had every guy ...,2015-03-29 22:00:01,0,0
388592,F,0,3,1,0,2012-03-29,2015-05-25 11:21:17,11,2015-05-22 08:16:01,2012-03-29 04:36:29,1994-08-31,2475,Me and my boyfriend that I am currently breaki...,2015-05-22 03:11:01,0,0
390300,F,0,1914,816,186,2012-04-03,2015-06-21 21:25:22,2078,2014-10-24 04:38:31,2014-11-09 12:41:10,1974-03-13,154884,"going to bed, aiiight, kids? goodnight, its be...",2015-02-06 01:19:10,1,0
9128,F,0,2,3,1,2012-08-03,2015-04-03 06:45:56,53,2013-03-01 16:39:40,2015-01-03 22:01:44,1984-03-10,1694,"I'm on my periods, <br />\nI'm horny.<br />\nI...",2015-01-03 21:52:03,0,1
389808,F,0,3,4,0,2012-09-07,2015-02-25 15:26:01,15,0000-00-00 00:00:00,2012-10-06 09:50:54,1982-04-30,154884,I was read an article of another mother compla...,2015-01-10 10:00:16,3,1
389807,F,0,3,4,0,2012-09-07,2015-02-25 15:26:01,15,0000-00-00 00:00:00,2012-10-06 09:50:54,1982-04-30,154884,I was read an article of another mother compla...,2015-01-10 09:52:31,2,0
390770,F,0,5,1,0,2012-10-02,2015-05-22 02:16:45,61,2012-11-14 02:23:01,2014-11-04 17:25:10,1945-03-20,154884,How cracked out are you guys tonight?,2015-03-01 01:19:51,0,0
240087,F,0,1,3,0,2012-12-02,2015-06-04 18:32:59,5,0000-00-00 00:00:00,0000-00-00 00:00:00,1989-03-09,856092,About 8 years ago my now exhusband's friends r...,2015-04-02 18:52:22,11,6
389588,F,0,1,2,2,2013-02-23,2015-01-08 06:00:00,33,2015-01-01 02:51:21,2015-01-08 06:10:24,1999-03-31,154884,"I have a lot of best friends, however they are...",2015-01-01 03:06:13,0,0
390567,F,0,2,1,0,2013-03-09,2015-02-20 05:35:33,12,0000-00-00 00:00:00,2013-03-12 02:54:37,1997-05-31,154884,I wish that someone would kill me so it wouldn...,2015-02-20 05:42:24,1,1
133517,F,0,2,1,0,2013-03-09,2015-02-20 05:35:33,12,0000-00-00 00:00:00,2013-03-12 02:54:37,1997-05-31,2334,https://www.youtube.com/watch?v=aNG7Pyoj58I<br...,2015-02-20 05:52:15,0,0
392260,F,0,12,1,0,2013-03-29,2015-06-15 19:41:57,50,2014-06-10 15:47:32,2014-06-10 15:47:05,1988-01-31,154884,If I feel like you're pulling away even in the...,2015-05-17 21:49:27,6,0
138973,F,0,1,1,0,2013-05-03,2015-04-27 11:19:31,9,0000-00-00 00:00:00,0000-00-00 00:00:00,1983-09-30,996247,My daughters father and I were surprised when...,2015-02-22 08:39:24,0,0
129874,F,0,2,33,29,2013-07-15,2015-04-30 01:35:56,24,2015-02-18 16:55:16,2015-02-18 16:56:36,1987-12-31,487,The worst feeling is that I know he doesn't ev...,2015-02-18 17:13:26,3,0
510573,F,0,1,2,1,2013-08-14,2015-07-08 16:08:30,28,0000-00-00 00:00:00,2013-08-30 16:18:13,1991-01-31,967,A met a guy online who was super sweet and cha...,2015-07-03 07:58:14,0,3
489521,F,0,1,1,0,2013-12-10,2015-06-27 14:35:02,2,0000-00-00 00:00:00,2013-12-10 17:03:49,1990-03-31,30727,I am fine with my body but I don't like showin...,2015-06-27 02:42:37,0,0
17904,F,0,4,8,0,2013-12-23,2015-06-24 06:39:52,72,0000-00-00 00:00:00,2014-02-11 14:04:03,1998-05-31,114586,Looking for someone to chat/whatsapp :),2015-01-06 13:36:35,3,0
17824,F,0,4,8,0,2013-12-23,2015-06-24 06:39:52,72,0000-00-00 00:00:00,2014-02-11 14:04:03,1998-05-31,500488,I am looking for a penpal. I am a 16 year old ...,2015-01-06 13:00:47,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524524,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043849,Ventriloquist cowboy walks into town and sees ...,2015-07-07 10:20:25,1,0
524797,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043913,so wil ek sterf: skielik<br />\nsonder om iets...,2015-07-07 12:18:23,1,1
524830,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,35573,All the things my mother taught me:My mom taug...,2015-07-07 12:37:36,1,2
525161,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,523050,<img src='http://content-img.experienceproject...,2015-07-07 14:23:39,0,1
527596,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044306,<img src='http://content-img.experienceproject...,2015-07-08 06:04:04,0,0
528571,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,983955,<img src='http://content-img.experienceproject...,2015-07-08 13:09:55,0,0
528675,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044426,So we ordered this camera online...a bridge ty...,2015-07-08 13:50:17,0,0
528743,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044436,Ten worst gifts to buy a woman<br />\n1. Never...,2015-07-08 14:13:10,1,0
531806,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044717,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 10:32:37,0,0
532050,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,443195,A woman came home to find her retired husband ...,2015-07-09 12:15:04,0,0
510358,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1042437,<img src='http://content-img.experienceproject...,2015-07-03 06:37:46,2,2
510361,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,507232,<img src='http://content-img.experienceproject...,2015-07-03 06:39:47,2,0
510687,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,145497,"<iframe title=""YouTube video player"" class=""yo...",2015-07-03 08:51:31,2,0
511151,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1042519,<img src='http://content-img.experienceproject...,2015-07-03 12:01:58,2,2
511153,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,21890,<img src='http://content-img.experienceproject...,2015-07-03 12:03:21,2,0
511313,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,569936,<img src='http://content-img.experienceproject...,2015-07-03 12:59:55,5,2
516913,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043115,<img src='http://content-img.experienceproject...,2015-07-05 05:45:51,1,0
520348,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043423,"She: What do you love most, my natural beauty ...",2015-07-06 05:36:02,1,0
531099,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,3657,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:00:55,0,0
531102,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044635,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:02:43,0,0
531365,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044661,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 07:10:06,0,0
531513,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044685,Sylvia Plath<br />\n(1932 - 1963)<br />\nOn Lo...,2015-07-09 08:28:05,0,0
531921,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,12609,<img src='http://content-img.experienceproject...,2015-07-09 11:22:52,0,0
530861,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,522640,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 02:58:37,0,0
530915,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,216748,Phenomenal Woman<br />\nBY MAYA ANGELOU<br />\...,2015-07-09 03:24:09,1,0
499277,F,0,1,2,0,2015-06-30,2015-07-03 06:58:00,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1997-09-30,573842,"I love solitude. that's all, people think I fe...",2015-06-30 00:43:06,2,1
529139,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,216250,I too often find myself in stressful situation...,2015-07-08 16:41:07,0,0
529157,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,5314,I have been feeling lost & confused about life...,2015-07-08 16:48:13,0,0
530478,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,549438,I love the sound of Rain at night while laying...,2015-07-09 00:18:43,15,1
521870,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,117528,I am new here and would love to meet new peopl...,2015-07-06 16:26:55,0,2