In [1]:
dataFilePath = "/Users/dharshid/CDIPS_Project/data/EP_data.csv"
import pandas as pd
EPData = pd.read_csv(dataFilePath)

In [2]:
EPData.columns

Index([u'gender', u'num_groups', u'num_entries', u'num_fans', u'num_friends',
       u'created', u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments'],
      dtype='object')

In [3]:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

In [4]:
noGroupsUsers = EPData[EPData['num_groups'] == 0]

In [5]:
noGroupsUsers

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
2,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,49025,I accept the wisdom of all religions and disca...,2015-01-01 00:00:49,10,1
75,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,275667,Thongs and g-strings for me. They are my favor...,2015-01-01 00:30:17,8,3
85,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,655763,I cuddle you... You no cuddle me. (Only on spe...,2015-01-01 00:36:25,0,0
112,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,30197,I pray for my cousin as I know what's happenin...,2015-01-01 00:48:02,3,1
167,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,207878,I am rethinking everything I once thought abou...,2015-01-01 01:06:04,0,0
173,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,111499,I don't let my plants die. I let them live. If...,2015-01-01 01:08:35,4,1
176,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,1159,I am unemployed. I also like living the fast l...,2015-01-01 01:09:17,0,2
201,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,1431,I was watchin tv and i came across a glade com...,2015-01-01 01:19:16,1,2
220,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,310364,You know you're loser when you unadd everyone ...,2015-01-01 01:25:48,3,2
231,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,438995,"I wet bed again, it was so warm but now the co...",2015-01-01 01:30:21,33,7
260,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,972286,"I am in my late 20s, i have been to college fo...",2015-01-01 01:37:48,2,1
399,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,6466,I am a very big hopeless romantic but at times...,2015-01-01 02:47:34,3,0
418,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,60,He is my dream come true ðŸ˜˜ðŸ˜â¤ï¸,2015-01-01 03:00:03,6,1
479,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,199746,I'm forming a pack. Anyone wanna join?,2015-01-01 03:42:41,4,4
490,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,64973,Moonlit night at the beach 4 minutes before mi...,2015-01-01 03:58:42,1,0
503,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,335,Somebody talk so bored and lonely need someone...,2015-01-01 04:13:33,3,1
506,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,36348,I don't have high expectations but I know I de...,2015-01-01 04:15:35,1,0
549,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,972266,Can't you feel that change is in the air? It'...,2015-01-01 04:43:51,3,0
553,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,178886,I want to make a 'sharing' friend in the UK. I...,2015-01-01 04:46:57,9,5
657,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,193494,"Girls can't find their car keys, shoes or chap...",2015-01-01 05:58:57,8,2
720,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,273296,It's health related and has me knocked for a l...,2015-01-01 06:42:12,1,0
725,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,516393,We all do actually. Mom sister and I (dad when...,2015-01-01 06:47:59,10,4
741,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,426358,I've found Shemales with females is really pre...,2015-01-01 06:57:34,7,3
758,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,50780,I have a Flickr page. I use or upload photos d...,2015-01-01 07:09:47,0,1
788,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,1431,"I need you tonight - INXS, dedicating this to ...",2015-01-01 07:37:55,3,0
869,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,651297,"A few years ago, my husband and I went to a di...",2015-01-01 08:15:34,12,11
884,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,117528,hoo hoo ha ha I am new at ep love this site,2015-01-01 08:23:22,0,1
893,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,5273,born in august I will prove I am real Leo wann...,2015-01-01 08:26:11,3,3
899,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,296125,If you want my yahoo Id just message me,2015-01-01 08:29:17,0,1
903,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,2212,I love to dance in rain sometimes I enjoy rain...,2015-01-01 08:30:52,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531099,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,3657,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:00:55,0,0
531102,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044635,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:02:43,0,0
531182,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,290634,ISSS NUUUUUUUUUUDDDDDDDDDES,2015-07-09 05:46:11,4,2
531232,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,779919,I want to be with a woman. To feel her soft li...,2015-07-09 06:13:04,6,3
531235,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,616813,Ask me anything I'll answer!,2015-07-09 06:14:11,1,3
531365,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044661,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 07:10:06,0,0
531420,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,414720,I want to be with several people at one time. ...,2015-07-09 07:44:12,0,0
531513,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044685,Sylvia Plath<br />\n(1932 - 1963)<br />\nOn Lo...,2015-07-09 08:28:05,0,0
531806,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044717,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 10:32:37,0,0
531921,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,12609,<img src='http://content-img.experienceproject...,2015-07-09 11:22:52,0,0
532050,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,443195,A woman came home to find her retired husband ...,2015-07-09 12:15:04,0,0
532265,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,668668,My first time peeing at the cinema was with my...,2015-07-09 13:33:30,7,2
532270,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,571409,I'm looking for someone to control my bladder....,2015-07-09 13:35:10,5,1
532675,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,967,I met my bf on a dating app. Turns out he stil...,2015-07-09 16:01:53,0,1
532681,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,60638,Bf tied me up earlier and pounded me. The chai...,2015-07-09 16:02:48,5,2
532692,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,269780,Me and bf use a spider gag when he face bangs me,2015-07-09 16:05:36,0,0
533222,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,60049,It's been about 3-4 weeks since my man has bee...,2015-07-09 19:12:09,1,0
533330,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,101959,I absolutely adore them :) nothing more sexy t...,2015-07-09 19:52:15,3,1
533389,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,672527,I fit well in this category. I've always been ...,2015-07-09 20:08:28,19,10
533452,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,107900,"I'm bi and not ashamed but still not ""coming o...",2015-07-09 20:32:28,1,3
533455,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,5577,I am but not really into masculine guys i pref...,2015-07-09 20:33:45,2,2
533466,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,759408,I don't use them personally. It removes a lot ...,2015-07-09 20:37:29,12,4
533471,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,3543,Is anyone interested in some rp with me?,2015-07-09 20:39:10,4,1
533582,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,599269,Would someone like to rp? Message me please.,2015-07-09 21:30:57,8,6
533588,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,595035,someone tell me how to delete it,2015-07-09 21:32:05,0,1
533642,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,851475,I am :) i like taking sexy pics in them,2015-07-09 21:52:11,0,0
533652,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,69947,I am looking for my daddy ;* message me if you...,2015-07-09 21:55:43,1,1
533661,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,4603,Today I have been frustrated and stuff. My gir...,2015-07-09 22:00:15,0,1
533771,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,41615,it was absolutely fun to be nude on beach.. i ...,2015-07-09 22:38:10,3,0
533967,U,0,65535,5672,0,2008-04-21,2012-11-13 18:03:23,5,2009-03-27 21:22:12,0000-00-00 00:00:00,1989-03-09,334564,I want to do a tranny or cd :) i love looking ...,2015-07-09 23:40:51,0,0

In [6]:
EPData.loc[531099,:]

gender                                                                  F
num_groups                                                              0
num_entries                                                            28
num_fans                                                                1
num_friends                                                             0
created                                                        2015-06-20
last_login                                            2015-07-09 10:25:36
num_logins                                                             57
last_wall_activity                                    2015-07-09 12:57:31
last_circle_activity                                  2015-07-07 13:44:18
birthdate                                                      1964-11-30
gid                                                                  3657
content                 <iframe title="YouTube video player" class="yo...
date_posted                                           2015-07-09 05:00:55
votes                                                                   0
num_comments                                                            0
Name: 531099, dtype: object

In [7]:
noGroupsFemales = noGroupsUsers[noGroupsUsers['gender']=='F']

In [8]:
noGroupsFemales.sort(columns='created')

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
388303,F,0,2,1,0,2010-02-18,2015-04-02 10:53:19,5,0000-00-00 00:00:00,2010-12-03 21:55:25,1997-03-07,2475,I was in my exs house and we were in the livin...,2015-03-31 22:36:36,0,0
346613,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,In a really bad mood.<br />\nI feel like this ...,2015-05-12 09:06:54,3,1
139524,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,Relapsing- Part II<br />\n<br />\nI figured it...,2015-02-22 13:14:08,0,2
495416,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,Went on a date today.<br />\nSpent 4 hours wit...,2015-06-28 22:32:14,0,0
123029,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,"Aww Man, <br />\n<br />\nI notice that this fe...",2015-02-15 21:31:14,1,0
127956,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,192737,It's a white winter morning. There is a stilln...,2015-02-17 20:32:28,0,0
197590,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,192737,I have been waiting a very long time.<br />\nI...,2015-03-16 22:36:48,0,0
405651,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,What just happened to my story!? Ugh. I lost i...,2015-05-31 02:57:10,1,0
408193,F,0,53,25,17,2010-09-26,2015-06-28 23:16:39,169,2011-11-22 23:32:34,2015-05-12 22:50:56,1993-03-08,109,I'm struggling with something that I wanted to...,2015-05-31 23:25:17,2,2
391019,F,0,2,1,0,2011-04-21,2015-03-15 14:01:51,13,2015-03-15 08:28:13,0000-00-00 00:00:00,1997-03-07,154884,I'm addicted. I use sex as a way to tear away ...,2015-03-14 09:55:04,2,1
391018,F,0,2,1,0,2011-04-21,2015-03-15 14:01:51,13,2015-03-15 08:28:13,0000-00-00 00:00:00,1997-03-07,154884,I'm addicted. I use sex as a way to tear away ...,2015-03-14 09:52:49,1,1
391281,F,0,8,3,0,2011-12-01,2015-07-08 03:53:48,59,2015-04-07 20:32:40,2012-01-12 13:39:02,1979-03-12,154884,Its over 3 years since we have spoken.Â <br />...,2015-03-25 23:38:03,0,0
230785,F,0,30,71,3,2012-02-19,2015-07-07 20:32:59,1445,2015-06-21 10:53:34,2015-01-18 17:47:38,1989-03-09,635569,I'd choose you every time! If I had every guy ...,2015-03-29 22:00:01,0,0
388592,F,0,3,1,0,2012-03-29,2015-05-25 11:21:17,11,2015-05-22 08:16:01,2012-03-29 04:36:29,1994-08-31,2475,Me and my boyfriend that I am currently breaki...,2015-05-22 03:11:01,0,0
390300,F,0,1914,816,186,2012-04-03,2015-06-21 21:25:22,2078,2014-10-24 04:38:31,2014-11-09 12:41:10,1974-03-13,154884,"going to bed, aiiight, kids? goodnight, its be...",2015-02-06 01:19:10,1,0
9128,F,0,2,3,1,2012-08-03,2015-04-03 06:45:56,53,2013-03-01 16:39:40,2015-01-03 22:01:44,1984-03-10,1694,"I'm on my periods, <br />\nI'm horny.<br />\nI...",2015-01-03 21:52:03,0,1
389808,F,0,3,4,0,2012-09-07,2015-02-25 15:26:01,15,0000-00-00 00:00:00,2012-10-06 09:50:54,1982-04-30,154884,I was read an article of another mother compla...,2015-01-10 10:00:16,3,1
389807,F,0,3,4,0,2012-09-07,2015-02-25 15:26:01,15,0000-00-00 00:00:00,2012-10-06 09:50:54,1982-04-30,154884,I was read an article of another mother compla...,2015-01-10 09:52:31,2,0
390770,F,0,5,1,0,2012-10-02,2015-05-22 02:16:45,61,2012-11-14 02:23:01,2014-11-04 17:25:10,1945-03-20,154884,How cracked out are you guys tonight?,2015-03-01 01:19:51,0,0
240087,F,0,1,3,0,2012-12-02,2015-06-04 18:32:59,5,0000-00-00 00:00:00,0000-00-00 00:00:00,1989-03-09,856092,About 8 years ago my now exhusband's friends r...,2015-04-02 18:52:22,11,6
389588,F,0,1,2,2,2013-02-23,2015-01-08 06:00:00,33,2015-01-01 02:51:21,2015-01-08 06:10:24,1999-03-31,154884,"I have a lot of best friends, however they are...",2015-01-01 03:06:13,0,0
390567,F,0,2,1,0,2013-03-09,2015-02-20 05:35:33,12,0000-00-00 00:00:00,2013-03-12 02:54:37,1997-05-31,154884,I wish that someone would kill me so it wouldn...,2015-02-20 05:42:24,1,1
133517,F,0,2,1,0,2013-03-09,2015-02-20 05:35:33,12,0000-00-00 00:00:00,2013-03-12 02:54:37,1997-05-31,2334,https://www.youtube.com/watch?v=aNG7Pyoj58I<br...,2015-02-20 05:52:15,0,0
392260,F,0,12,1,0,2013-03-29,2015-06-15 19:41:57,50,2014-06-10 15:47:32,2014-06-10 15:47:05,1988-01-31,154884,If I feel like you're pulling away even in the...,2015-05-17 21:49:27,6,0
138973,F,0,1,1,0,2013-05-03,2015-04-27 11:19:31,9,0000-00-00 00:00:00,0000-00-00 00:00:00,1983-09-30,996247,My daughters father and I were surprised when...,2015-02-22 08:39:24,0,0
129874,F,0,2,33,29,2013-07-15,2015-04-30 01:35:56,24,2015-02-18 16:55:16,2015-02-18 16:56:36,1987-12-31,487,The worst feeling is that I know he doesn't ev...,2015-02-18 17:13:26,3,0
510573,F,0,1,2,1,2013-08-14,2015-07-08 16:08:30,28,0000-00-00 00:00:00,2013-08-30 16:18:13,1991-01-31,967,A met a guy online who was super sweet and cha...,2015-07-03 07:58:14,0,3
489521,F,0,1,1,0,2013-12-10,2015-06-27 14:35:02,2,0000-00-00 00:00:00,2013-12-10 17:03:49,1990-03-31,30727,I am fine with my body but I don't like showin...,2015-06-27 02:42:37,0,0
17904,F,0,4,8,0,2013-12-23,2015-06-24 06:39:52,72,0000-00-00 00:00:00,2014-02-11 14:04:03,1998-05-31,114586,Looking for someone to chat/whatsapp :),2015-01-06 13:36:35,3,0
17824,F,0,4,8,0,2013-12-23,2015-06-24 06:39:52,72,0000-00-00 00:00:00,2014-02-11 14:04:03,1998-05-31,500488,I am looking for a penpal. I am a 16 year old ...,2015-01-06 13:00:47,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524524,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043849,Ventriloquist cowboy walks into town and sees ...,2015-07-07 10:20:25,1,0
524797,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043913,so wil ek sterf: skielik<br />\nsonder om iets...,2015-07-07 12:18:23,1,1
524830,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,35573,All the things my mother taught me:My mom taug...,2015-07-07 12:37:36,1,2
525161,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,523050,<img src='http://content-img.experienceproject...,2015-07-07 14:23:39,0,1
527596,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044306,<img src='http://content-img.experienceproject...,2015-07-08 06:04:04,0,0
528571,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,983955,<img src='http://content-img.experienceproject...,2015-07-08 13:09:55,0,0
528675,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044426,So we ordered this camera online...a bridge ty...,2015-07-08 13:50:17,0,0
528743,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044436,Ten worst gifts to buy a woman<br />\n1. Never...,2015-07-08 14:13:10,1,0
531806,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044717,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 10:32:37,0,0
532050,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,443195,A woman came home to find her retired husband ...,2015-07-09 12:15:04,0,0
510358,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1042437,<img src='http://content-img.experienceproject...,2015-07-03 06:37:46,2,2
510361,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,507232,<img src='http://content-img.experienceproject...,2015-07-03 06:39:47,2,0
510687,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,145497,"<iframe title=""YouTube video player"" class=""yo...",2015-07-03 08:51:31,2,0
511151,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1042519,<img src='http://content-img.experienceproject...,2015-07-03 12:01:58,2,2
511153,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,21890,<img src='http://content-img.experienceproject...,2015-07-03 12:03:21,2,0
511313,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,569936,<img src='http://content-img.experienceproject...,2015-07-03 12:59:55,5,2
516913,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043115,<img src='http://content-img.experienceproject...,2015-07-05 05:45:51,1,0
520348,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1043423,"She: What do you love most, my natural beauty ...",2015-07-06 05:36:02,1,0
531099,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,3657,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:00:55,0,0
531102,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044635,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 05:02:43,0,0
531365,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044661,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 07:10:06,0,0
531513,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,1044685,Sylvia Plath<br />\n(1932 - 1963)<br />\nOn Lo...,2015-07-09 08:28:05,0,0
531921,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,12609,<img src='http://content-img.experienceproject...,2015-07-09 11:22:52,0,0
530861,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,522640,"<iframe title=""YouTube video player"" class=""yo...",2015-07-09 02:58:37,0,0
530915,F,0,28,1,0,2015-06-20,2015-07-09 10:25:36,57,2015-07-09 12:57:31,2015-07-07 13:44:18,1964-11-30,216748,Phenomenal Woman<br />\nBY MAYA ANGELOU<br />\...,2015-07-09 03:24:09,1,0
499277,F,0,1,2,0,2015-06-30,2015-07-03 06:58:00,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1997-09-30,573842,"I love solitude. that's all, people think I fe...",2015-06-30 00:43:06,2,1
529139,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,216250,I too often find myself in stressful situation...,2015-07-08 16:41:07,0,0
529157,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,5314,I have been feeling lost & confused about life...,2015-07-08 16:48:13,0,0
530478,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,549438,I love the sound of Rain at night while laying...,2015-07-09 00:18:43,15,1
521870,F,0,4,3,1,2015-07-06,2015-07-09 20:19:11,5,0000-00-00 00:00:00,2015-07-07 15:54:54,1990-01-31,117528,I am new here and would love to meet new peopl...,2015-07-06 16:26:55,0,2

In [9]:
groupNameFile = "/Users/dharshid/CDIPS_Project/data/group_names.csv"
groupNames = pd.read_csv(groupNameFile,header=None,names=['gid','group_name'])

In [10]:
groupNames.columns

Index([u'gid', u'group_name'], dtype='object')

In [11]:
groupNames[groupNames['gid']==109]

    gid         group_name
89  109  Battle Depression

In [12]:
EPData.sort(columns='birthdate')

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
228959,T,24,1,5,4,2015-03-27,2015-06-16 09:29:38,36,2015-03-28 05:00:39,2015-05-12 08:19:01,0001-01-31,1009499,<img src='http://content-img.experienceproject...,2015-03-29 05:20:45,1,1
129897,M,7,1,1,1,2015-02-18,2015-02-18 17:20:08,1,0000-00-00 00:00:00,0000-00-00 00:00:00,0402-12-31,673,i looking for a girl a pretty girl who will m...,2015-02-18 17:24:24,3,3
3232,F,7,2,1,0,2015-01-02,2015-01-02 00:24:49,1,0000-00-00 00:00:00,0000-00-00 00:00:00,0794-08-31,467330,I am so close I start to shake violently and t...,2015-01-02 00:51:56,0,0
3237,F,7,2,1,0,2015-01-02,2015-01-02 00:24:49,1,0000-00-00 00:00:00,0000-00-00 00:00:00,0794-08-31,467330,Please help when I close my eyes they are a di...,2015-01-02 00:53:22,0,0
290909,F,9,1,1,1,2015-04-21,2015-04-21 21:50:46,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1004-10-31,3459,I stay up late watching anime and reading. I'm...,2015-04-21 21:57:45,0,0
119849,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,20340,embarrasing. hope no one can see through my pa...,2015-02-14 16:26:30,2,1
70996,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,984783,i swear i was just 10 years old yesterday... d...,2015-01-25 16:13:22,0,0
341,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,148662,i really fucking miss you spencer... i hope yo...,2015-01-01 02:15:14,1,0
119780,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,992860,almost got caught masturbating with some dude ...,2015-02-14 15:51:51,0,0
71007,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,320285,it feeeels like were only going backwards â™ªâ...,2015-01-25 16:18:39,0,0
79210,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,986077,fuck. new phones ruined. i still miss you spen...,2015-01-28 18:21:52,0,0
71013,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,70815,cannot fucking wait to go to the bookstore nex...,2015-01-25 16:20:15,0,0
117857,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,923006,ughhhhh. cant wait to be home alone haha (;,2015-02-13 20:40:09,0,0
119784,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,992861,"Shoulders sideways, smack it, smack it in the ...",2015-02-14 15:54:52,0,1
79224,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,24172,awkward moment when some dude you barely know ...,2015-01-28 18:28:44,0,0
166013,F,9,1,2,1,2015-03-04,2015-03-04 19:46:08,1,0000-00-00 00:00:00,2015-03-04 20:14:02,1025-01-31,117528,Hi I don't like it when people judge others fo...,2015-03-04 20:12:54,2,1
409269,NaN,9,1,2,2,2015-06-01,2015-06-01 20:04:42,2,0000-00-00 00:00:00,0000-00-00 00:00:00,1030-01-31,349670,When I was young I would never brush my teeth....,2015-06-01 09:55:53,2,2
299348,F,2,1,1,0,2015-04-25,2015-04-25 04:13:10,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1061-03-31,143889,"I recently was ""let go"" from a dental office i...",2015-04-25 04:18:09,1,1
88459,F,1,1,4,2,2015-02-01,2015-02-11 11:36:49,9,2015-02-11 12:30:08,0000-00-00 00:00:00,1072-09-30,88051,I'm emotionally exhausted and beat down. My h...,2015-02-01 12:21:11,1,2
168911,M,9,1,1,0,2015-03-05,2015-03-05 21:30:29,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1078-01-31,1000763,Well...many decades online and this is my firs...,2015-03-05 22:12:18,0,0
261240,F,3,1,1,0,2013-10-31,2015-06-13 08:32:29,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1078-05-31,401848,I believe in marriage and would like to get ma...,2015-04-10 20:03:45,0,1
292181,F,9,1,2,0,2015-04-22,2015-04-22 11:26:11,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1085-04-30,157917,hubby likes to share me and watch me being fil...,2015-04-22 11:36:03,2,2
416030,M,14,1,2,0,2015-05-13,2015-06-03 19:54:54,8,0000-00-00 00:00:00,0000-00-00 00:00:00,1101-05-31,233,I wish I had a girlfriend that is between 14 a...,2015-06-03 16:51:20,0,2
152443,M,10,1,1,1,2015-02-27,2015-02-27 18:02:33,2,0000-00-00 00:00:00,0000-00-00 00:00:00,1102-11-30,998455,"I just found out that I had synesthesia today,...",2015-02-27 18:17:24,0,0
300813,NaN,1,1,1,0,2015-04-25,2015-04-25 18:16:24,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-06-30,1020143,"Love Rick Riordans ""Heroes of Olympus"" series....",2015-04-25 18:19:29,0,0
160029,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"Collapsing in on my self, I watch as the world...",2015-03-02 13:32:10,2,2
156498,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"Day after day, I wonder will I ever go out the...",2015-03-01 06:42:07,1,1
157677,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"Often I can't sleep for days, and everything s...",2015-03-01 15:57:26,2,1
165542,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"When the moment arrives, the one that you real...",2015-03-04 16:27:55,1,2
173023,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,To all the people who suffer for a wide and va...,2015-03-07 14:28:30,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491041,M,729,5,47,13,2015-06-27,2015-06-30 22:13:14,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,983984,me too.... wish I could do it again.,2015-06-27 15:55:43,0,0
532011,M,8,1,4,2,2015-07-08,2015-07-09 13:08:28,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,117528,Hi I made this account yesterday night so I th...,2015-07-09 11:57:13,0,1
531300,M,8,1,2,0,2015-07-09,2015-07-09 17:22:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,692409,"hey,im new here and was just hoping to meet ne...",2015-07-09 06:41:18,3,1
462509,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,294022,"When I look in the mirror, I see a girl nor bo...",2015-06-18 17:46:11,4,3
513495,M,262,9,15,15,2015-01-15,2015-07-09 19:35:48,11,0000-00-00 00:00:00,2015-01-17 17:01:15,2002-06-30,5029,I like CATS :)<br />\nreply if you do too,2015-07-04 03:26:13,1,1
482981,F,108,8,9,7,2015-06-18,2015-07-06 02:44:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,937157,jongkey64 is me OK No one over 17 plz I'M only 13,2015-06-25 00:13:29,0,0
461287,F,108,8,9,7,2015-06-18,2015-07-06 02:44:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,552602,when I'M bored and need Someone room talk to a...,2015-06-18 08:57:20,0,1
518024,F,108,8,9,7,2015-06-18,2015-07-06 02:44:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,937157,jongkey64 is me I don't talk to anyone over 17...,2015-07-05 14:25:13,0,1
502411,M,9,1,1,0,2015-06-30,2015-07-05 23:04:40,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,2805,I love being gemini but has anybody ever felt ...,2015-06-30 23:14:19,4,3
441074,F,9,12,37,2,2015-06-10,2015-07-10 01:32:40,4,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,364243,I can't wait until my step brothers go back to...,2015-06-11 21:43:33,0,1
475295,F,34,1,2,0,2015-06-22,2015-06-23 22:06:01,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,155309,I'm a therian from Land O' Lakes who is going ...,2015-06-22 16:21:07,0,0
493401,M,729,5,47,13,2015-06-27,2015-06-30 22:13:14,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,444604,so! I didn't mind. found more love from a man ...,2015-06-28 09:54:51,4,2
460882,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,400064,Ha! I started playing when I was 3. Still love...,2015-06-18 04:45:23,6,1
460863,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,222272,I like Asians because most of them are brought...,2015-06-18 04:35:28,7,0
447654,F,9,12,37,2,2015-06-10,2015-07-10 01:32:40,4,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,5043,This is what I drink when my parents aren't home,2015-06-14 02:13:58,0,1
453174,M,124,8,107,105,2015-06-15,2015-07-09 16:37:15,72,0000-00-00 00:00:00,2015-06-22 11:50:07,2002-06-30,117528,Well just joined and looking for friends,2015-06-15 20:28:03,1,1
529279,M,262,9,15,15,2015-01-15,2015-07-09 19:35:48,11,0000-00-00 00:00:00,2015-01-17 17:01:15,2002-06-30,276385,it tastes good so why not? it solves my proble...,2015-07-08 17:32:07,2,0
460859,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,64567,I couldn't give a poo about what people think ...,2015-06-18 04:33:45,10,0
447525,F,9,12,37,2,2015-06-10,2015-07-10 01:32:40,4,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,24933,Should I get a permanent tattoo,2015-06-14 01:24:22,0,3
435945,F,9,1,6,0,2015-06-10,2015-06-10 06:51:21,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,1035069,Will I be able to find the guy that is right f...,2015-06-10 06:58:54,0,0
529797,M,10,2,8,1,2015-07-08,2015-07-09 20:44:46,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,205860,I have been told I look more like 10-12. I rec...,2015-07-08 20:33:42,5,4
460852,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,166260,I always had a need to make a mark of importan...,2015-06-18 04:29:23,1,2
529274,M,262,9,15,15,2015-01-15,2015-07-09 19:35:48,11,0000-00-00 00:00:00,2015-01-17 17:01:15,2002-06-30,85983,have papa John's pizza with extra human I mean...,2015-07-08 17:29:21,0,0
437039,F,125,2,5,3,2015-06-10,2015-07-07 21:28:47,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,376866,Found one in my front yard,2015-06-10 15:09:00,0,0
499386,F,104,4,7,2,2015-06-30,2015-07-09 05:34:24,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,665290,I am absolutely in love with Mello from Death ...,2015-06-30 01:25:31,2,4
503362,F,34,3,22,0,2015-06-15,2015-07-10 00:56:24,23,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-07-31,530949,I am very shy and I am very busty for my age,2015-07-01 07:05:09,2,1
471271,F,34,3,22,0,2015-06-15,2015-07-10 00:56:24,23,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-07-31,1030263,My neighbors saw everything... What happened b...,2015-06-21 12:11:15,3,4
510400,F,34,3,22,0,2015-06-15,2015-07-10 00:56:24,23,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-07-31,2499,I don't like how big my boobs are especially f...,2015-07-03 07:03:10,1,2
57531,F,1,7,2,0,2007-03-19,2015-01-21 14:28:38,23,0000-00-00 00:00:00,2011-02-17 19:36:09,NaN,36135,I realize I have a problem.<br />\n<br />\nAnd...,2015-01-20 13:05:34,0,2
83809,NaN,10,6,1,0,2008-01-17,2015-02-10 10:48:02,105,2008-01-18 19:24:24,0000-00-00 00:00:00,NaN,293219,"I do too, but it ddrives me crazy when a child...",2015-01-30 14:12:47,0,0

In [13]:
dataFileWithUserIDs = "/Users/dharshid/CDIPS_Project/data/First100000_with_id.csv"
dataWithUserIDs = pd.read_csv(dataFileWithUserIDs)

In [14]:
dataWithUserIDs.head(10)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
0,0,0,0,F,210,54,25,2,2014-12-20,2015-04-03 12:45:01,...,0000-00-00 00:00:00,1997-03-31,124249,I just want my mom to hug me and say that she ...,2015-01-01 00:00:10,0,0,18,9343578,False
1,1,1,1,F,25,9,2,0,2014-08-28,2015-04-15 22:32:36,...,0000-00-00 00:00:00,1994-03-31,5276,I don't know why this is happening right now. ...,2015-01-01 00:00:46,0,0,21,8866629,False
2,2,3,3,M,153,2,6,5,2014-12-13,2015-06-01 20:34:52,...,2014-12-13 08:37:11,1993-11-30,58852,HAPPY NEW YEARS !!!!!!!!!!!!!!! !!!!!!!!!...,2015-01-01 00:02:39,1,2,21,9318824,False
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
7,7,8,8,M,250,255,1,0,2014-11-29,2015-03-25 09:23:41,...,0000-00-00 00:00:00,1982-11-30,962002,"Be of good character, should have an eighth gr...",2015-01-01 00:06:00,0,1,32,9270416,False
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True

In [15]:
dataWithUserIDs.columns

Index([u'Unnamed: 0', u'Unnamed: 0.1', u'Unnamed: 0.1', u'gender',
       u'num_groups', u'num_entries', u'num_fans', u'num_friends', u'created',
       u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments', u'age', u'uid',
       u'certainty'],
      dtype='object')

In [16]:
dataSorted = dataWithUserIDs.sort(columns='uid')
dataSorted

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
41477,41477,43822,43822,M,1261,1847,150,31,2014-04-03,2015-07-05 21:41:55,...,2015-07-05 21:31:28,1965-06-30,943026,"John ""Duke"" Wayne, one of the greats. A patrio...",2015-01-15 13:35:41,1,0,50,0,True
38577,38577,40748,40748,M,127,208,31,15,2014-09-29,2015-07-08 20:47:19,...,0000-00-00 00:00:00,1984-07-31,703085,I'm supposed to have given it up but can't. I ...,2015-01-14 11:26:58,2,3,30,0,True
38579,38579,40750,40750,M,127,208,31,15,2014-09-29,2015-07-08 20:47:19,...,0000-00-00 00:00:00,1984-07-31,8230,My brother bought me a half pound Reese peanut...,2015-01-14 11:28:45,4,0,30,0,True
75670,75670,80054,80054,NaN,114,10,123,9,2008-09-11,2015-06-17 00:09:47,...,0000-00-00 00:00:00,1993-03-08,611660,I prefer the look and love the feel!,2015-01-29 01:43:27,5,1,22,0,True
10865,10865,11512,11512,F,27,15,214,77,2015-01-03,2015-07-08 18:35:44,...,2015-07-06 08:09:39,1996-12-31,816685,So h o r ny very wet though. ;),2015-01-04 14:42:03,25,5,18,0,True
38644,38644,40817,40817,NaN,76,9,270,76,2015-01-04,2015-07-06 01:55:16,...,0000-00-00 00:00:00,1996-07-31,361728,I used to hide away behind a models photo here...,2015-01-14 12:13:50,19,10,18,0,True
20296,20296,21448,21448,M,339,49,123,116,2014-05-12,2015-07-09 09:20:40,...,2015-07-09 09:21:11,1972-09-30,502299,Well I would if I was wearing pants! But when ...,2015-01-07 17:14:02,2,0,42,0,True
60474,60474,63909,63909,NaN,1,1,1,0,2015-01-22,2015-06-29 20:15:51,...,2015-01-22 23:28:35,1994-08-31,185836,Hi everyone! I'm blessed to say that I am aliv...,2015-01-22 23:47:19,0,4,20,0,True
53080,53080,56164,56164,NaN,1,1,1,0,2015-01-19,2015-01-19 23:33:24,...,0000-00-00 00:00:00,1987-07-31,10201,Hello I am an independent coach and can recomm...,2015-01-19 23:03:22,0,0,27,0,True
38680,38680,40855,40855,M,42,39,45,31,2014-12-12,2015-06-30 12:35:52,...,2015-06-24 20:33:37,1996-03-31,980253,"Heya, this is gonna be my group since I've got...",2015-01-14 12:40:43,0,1,19,0,True
92176,92176,97530,97530,NaN,1,1,2,0,2015-02-02,2015-03-08 07:40:58,...,0000-00-00 00:00:00,1957-02-28,472492,I would love to to be a toilet slave for a you...,2015-02-05 06:58:27,0,1,58,0,True
38699,38699,40874,40874,U,15,1029,32,0,2012-01-29,2015-07-09 23:17:00,...,2015-07-07 19:44:53,1934-01-31,950332,The First Time I Ever Saw Your Face<br /><br /...,2015-01-14 12:57:07,0,0,81,0,True
60501,60501,63936,63936,NaN,14,1,1,0,2015-01-03,2015-02-07 22:20:38,...,2015-01-03 23:01:38,1965-08-31,357578,"I know me too. I have aaddos "" Adult attentio...",2015-01-22 23:58:53,0,0,49,0,True
20272,20272,21421,21421,NaN,5,1,1,0,2015-01-07,2015-01-07 17:09:57,...,0000-00-00 00:00:00,1990-09-30,643503,"Gym junkie, self taught artist, gamer, Maratho...",2015-01-07 17:01:33,1,0,24,0,True
66603,66603,70386,70386,NaN,18,10,5,4,2014-10-08,2015-06-09 06:21:44,...,2015-01-07 07:41:18,1964-06-30,109,With cuts to mental health services-and the fa...,2015-01-25 11:24:00,2,2,51,0,True
20269,20269,21418,21418,NaN,81,74,84,4,2008-11-09,2015-07-09 12:15:51,...,0000-00-00 00:00:00,1997-03-07,83826,Filled mine quite well on my friends couch and...,2015-01-07 16:59:33,6,1,18,0,True
66593,66593,70376,70376,F,261,798,436,14,2015-01-20,2015-07-09 13:13:15,...,2015-07-09 08:34:22,1975-01-31,2534,What do you plan on doing with the rest of you...,2015-01-25 11:18:04,5,27,40,0,True
83305,83305,88108,88108,NaN,35,15,3,2,2015-01-24,2015-06-14 11:44:26,...,0000-00-00 00:00:00,1987-09-30,762206,I feel so close to you right now.. today I tal...,2015-02-01 09:29:11,0,0,27,0,True
8040,8040,8571,8571,T,340,6,29,6,2015-01-03,2015-07-10 00:51:07,...,0000-00-00 00:00:00,1999-11-30,57772,Ever since I was little I wanted to be a girl....,2015-01-03 18:43:25,2,2,15,0,True
83314,83314,88118,88118,NaN,8,1,5,0,2015-02-01,2015-02-02 16:48:55,...,2015-02-01 09:35:20,1996-08-31,222619,I have been like this for as long as I can rem...,2015-02-01 09:34:03,4,2,18,0,True
38571,38571,40742,40742,NaN,2,1,4,2,2015-01-14,2015-01-15 01:38:43,...,2015-01-14 11:35:19,1985-01-31,980225,"I am in limbo, in between the sleep(dream) and...",2015-01-14 11:24:46,1,1,30,0,True
53019,53019,56101,56101,NaN,8,2,6,2,2015-01-03,2015-03-06 06:56:55,...,0000-00-00 00:00:00,1998-09-30,461909,Everyone is striving for every else's approval...,2015-01-19 22:40:47,0,0,16,0,True
75669,75669,80053,80053,NaN,114,10,123,9,2008-09-11,2015-06-17 00:09:47,...,0000-00-00 00:00:00,1993-03-08,290580,"I love the feeling of wearing thongs, I wear t...",2015-01-29 01:42:32,7,2,22,0,True
53211,53211,56297,56297,F,891,33,87,3,2014-12-23,2015-07-10 01:30:17,...,2015-01-11 18:09:01,1995-11-30,1996,I'm working my way through my sadness. A frien...,2015-01-20 00:08:57,3,2,19,0,True
92385,92385,97770,97770,NaN,2,2,1,0,2015-02-05,2015-02-08 17:44:27,...,0000-00-00 00:00:00,1970-05-31,988955,So here it is.After all these years of struggl...,2015-02-05 09:47:55,2,2,45,0,True
38389,38389,40552,40552,NaN,20,22,6,0,2015-01-10,2015-04-15 16:44:35,...,0000-00-00 00:00:00,1994-02-28,932781,Homework probably SHOULD be banned... but not ...,2015-01-14 10:00:09,0,0,21,0,True
60439,60439,63872,63872,NaN,316,18,382,100,2014-11-17,2015-07-09 22:33:30,...,2015-06-19 22:11:16,1975-02-28,456446,My boyfriend likes to have sexy time with othe...,2015-01-22 23:29:50,10,1,40,0,True
92373,92373,97753,97753,NaN,1,1,1,0,2015-02-05,2015-02-05 09:28:59,...,0000-00-00 00:00:00,1987-01-31,45456,Everything was going great... I got along with...,2015-02-05 09:34:29,0,0,28,0,True
38390,38390,40553,40553,NaN,14,16,1,0,2015-01-14,2015-01-14 06:06:39,...,0000-00-00 00:00:00,1963-10-31,2917,Most people who hate liars are the biggest lia...,2015-01-14 10:02:13,1,1,51,0,True
38401,38401,40564,40564,NaN,8,2,1,0,2015-01-14,2015-01-14 09:25:58,...,2015-01-14 09:37:30,1975-12-31,9222,I've been singing for as long as I can remembe...,2015-01-14 10:08:43,1,1,39,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99704,99704,105485,105485,F,59,1,2,1,2015-02-08,2015-02-08 19:44:44,...,0000-00-00 00:00:00,1996-09-30,896,I was really young when it started. 16 and it ...,2015-02-08 17:04:03,1,1,18,9519831,False
99738,99738,105522,105522,T,207,3,13,6,2015-02-08,2015-06-29 22:33:48,...,2015-06-12 23:31:34,1986-05-31,876505,"When I was but just a little boy, I always fel...",2015-02-08 17:28:15,0,1,29,9519883,True
99747,99747,105532,105532,M,38,1,1,0,2015-02-08,2015-02-09 19:43:41,...,0000-00-00 00:00:00,1994-05-31,644547,To me it feels like I can hear the soul speaki...,2015-02-08 17:37:54,0,0,21,9519928,False
99739,99739,105523,105523,M,22,7,14,13,2015-02-08,2015-07-01 16:05:20,...,2015-02-09 22:41:22,1993-06-30,293509,I know I have somes werewolf abilities grows i...,2015-02-08 17:32:12,0,2,22,9519954,True
99781,99781,105567,105567,F,51,17,67,11,2015-02-08,2015-07-08 19:02:41,...,0000-00-00 00:00:00,1999-07-31,534595,I've only ever been in one relationship with a...,2015-02-08 17:58:22,5,3,15,9519984,True
99766,99766,105551,105551,F,1173,19,54,27,2015-02-08,2015-02-26 18:33:24,...,0000-00-00 00:00:00,1989-12-31,39601,Can't sleep untill 7 am then owersleep almost ...,2015-02-08 17:51:00,2,4,25,9519992,True
99874,99874,105666,105666,F,38,10,2,0,2015-02-08,2015-06-14 17:46:54,...,0000-00-00 00:00:00,1981-12-31,722404,I have a coworker who drags in late because sh...,2015-02-08 18:58:55,2,2,33,9520006,True
99815,99815,105604,105604,F,6,1,2,0,2015-02-08,2015-02-09 22:06:56,...,0000-00-00 00:00:00,1996-12-31,17901,I'm currently 18 and I'm a senior in high scho...,2015-02-08 18:17:47,2,1,18,9520059,False
99936,99936,105730,105730,F,8,2,1,0,2015-02-08,2015-02-16 18:26:30,...,2015-02-08 18:52:57,1996-01-31,10201,I want to listen to those who are afraid to sp...,2015-02-08 19:40:20,0,0,19,9520085,False
99848,99848,105638,105638,F,8,2,1,0,2015-02-08,2015-02-16 18:26:30,...,2015-02-08 18:52:57,1996-01-31,990526,No matter how hard I try I can't bring myself ...,2015-02-08 18:41:59,0,0,19,9520085,False
99825,99825,105614,105614,F,8,1,1,0,2015-02-08,2015-02-08 18:13:56,...,0000-00-00 00:00:00,1990-08-31,990521,I have been seeing a guy in the Army for 2 yea...,2015-02-08 18:25:17,0,0,24,9520090,False
99820,99820,105609,105609,F,6,1,1,0,2015-02-08,2015-02-08 19:48:14,...,0000-00-00 00:00:00,1994-03-31,539671,Hi I'm Mattie to wants your name,2015-02-08 18:23:34,2,3,21,9520106,False
99898,99898,105690,105690,M,7,1,1,0,2015-02-08,2015-02-18 23:55:26,...,0000-00-00 00:00:00,1995-10-31,27388,I remember thinking as I held two magnets sout...,2015-02-08 19:10:16,0,0,19,9520125,True
99953,99953,105748,105748,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,86984,Still Miss It Sometimes But I Was Wronged-Dece...,2015-02-08 19:45:50,0,2,45,9520131,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99913,99913,105705,105705,F,6,1,1,0,2015-02-08,2015-03-01 19:13:57,...,0000-00-00 00:00:00,1990-01-31,152979,"After almost 2 years of dating, 1 year being l...",2015-02-08 19:21:55,0,3,25,9520133,True
99845,99845,105635,105635,M,27,1,1,0,2015-02-08,2015-02-08 19:08:25,...,0000-00-00 00:00:00,1955-02-28,990527,<img src='http://content-img.experienceproject...,2015-02-08 18:40:56,0,1,60,9520145,True
99864,99864,105656,105656,F,29,1,7,3,2015-02-08,2015-02-10 12:10:52,...,0000-00-00 00:00:00,1994-04-30,117528,"Well, this looked interesting enough...",2015-02-08 18:52:27,1,4,21,9520151,False
99860,99860,105652,105652,M,6,1,2,0,2015-02-08,2015-02-08 18:43:18,...,0000-00-00 00:00:00,1999-09-30,364243,"I'm 15 years old and gay, want to talk to some...",2015-02-08 18:50:55,0,0,15,9520170,False
99857,99857,105649,105649,F,7,2,1,0,2015-02-08,2015-02-08 18:53:21,...,2015-02-08 18:44:52,1985-12-31,89265,i had a myelogram in november 2014. when i cam...,2015-02-08 18:49:14,0,1,29,9520173,True
99863,99863,105655,105655,F,7,2,1,0,2015-02-08,2015-02-08 18:53:21,...,2015-02-08 18:44:52,1985-12-31,861164,"<iframe title=""YouTube video player"" class=""yo...",2015-02-08 18:52:25,1,0,29,9520173,True
99893,99893,105685,105685,F,16,2,3,0,2015-02-08,2015-02-09 18:51:41,...,0000-00-00 00:00:00,1996-12-31,8902,my uncle molested me since I was in kinder up ...,2015-02-08 19:07:09,4,2,18,9520191,False
99871,99871,105663,105663,F,16,2,3,0,2015-02-08,2015-02-09 18:51:41,...,0000-00-00 00:00:00,1996-12-31,150673,My boyfriend died In a car crash a year ago an...,2015-02-08 18:57:28,1,1,18,9520191,False
99922,99922,105714,105714,F,134,2,4,0,2015-02-08,2015-02-13 19:39:46,...,0000-00-00 00:00:00,1989-02-28,7258,I've recently discovered that I have had PTSD ...,2015-02-08 19:34:27,1,3,26,9520225,True
99912,99912,105704,105704,F,35,1,2,0,2015-02-08,2015-02-18 23:40:36,...,0000-00-00 00:00:00,1996-09-30,4603,It's my first year of college and I'm in a lon...,2015-02-08 19:20:17,3,7,18,9520235,False
99984,99984,105779,105779,M,11,1,2,0,2015-02-08,2015-02-18 10:37:42,...,0000-00-00 00:00:00,1976-12-31,990554,"I've been married for over 3yrs, together for ...",2015-02-08 20:02:43,1,0,38,9520256,False
99958,99958,105753,105753,F,178,1,23,6,2015-02-08,2015-03-06 20:04:00,...,0000-00-00 00:00:00,2000-09-30,1912,"To everyone I'm just the ""goody goody"" or ""the...",2015-02-08 19:47:05,10,5,14,9520286,True
99931,99931,105725,105725,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,728632,I feel like a wolf.....i long to run and smell...,2015-02-08 19:39:20,0,0,14,9520293,True
99961,99961,105756,105756,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,629012,I am part wolf....I've known this since I was ...,2015-02-08 19:47:48,0,0,14,9520293,True
99969,99969,105764,105764,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,368260,I know im part wolf...I've known since 3rd gra...,2015-02-08 19:55:07,1,4,14,9520293,True

In [17]:
dataSorted[~(dataSorted['uid']==0)]

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
69383,69383,73372,73372,F,1412,733,1561,338,2006-08-28,2015-07-08 14:26:11,...,2015-07-01 16:50:09,1979-03-12,13512,It might take Face powder to catch a man... bu...,2015-01-26 12:45:51,16,5,36,1062,True
50974,50974,53949,53949,F,30,28,88,53,2006-10-11,2015-02-05 22:57:31,...,2013-08-11 13:54:07,1989-03-09,247,Should probably preface this with the note tha...,2015-01-19 05:43:53,3,1,26,2168,True
44768,44768,47303,47303,F,2,3,0,0,2006-11-13,2015-01-16 20:21:56,...,2006-11-13 08:55:18,1989-03-09,181576,I am addicted to psychics and I am going to tr...,2015-01-16 20:24:17,1,1,26,3243,True
22952,22952,24230,24230,F,9,7,14,3,2006-11-27,2015-03-10 16:50:28,...,2011-01-31 23:13:13,1993-03-08,9648,I dreamt that i was having lower abdomen pains...,2015-01-08 16:17:39,1,3,22,6193,True
592,592,611,611,F,249,206,176,158,2007-02-11,2015-06-19 08:37:58,...,2014-10-25 12:15:38,1964-03-15,972333,I have care giver and her and I been together ...,2015-01-01 05:31:03,0,0,51,44448,True
62602,62602,66152,66152,F,25,26,29,7,2007-03-22,2015-07-06 09:25:02,...,2014-01-29 22:36:40,1989-03-09,2510,"so after my word vomit on Sunday, he was dista...",2015-01-23 22:22:45,5,2,26,47289,True
30338,30338,32050,32050,F,25,26,29,7,2007-03-22,2015-07-06 09:25:02,...,2014-01-29 22:36:40,1989-03-09,2510,he said it. he said he loves me. he said we ar...,2015-01-11 11:12:22,18,4,26,47289,True
50084,50084,52991,52991,F,25,26,29,7,2007-03-22,2015-07-06 09:25:02,...,2014-01-29 22:36:40,1989-03-09,2510,what is wrong with me?!! why do I open my big ...,2015-01-18 21:29:12,0,3,26,47289,True
78678,78678,83202,83202,F,59,126,202,108,2007-03-28,2015-05-02 04:04:38,...,2013-01-14 09:53:46,1979-03-12,63676,Science has been given too much credit. It ha...,2015-01-30 08:33:07,4,1,36,47664,True
94794,94794,100309,100309,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,989529,<img src='http://content-img.experienceproject...,2015-02-06 13:07:39,0,0,49,49208,True
93040,93040,98449,98449,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,6156,I have been in recovery now for quite a few 24...,2015-02-05 16:54:40,4,1,49,49208,True
94893,94893,100408,100408,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,17806,NOT ALL FEAR IS BAD<br />\nWhen we attain enli...,2015-02-06 14:16:24,0,0,49,49208,True
94277,94277,99761,99761,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,310,<img src='http://content-img.experienceproject...,2015-02-06 07:16:05,1,1,49,49208,True
92462,92462,97848,97848,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,9902,I am definitely suffering. Severe depression ...,2015-02-05 10:55:51,2,0,49,49208,True
91420,91420,96711,96711,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,453672,"<iframe title=""YouTube video player"" class=""yo...",2015-02-04 20:56:46,0,1,49,49208,True
94760,94760,100275,100275,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,989529,ACCEPTANCE ~ Accepting ~ Accept ~ <br />\nPrac...,2015-02-06 12:44:24,0,0,49,49208,True
93054,93054,98464,98464,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,8450,12 Ways You Can Love Yourself Now<br />\nLearn...,2015-02-05 17:03:54,2,1,49,49208,True
92440,92440,97826,97826,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,310,Outlander by Diana Gabaldon is my all time fav...,2015-02-05 10:37:38,1,2,49,49208,True
91410,91410,96701,96701,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,2332,I'd like to share with you a Buddhist meditati...,2015-02-04 20:50:36,5,2,49,49208,True
38673,38673,40848,40848,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,980251,Alright. I might block me because I am overly ...,2015-01-14 12:37:51,13,11,53,50049,True
59611,59611,63003,63003,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,321718,"<iframe title=""YouTube video player"" class=""yo...",2015-01-22 16:41:46,28,22,53,50049,True
62769,62769,66334,66334,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,321718,"<iframe title=""YouTube video player"" class=""yo...",2015-01-23 23:38:09,5,8,53,50049,True
25137,25137,26537,26537,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,976977,Isn't that wonderful? I think something taste...,2015-01-09 12:40:18,18,13,53,50049,True
97240,97240,102884,102884,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,989996,As a forward observer with the 1st of the 11th...,2015-02-07 15:55:39,12,13,53,50049,True
88423,88423,93516,93516,M,7,3,1,0,2007-05-20,2015-02-25 11:04:18,...,2015-01-29 11:02:16,2001-12-31,82621,"Just this christmas i got tickets to see the, ...",2015-02-03 13:24:32,1,0,13,53997,True
76395,76395,80803,80803,M,7,3,1,0,2007-05-20,2015-02-25 11:04:18,...,2015-01-29 11:02:16,2001-12-31,397229,I am in 7th grade and in algebra. It is really...,2015-01-29 10:57:29,0,4,13,53997,True
95070,95070,100601,100601,M,7,3,1,0,2007-05-20,2015-02-25 11:04:18,...,2015-01-29 11:02:16,2001-12-31,522535,Sometimes life sucks. And theres nothing you c...,2015-02-06 16:05:18,0,0,13,53997,True
54752,54752,57900,57900,F,258,42,480,452,2007-05-21,2015-07-05 12:20:05,...,2015-06-18 09:53:06,1993-03-08,165,I miss being with a woman...not just physicall...,2015-01-20 16:27:31,23,4,22,54180,True
28723,28723,30346,30346,M,23,17,21,18,2007-06-13,2015-07-09 18:32:27,...,2014-01-13 17:00:00,1973-10-31,645,I wish I had higher self esteem and more self ...,2015-01-10 19:55:37,6,4,41,59589,True
48803,48803,51602,51602,F,813,153,387,312,2007-06-29,2015-06-27 17:45:29,...,2015-03-15 19:11:58,1991-11-30,474530,"My relationship with my mom is... problematic,...",2015-01-18 12:19:02,1,0,23,77830,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99704,99704,105485,105485,F,59,1,2,1,2015-02-08,2015-02-08 19:44:44,...,0000-00-00 00:00:00,1996-09-30,896,I was really young when it started. 16 and it ...,2015-02-08 17:04:03,1,1,18,9519831,False
99738,99738,105522,105522,T,207,3,13,6,2015-02-08,2015-06-29 22:33:48,...,2015-06-12 23:31:34,1986-05-31,876505,"When I was but just a little boy, I always fel...",2015-02-08 17:28:15,0,1,29,9519883,True
99747,99747,105532,105532,M,38,1,1,0,2015-02-08,2015-02-09 19:43:41,...,0000-00-00 00:00:00,1994-05-31,644547,To me it feels like I can hear the soul speaki...,2015-02-08 17:37:54,0,0,21,9519928,False
99739,99739,105523,105523,M,22,7,14,13,2015-02-08,2015-07-01 16:05:20,...,2015-02-09 22:41:22,1993-06-30,293509,I know I have somes werewolf abilities grows i...,2015-02-08 17:32:12,0,2,22,9519954,True
99781,99781,105567,105567,F,51,17,67,11,2015-02-08,2015-07-08 19:02:41,...,0000-00-00 00:00:00,1999-07-31,534595,I've only ever been in one relationship with a...,2015-02-08 17:58:22,5,3,15,9519984,True
99766,99766,105551,105551,F,1173,19,54,27,2015-02-08,2015-02-26 18:33:24,...,0000-00-00 00:00:00,1989-12-31,39601,Can't sleep untill 7 am then owersleep almost ...,2015-02-08 17:51:00,2,4,25,9519992,True
99874,99874,105666,105666,F,38,10,2,0,2015-02-08,2015-06-14 17:46:54,...,0000-00-00 00:00:00,1981-12-31,722404,I have a coworker who drags in late because sh...,2015-02-08 18:58:55,2,2,33,9520006,True
99815,99815,105604,105604,F,6,1,2,0,2015-02-08,2015-02-09 22:06:56,...,0000-00-00 00:00:00,1996-12-31,17901,I'm currently 18 and I'm a senior in high scho...,2015-02-08 18:17:47,2,1,18,9520059,False
99936,99936,105730,105730,F,8,2,1,0,2015-02-08,2015-02-16 18:26:30,...,2015-02-08 18:52:57,1996-01-31,10201,I want to listen to those who are afraid to sp...,2015-02-08 19:40:20,0,0,19,9520085,False
99848,99848,105638,105638,F,8,2,1,0,2015-02-08,2015-02-16 18:26:30,...,2015-02-08 18:52:57,1996-01-31,990526,No matter how hard I try I can't bring myself ...,2015-02-08 18:41:59,0,0,19,9520085,False
99825,99825,105614,105614,F,8,1,1,0,2015-02-08,2015-02-08 18:13:56,...,0000-00-00 00:00:00,1990-08-31,990521,I have been seeing a guy in the Army for 2 yea...,2015-02-08 18:25:17,0,0,24,9520090,False
99820,99820,105609,105609,F,6,1,1,0,2015-02-08,2015-02-08 19:48:14,...,0000-00-00 00:00:00,1994-03-31,539671,Hi I'm Mattie to wants your name,2015-02-08 18:23:34,2,3,21,9520106,False
99898,99898,105690,105690,M,7,1,1,0,2015-02-08,2015-02-18 23:55:26,...,0000-00-00 00:00:00,1995-10-31,27388,I remember thinking as I held two magnets sout...,2015-02-08 19:10:16,0,0,19,9520125,True
99953,99953,105748,105748,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,86984,Still Miss It Sometimes But I Was Wronged-Dece...,2015-02-08 19:45:50,0,2,45,9520131,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99913,99913,105705,105705,F,6,1,1,0,2015-02-08,2015-03-01 19:13:57,...,0000-00-00 00:00:00,1990-01-31,152979,"After almost 2 years of dating, 1 year being l...",2015-02-08 19:21:55,0,3,25,9520133,True
99845,99845,105635,105635,M,27,1,1,0,2015-02-08,2015-02-08 19:08:25,...,0000-00-00 00:00:00,1955-02-28,990527,<img src='http://content-img.experienceproject...,2015-02-08 18:40:56,0,1,60,9520145,True
99864,99864,105656,105656,F,29,1,7,3,2015-02-08,2015-02-10 12:10:52,...,0000-00-00 00:00:00,1994-04-30,117528,"Well, this looked interesting enough...",2015-02-08 18:52:27,1,4,21,9520151,False
99860,99860,105652,105652,M,6,1,2,0,2015-02-08,2015-02-08 18:43:18,...,0000-00-00 00:00:00,1999-09-30,364243,"I'm 15 years old and gay, want to talk to some...",2015-02-08 18:50:55,0,0,15,9520170,False
99857,99857,105649,105649,F,7,2,1,0,2015-02-08,2015-02-08 18:53:21,...,2015-02-08 18:44:52,1985-12-31,89265,i had a myelogram in november 2014. when i cam...,2015-02-08 18:49:14,0,1,29,9520173,True
99863,99863,105655,105655,F,7,2,1,0,2015-02-08,2015-02-08 18:53:21,...,2015-02-08 18:44:52,1985-12-31,861164,"<iframe title=""YouTube video player"" class=""yo...",2015-02-08 18:52:25,1,0,29,9520173,True
99893,99893,105685,105685,F,16,2,3,0,2015-02-08,2015-02-09 18:51:41,...,0000-00-00 00:00:00,1996-12-31,8902,my uncle molested me since I was in kinder up ...,2015-02-08 19:07:09,4,2,18,9520191,False
99871,99871,105663,105663,F,16,2,3,0,2015-02-08,2015-02-09 18:51:41,...,0000-00-00 00:00:00,1996-12-31,150673,My boyfriend died In a car crash a year ago an...,2015-02-08 18:57:28,1,1,18,9520191,False
99922,99922,105714,105714,F,134,2,4,0,2015-02-08,2015-02-13 19:39:46,...,0000-00-00 00:00:00,1989-02-28,7258,I've recently discovered that I have had PTSD ...,2015-02-08 19:34:27,1,3,26,9520225,True
99912,99912,105704,105704,F,35,1,2,0,2015-02-08,2015-02-18 23:40:36,...,0000-00-00 00:00:00,1996-09-30,4603,It's my first year of college and I'm in a lon...,2015-02-08 19:20:17,3,7,18,9520235,False
99984,99984,105779,105779,M,11,1,2,0,2015-02-08,2015-02-18 10:37:42,...,0000-00-00 00:00:00,1976-12-31,990554,"I've been married for over 3yrs, together for ...",2015-02-08 20:02:43,1,0,38,9520256,False
99958,99958,105753,105753,F,178,1,23,6,2015-02-08,2015-03-06 20:04:00,...,0000-00-00 00:00:00,2000-09-30,1912,"To everyone I'm just the ""goody goody"" or ""the...",2015-02-08 19:47:05,10,5,14,9520286,True
99931,99931,105725,105725,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,728632,I feel like a wolf.....i long to run and smell...,2015-02-08 19:39:20,0,0,14,9520293,True
99961,99961,105756,105756,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,629012,I am part wolf....I've known this since I was ...,2015-02-08 19:47:48,0,0,14,9520293,True
99969,99969,105764,105764,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,368260,I know im part wolf...I've known since 3rd gra...,2015-02-08 19:55:07,1,4,14,9520293,True

In [18]:
dataGroupSorted = dataWithUserIDs.sort(columns = 'gid')
dataGroupSorted

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
24525,24525,25890,25890,M,679,153,102,100,2014-09-27,2015-07-09 15:19:02,...,2015-07-02 23:45:19,1999-12-31,24,I still believe in you buddy!,2015-01-09 06:45:04,2,1,15,9021103,True
93434,93434,98864,98864,F,400,470,334,13,2014-07-07,2015-07-09 15:39:55,...,2015-05-29 20:59:28,1995-06-30,30,I love all his skits especially Clueless Gamer...,2015-02-05 20:21:44,1,1,20,8557823,True
94681,94681,100190,100190,M,189,20,24,13,2015-01-31,2015-05-02 05:09:52,...,2015-05-02 05:14:11,1963-06-30,30,I worked for Him when he was here in NY at NBC...,2015-02-06 11:49:26,0,0,52,9492389,True
23445,23445,24751,24751,F,39,14,23,5,2010-02-15,2015-02-25 05:42:43,...,2011-04-07 22:47:53,1993-03-08,37,Got 3 taken out today. I was shaking like a he...,2015-01-08 20:11:23,4,2,22,2421583,False
10122,10122,10733,10733,F,76,25,11,4,2010-05-03,2015-06-01 16:15:02,...,0000-00-00 00:00:00,1993-03-08,37,I got all 4 of mine out. I was anxious at firs...,2015-01-04 09:47:21,1,3,22,2628017,True
39325,39325,41545,41545,M,527,117,162,45,2014-07-31,2015-07-08 19:19:48,...,2015-05-18 17:44:25,1981-08-31,39,Pretty sure I'd rather be water boarded than t...,2015-01-14 17:35:58,3,1,33,8707170,True
76085,76085,80488,80488,F,140,59,346,52,2014-10-18,2015-04-23 23:58:43,...,2015-01-29 08:11:22,1996-02-29,39,You ever have one of those days when you wake ...,2015-01-29 07:39:46,8,4,19,9109324,True
39508,39508,41740,41740,F,541,358,867,414,2013-09-14,2015-07-09 16:20:22,...,2014-10-19 16:27:27,1999-04-30,39,One of my wisdom tooth a started to come thoug...,2015-01-14 19:00:42,1,0,16,7039997,True
53727,53727,56836,56836,F,40,15,5,2,2015-01-19,2015-05-02 00:45:21,...,0000-00-00 00:00:00,1986-05-31,41,4:15 am<br />\n<br />\nI have a 12+ hour day a...,2015-01-20 06:16:52,1,2,29,9452789,False
63641,63641,67234,67234,M,577,140,186,78,2013-03-22,2015-07-09 19:37:48,...,2015-04-16 00:11:11,1994-09-30,41,I think too much usually staying up to midnigh...,2015-01-24 08:59:05,0,0,20,6156098,True
5237,5237,5575,5575,F,93,23,119,10,2014-08-28,2015-05-28 16:06:06,...,0000-00-00 00:00:00,2001-05-31,41,I hate it. :( Sometimes I am up all night coun...,2015-01-02 20:01:53,2,2,14,8871629,True
4111,4111,4372,4372,F,640,67,449,121,2014-07-09,2015-06-06 22:03:20,...,2015-02-01 18:28:03,1997-08-31,41,Have to be up in 5 minutes. Haven't slept at a...,2015-01-02 11:56:16,4,3,17,8570454,True
28449,28449,30053,30053,F,242,127,193,3,2014-02-25,2015-07-06 15:27:46,...,2014-07-27 12:47:01,2000-07-31,41,"It's midnight, so what that really means is st...",2015-01-10 18:04:49,1,0,14,7940213,True
64377,64377,68013,68013,F,161,48,378,113,2012-12-29,2015-07-08 18:18:25,...,2015-05-29 18:58:49,1997-03-31,41,So complicated. Why do I have insomnia? I'm th...,2015-01-24 15:23:29,0,0,18,5821474,True
12643,12643,13391,13391,F,801,319,777,164,2014-07-08,2015-07-10 00:43:50,...,2015-03-02 13:59:15,1998-01-31,41,So I can't sleep and I start school again in l...,2015-01-05 01:57:55,7,5,17,8565409,True
37466,37466,39592,39592,M,24,9,3,1,2014-12-19,2015-04-03 21:08:06,...,0000-00-00 00:00:00,1996-07-31,41,I can never sleep on time either. I usually ge...,2015-01-14 00:04:55,0,0,18,9340953,False
12981,12981,13739,13739,M,215,22,16,13,2014-12-31,2015-06-22 00:11:37,...,0000-00-00 00:00:00,1999-07-31,41,I remember a day i used to go to bed at 11 pm ...,2015-01-05 05:51:55,2,2,15,9380735,True
35068,35068,37044,37044,F,801,319,777,164,2014-07-08,2015-07-10 00:43:50,...,2015-03-02 13:59:15,1998-01-31,41,It's 1:30 am and I'm wide awake with no one to...,2015-01-13 02:33:48,3,2,17,8565409,True
20263,20263,21412,21412,F,385,213,311,19,2012-04-17,2015-07-09 12:46:07,...,2015-07-09 13:23:27,1977-09-30,41,"For the past week, I haven't been able to slee...",2015-01-07 16:56:46,2,2,37,4908068,True
20555,20555,21719,21719,M,189,528,131,43,2014-07-27,2015-07-09 11:16:51,...,2014-08-04 14:25:04,1994-05-31,41,Well it's been 24 hours and still no sleep... ...,2015-01-07 19:03:26,1,2,21,8678482,True
12930,12930,13687,13687,F,542,101,669,202,2013-08-10,2015-07-07 11:06:55,...,2014-10-28 09:53:51,1975-10-31,41,I used to go to bed and get up around the same...,2015-01-05 05:17:23,4,3,39,6775467,True
79357,79357,83910,83910,F,106,170,794,414,2014-09-16,2015-07-08 13:28:51,...,2015-06-25 15:54:16,1920-03-31,41,Usually I do not have a reason why I stay up l...,2015-01-30 15:08:03,6,2,95,0,True
27648,27648,29212,29212,F,218,232,109,8,2014-11-20,2015-01-28 10:10:36,...,0000-00-00 00:00:00,1982-01-31,41,sorry.me again.<br />\n2:48 am.my heart is bea...,2015-01-10 11:54:25,3,1,33,9238698,True
22079,22079,23322,23322,M,92,32,73,29,2013-09-05,2015-07-09 15:57:52,...,2015-07-08 20:10:09,1986-05-31,41,Fuck me. Another sleepless night. It wouldn't ...,2015-01-08 08:40:45,4,3,29,6976922,True
27261,27261,28776,28776,F,218,232,109,8,2014-11-20,2015-01-28 10:10:36,...,0000-00-00 00:00:00,1982-01-31,41,i have horrible sleeping problems. <br />\ni u...,2015-01-10 08:31:51,0,1,33,9238698,True
87213,87213,92233,92233,F,70,18,25,6,2015-02-01,2015-04-16 18:26:18,...,0000-00-00 00:00:00,1984-12-31,41,I always seem to be wide awake on the nights t...,2015-02-02 22:31:04,2,4,30,9494886,True
99230,99230,104991,104991,F,675,48,96,1,2015-01-11,2015-07-09 22:35:08,...,2015-07-08 19:51:43,1997-05-31,41,The longest I couldn't sleep was for 5 days st...,2015-02-08 13:07:05,3,1,18,9422865,True
6617,6617,7048,7048,M,1080,223,743,713,2015-01-01,2015-07-09 15:59:46,...,2015-03-24 18:19:52,2000-02-29,41,The clock is torturing us<br />\nLife has lost...,2015-01-03 07:42:07,1,1,15,9386599,True
6622,6622,7053,7053,M,1080,223,743,713,2015-01-01,2015-07-09 15:59:46,...,2015-03-24 18:19:52,2000-02-29,41,"From the tick and the tock<br />\nWhite Noise,...",2015-01-03 07:44:02,1,0,15,9386599,True
69085,69085,73031,73031,F,6,1,1,0,2015-01-26,2015-01-28 09:08:18,...,0000-00-00 00:00:00,1990-12-31,41,"Hello,<br />\nI am a journalist working on a f...",2015-01-26 10:01:57,0,1,24,9474785,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99510,99510,105285,105285,T,7,4,1,0,2014-12-05,2015-06-07 01:03:59,...,0000-00-00 00:00:00,1987-08-31,990448,If you'd like to rank properly in the major se...,2015-02-08 15:27:48,0,1,27,9291884,True
99526,99526,105301,105301,M,544,21,31,6,2013-07-13,2015-06-13 21:21:36,...,2015-04-21 08:34:46,1953-10-31,990450,I am not finding many people my age group here...,2015-02-08 15:36:24,3,4,61,6586735,True
99830,99830,105619,105619,M,17,2,1,0,2015-02-07,2015-07-05 18:17:36,...,0000-00-00 00:00:00,1983-11-30,990453,I started dating this girl 4 days ago and we h...,2015-02-08 18:28:52,0,0,31,9514075,True
99536,99536,105311,105311,F,109,71,42,15,2015-02-05,2015-02-27 07:22:28,...,2015-02-20 19:33:48,1989-04-30,990455,I dont know if I lm bisexual. I like boobs. I ...,2015-02-08 15:43:48,0,0,26,9507985,False
99540,99540,105316,105316,U,10,6,2,1,2012-10-16,2015-05-30 14:58:36,...,2014-07-26 11:59:13,1984-05-31,990458,No need to give you my story (you dont care to...,2015-02-08 15:47:04,1,1,31,5564192,True
99546,99546,105322,105322,F,721,338,1482,1140,2012-06-18,2015-07-08 17:15:24,...,2015-06-03 09:33:00,1990-08-31,990461,Are you incapable of doing so yourself? Why mu...,2015-02-08 15:50:28,4,3,24,5118936,True
99556,99556,105332,105332,F,1406,1793,1347,20,2014-03-30,2015-07-10 01:16:28,...,2015-07-09 14:56:02,1963-03-31,990464,"... but only by one or two (or three or four, ...",2015-02-08 15:53:15,1,2,52,8096295,True
99567,99567,105343,105343,F,98,5,230,150,2014-08-04,2015-07-09 10:54:37,...,2015-07-02 19:55:02,1995-01-31,990466,You answered my question but still we talked f...,2015-02-08 15:59:04,6,5,20,8728421,True
99571,99571,105347,105347,M,138,12,64,59,2015-01-20,2015-04-28 06:25:37,...,2015-03-21 21:53:24,1975-08-31,990467,The sports illustrated plus size model issue l...,2015-02-08 16:00:48,1,0,39,9455572,True
99581,99581,105357,105357,F,31,1943,241,12,2012-10-03,2015-07-09 17:27:45,...,2015-07-09 17:28:10,1964-03-15,990469,This song brought back a rush of good memories...,2015-02-08 16:04:54,0,1,51,5519534,True
99583,99583,105359,105359,F,248,21,63,22,2015-02-07,2015-07-09 19:58:15,...,2015-07-09 20:56:59,1997-04-30,990471,It makes me really happy when a guy is really ...,2015-02-08 16:05:13,0,0,18,9515519,True
99601,99601,105378,105378,F,3,2,2,0,2014-10-03,2015-05-24 20:55:44,...,2015-05-18 01:48:51,1972-06-30,990472,I love my boyfriend of a year and a half and h...,2015-02-08 16:13:00,0,2,43,9047758,True
99604,99604,105381,105381,M,4,4,1,0,2014-12-02,2015-06-05 06:09:34,...,0000-00-00 00:00:00,1986-01-31,990473,Will you be to the look out for web hosting in...,2015-02-08 16:13:49,0,1,29,9282695,True
99612,99612,105389,105389,M,9,8,1,0,2014-12-05,2015-06-04 07:45:58,...,0000-00-00 00:00:00,1985-03-31,990474,"<iframe title=""YouTube video player"" class=""yo...",2015-02-08 16:17:29,0,1,30,9291759,False
99649,99649,105427,105427,U,3,1,1,0,2014-08-22,2015-02-24 18:47:34,...,0000-00-00 00:00:00,1989-08-31,990478,If an individual experienced requested me 6 mo...,2015-02-08 16:34:45,0,1,25,8837465,True
99655,99655,105433,105433,M,5,4,4,0,2015-01-09,2015-05-20 11:09:04,...,0000-00-00 00:00:00,1995-05-31,990482,I am a 15 year old boy and my sister is 17. In...,2015-02-08 16:39:04,0,0,20,9417468,False
99732,99732,105516,105516,M,5,1,5,1,2014-02-26,2015-04-13 17:07:07,...,0000-00-00 00:00:00,1994-11-30,990495,Living in nj. Can't travel so only people who ...,2015-02-08 17:24:20,0,1,20,7943319,True
99744,99744,105529,105529,M,11,2,2,1,2015-02-08,2015-03-17 01:14:08,...,2015-02-08 18:08:27,1991-04-30,990499,"Hey, I dunno whats up with me, but in all my p...",2015-02-08 17:35:42,0,0,24,9519809,True
99749,99749,105534,105534,F,8,2,11,3,2012-08-01,2015-02-19 15:32:04,...,2014-08-25 16:34:14,1984-03-10,990501,<img src='http://content-img.experienceproject...,2015-02-08 17:39:13,0,0,31,5288053,False
99808,99808,105596,105596,M,137,7,117,96,2014-07-01,2015-07-09 22:10:15,...,2015-04-29 23:34:03,1972-10-31,990515,its been a while but have an evening to myself...,2015-02-08 18:13:55,4,4,42,8525284,True
99825,99825,105614,105614,F,8,1,1,0,2015-02-08,2015-02-08 18:13:56,...,0000-00-00 00:00:00,1990-08-31,990521,I have been seeing a guy in the Army for 2 yea...,2015-02-08 18:25:17,0,0,24,9520090,False
99833,99833,105622,105622,F,2,6,2,0,2012-02-28,2015-02-08 18:20:46,...,2012-02-28 17:56:50,1997-03-31,990523,"I consider myself to be a movie aficionado, bu...",2015-02-08 18:30:16,0,0,18,4743254,True
99848,99848,105638,105638,F,8,2,1,0,2015-02-08,2015-02-16 18:26:30,...,2015-02-08 18:52:57,1996-01-31,990526,No matter how hard I try I can't bring myself ...,2015-02-08 18:41:59,0,0,19,9520085,False
99845,99845,105635,105635,M,27,1,1,0,2015-02-08,2015-02-08 19:08:25,...,0000-00-00 00:00:00,1955-02-28,990527,<img src='http://content-img.experienceproject...,2015-02-08 18:40:56,0,1,60,9520145,True
99847,99847,105637,105637,F,692,119,618,239,2015-01-23,2015-07-09 20:41:49,...,2015-07-09 23:51:01,2000-03-31,990528,I never was but yesterday my sister got a long...,2015-02-08 18:41:45,8,11,15,9465417,True
99882,99882,105674,105674,M,999,482,179,90,2014-08-31,2015-07-10 01:33:56,...,2015-07-09 22:11:32,1972-02-29,990531,<img src='http://images.epcdn.net/images/pictu...,2015-02-08 19:01:21,2,0,43,8888331,True
99934,99934,105728,105728,M,4,2,1,0,2014-11-20,2015-03-08 10:30:12,...,0000-00-00 00:00:00,1989-03-31,990550,Book a Room at Reservation for the hampton inn...,2015-02-08 19:40:15,0,0,26,9237410,False
99966,99966,105761,105761,M,64,25,29,24,2014-09-22,2015-07-09 20:16:36,...,2015-07-09 16:44:24,1999-06-30,990552,I want a chub to smother me with his fat,2015-02-08 19:52:56,2,1,16,8997675,True
99974,99974,105769,105769,F,16,11,4,3,2014-11-17,2015-07-04 10:13:58,...,2015-03-22 19:57:20,1975-03-31,990553,Even though I'm clearly gay I still get approa...,2015-02-08 19:58:45,0,0,40,9226696,True
99984,99984,105779,105779,M,11,1,2,0,2015-02-08,2015-02-18 10:37:42,...,0000-00-00 00:00:00,1976-12-31,990554,"I've been married for over 3yrs, together for ...",2015-02-08 20:02:43,1,0,38,9520256,False

In [19]:
EPBirthdateSorted = EPData.sort(columns='birthdate')
EPBirthdateSorted

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
228959,T,24,1,5,4,2015-03-27,2015-06-16 09:29:38,36,2015-03-28 05:00:39,2015-05-12 08:19:01,0001-01-31,1009499,<img src='http://content-img.experienceproject...,2015-03-29 05:20:45,1,1
129897,M,7,1,1,1,2015-02-18,2015-02-18 17:20:08,1,0000-00-00 00:00:00,0000-00-00 00:00:00,0402-12-31,673,i looking for a girl a pretty girl who will m...,2015-02-18 17:24:24,3,3
3232,F,7,2,1,0,2015-01-02,2015-01-02 00:24:49,1,0000-00-00 00:00:00,0000-00-00 00:00:00,0794-08-31,467330,I am so close I start to shake violently and t...,2015-01-02 00:51:56,0,0
3237,F,7,2,1,0,2015-01-02,2015-01-02 00:24:49,1,0000-00-00 00:00:00,0000-00-00 00:00:00,0794-08-31,467330,Please help when I close my eyes they are a di...,2015-01-02 00:53:22,0,0
290909,F,9,1,1,1,2015-04-21,2015-04-21 21:50:46,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1004-10-31,3459,I stay up late watching anime and reading. I'm...,2015-04-21 21:57:45,0,0
119849,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,20340,embarrasing. hope no one can see through my pa...,2015-02-14 16:26:30,2,1
70996,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,984783,i swear i was just 10 years old yesterday... d...,2015-01-25 16:13:22,0,0
341,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,148662,i really fucking miss you spencer... i hope yo...,2015-01-01 02:15:14,1,0
119780,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,992860,almost got caught masturbating with some dude ...,2015-02-14 15:51:51,0,0
71007,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,320285,it feeeels like were only going backwards â™ªâ...,2015-01-25 16:18:39,0,0
79210,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,986077,fuck. new phones ruined. i still miss you spen...,2015-01-28 18:21:52,0,0
71013,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,70815,cannot fucking wait to go to the bookstore nex...,2015-01-25 16:20:15,0,0
117857,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,923006,ughhhhh. cant wait to be home alone haha (;,2015-02-13 20:40:09,0,0
119784,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,992861,"Shoulders sideways, smack it, smack it in the ...",2015-02-14 15:54:52,0,1
79224,F,74,14,9,5,2014-11-15,2015-02-15 11:40:30,37,2014-11-15 20:58:17,2015-01-25 16:05:58,1017-03-31,24172,awkward moment when some dude you barely know ...,2015-01-28 18:28:44,0,0
166013,F,9,1,2,1,2015-03-04,2015-03-04 19:46:08,1,0000-00-00 00:00:00,2015-03-04 20:14:02,1025-01-31,117528,Hi I don't like it when people judge others fo...,2015-03-04 20:12:54,2,1
409269,NaN,9,1,2,2,2015-06-01,2015-06-01 20:04:42,2,0000-00-00 00:00:00,0000-00-00 00:00:00,1030-01-31,349670,When I was young I would never brush my teeth....,2015-06-01 09:55:53,2,2
299348,F,2,1,1,0,2015-04-25,2015-04-25 04:13:10,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1061-03-31,143889,"I recently was ""let go"" from a dental office i...",2015-04-25 04:18:09,1,1
88459,F,1,1,4,2,2015-02-01,2015-02-11 11:36:49,9,2015-02-11 12:30:08,0000-00-00 00:00:00,1072-09-30,88051,I'm emotionally exhausted and beat down. My h...,2015-02-01 12:21:11,1,2
168911,M,9,1,1,0,2015-03-05,2015-03-05 21:30:29,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1078-01-31,1000763,Well...many decades online and this is my firs...,2015-03-05 22:12:18,0,0
261240,F,3,1,1,0,2013-10-31,2015-06-13 08:32:29,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1078-05-31,401848,I believe in marriage and would like to get ma...,2015-04-10 20:03:45,0,1
292181,F,9,1,2,0,2015-04-22,2015-04-22 11:26:11,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1085-04-30,157917,hubby likes to share me and watch me being fil...,2015-04-22 11:36:03,2,2
416030,M,14,1,2,0,2015-05-13,2015-06-03 19:54:54,8,0000-00-00 00:00:00,0000-00-00 00:00:00,1101-05-31,233,I wish I had a girlfriend that is between 14 a...,2015-06-03 16:51:20,0,2
152443,M,10,1,1,1,2015-02-27,2015-02-27 18:02:33,2,0000-00-00 00:00:00,0000-00-00 00:00:00,1102-11-30,998455,"I just found out that I had synesthesia today,...",2015-02-27 18:17:24,0,0
300813,NaN,1,1,1,0,2015-04-25,2015-04-25 18:16:24,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-06-30,1020143,"Love Rick Riordans ""Heroes of Olympus"" series....",2015-04-25 18:19:29,0,0
160029,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"Collapsing in on my self, I watch as the world...",2015-03-02 13:32:10,2,2
156498,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"Day after day, I wonder will I ever go out the...",2015-03-01 06:42:07,1,1
157677,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"Often I can't sleep for days, and everything s...",2015-03-01 15:57:26,2,1
165542,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,"When the moment arrives, the one that you real...",2015-03-04 16:27:55,1,2
173023,F,11,5,3,2,2015-03-01,2015-04-15 05:41:37,29,0000-00-00 00:00:00,0000-00-00 00:00:00,1111-11-30,7555,To all the people who suffer for a wide and va...,2015-03-07 14:28:30,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491041,M,729,5,47,13,2015-06-27,2015-06-30 22:13:14,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,983984,me too.... wish I could do it again.,2015-06-27 15:55:43,0,0
532011,M,8,1,4,2,2015-07-08,2015-07-09 13:08:28,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,117528,Hi I made this account yesterday night so I th...,2015-07-09 11:57:13,0,1
531300,M,8,1,2,0,2015-07-09,2015-07-09 17:22:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,692409,"hey,im new here and was just hoping to meet ne...",2015-07-09 06:41:18,3,1
462509,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,294022,"When I look in the mirror, I see a girl nor bo...",2015-06-18 17:46:11,4,3
513495,M,262,9,15,15,2015-01-15,2015-07-09 19:35:48,11,0000-00-00 00:00:00,2015-01-17 17:01:15,2002-06-30,5029,I like CATS :)<br />\nreply if you do too,2015-07-04 03:26:13,1,1
482981,F,108,8,9,7,2015-06-18,2015-07-06 02:44:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,937157,jongkey64 is me OK No one over 17 plz I'M only 13,2015-06-25 00:13:29,0,0
461287,F,108,8,9,7,2015-06-18,2015-07-06 02:44:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,552602,when I'M bored and need Someone room talk to a...,2015-06-18 08:57:20,0,1
518024,F,108,8,9,7,2015-06-18,2015-07-06 02:44:50,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,937157,jongkey64 is me I don't talk to anyone over 17...,2015-07-05 14:25:13,0,1
502411,M,9,1,1,0,2015-06-30,2015-07-05 23:04:40,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,2805,I love being gemini but has anybody ever felt ...,2015-06-30 23:14:19,4,3
441074,F,9,12,37,2,2015-06-10,2015-07-10 01:32:40,4,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,364243,I can't wait until my step brothers go back to...,2015-06-11 21:43:33,0,1
475295,F,34,1,2,0,2015-06-22,2015-06-23 22:06:01,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,155309,I'm a therian from Land O' Lakes who is going ...,2015-06-22 16:21:07,0,0
493401,M,729,5,47,13,2015-06-27,2015-06-30 22:13:14,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,444604,so! I didn't mind. found more love from a man ...,2015-06-28 09:54:51,4,2
460882,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,400064,Ha! I started playing when I was 3. Still love...,2015-06-18 04:45:23,6,1
460863,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,222272,I like Asians because most of them are brought...,2015-06-18 04:35:28,7,0
447654,F,9,12,37,2,2015-06-10,2015-07-10 01:32:40,4,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,5043,This is what I drink when my parents aren't home,2015-06-14 02:13:58,0,1
453174,M,124,8,107,105,2015-06-15,2015-07-09 16:37:15,72,0000-00-00 00:00:00,2015-06-22 11:50:07,2002-06-30,117528,Well just joined and looking for friends,2015-06-15 20:28:03,1,1
529279,M,262,9,15,15,2015-01-15,2015-07-09 19:35:48,11,0000-00-00 00:00:00,2015-01-17 17:01:15,2002-06-30,276385,it tastes good so why not? it solves my proble...,2015-07-08 17:32:07,2,0
460859,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,64567,I couldn't give a poo about what people think ...,2015-06-18 04:33:45,10,0
447525,F,9,12,37,2,2015-06-10,2015-07-10 01:32:40,4,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,24933,Should I get a permanent tattoo,2015-06-14 01:24:22,0,3
435945,F,9,1,6,0,2015-06-10,2015-06-10 06:51:21,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,1035069,Will I be able to find the guy that is right f...,2015-06-10 06:58:54,0,0
529797,M,10,2,8,1,2015-07-08,2015-07-09 20:44:46,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,205860,I have been told I look more like 10-12. I rec...,2015-07-08 20:33:42,5,4
460852,F,49,8,17,0,2015-06-17,2015-07-08 00:50:21,16,2015-06-18 17:03:58,2015-06-17 02:14:22,2002-06-30,166260,I always had a need to make a mark of importan...,2015-06-18 04:29:23,1,2
529274,M,262,9,15,15,2015-01-15,2015-07-09 19:35:48,11,0000-00-00 00:00:00,2015-01-17 17:01:15,2002-06-30,85983,have papa John's pizza with extra human I mean...,2015-07-08 17:29:21,0,0
437039,F,125,2,5,3,2015-06-10,2015-07-07 21:28:47,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,376866,Found one in my front yard,2015-06-10 15:09:00,0,0
499386,F,104,4,7,2,2015-06-30,2015-07-09 05:34:24,1,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-06-30,665290,I am absolutely in love with Mello from Death ...,2015-06-30 01:25:31,2,4
503362,F,34,3,22,0,2015-06-15,2015-07-10 00:56:24,23,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-07-31,530949,I am very shy and I am very busty for my age,2015-07-01 07:05:09,2,1
471271,F,34,3,22,0,2015-06-15,2015-07-10 00:56:24,23,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-07-31,1030263,My neighbors saw everything... What happened b...,2015-06-21 12:11:15,3,4
510400,F,34,3,22,0,2015-06-15,2015-07-10 00:56:24,23,0000-00-00 00:00:00,0000-00-00 00:00:00,2002-07-31,2499,I don't like how big my boobs are especially f...,2015-07-03 07:03:10,1,2
57531,F,1,7,2,0,2007-03-19,2015-01-21 14:28:38,23,0000-00-00 00:00:00,2011-02-17 19:36:09,NaN,36135,I realize I have a problem.<br />\n<br />\nAnd...,2015-01-20 13:05:34,0,2
83809,NaN,10,6,1,0,2008-01-17,2015-02-10 10:48:02,105,2008-01-18 19:24:24,0000-00-00 00:00:00,NaN,293219,"I do too, but it ddrives me crazy when a child...",2015-01-30 14:12:47,0,0

In [20]:
EPBirthdateSorted.iloc[50000:50050,:]

,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,num_logins,last_wall_activity,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments
389555,M,104,26,15,6,2014-03-10,2015-07-09 22:59:43,2541,2015-04-27 00:49:25,2015-07-08 12:08:41,1966-11-30,152989,EP<br />\nI said I was leaving. That's easier ...,2015-05-26 13:52:20,2,2
219454,F,9,1,1,1,2015-03-25,2015-03-25 08:46:47,1,0000-00-00 00:00:00,2015-03-25 09:06:05,1966-11-30,1008122,I only have one child and bothme and my husban...,2015-03-25 09:04:12,0,1
76197,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,221424,They say try not to suppress or ignore frustr...,2015-01-27 13:45:05,12,4
317884,NaN,67,9,23,19,2015-03-20,2015-07-09 21:10:02,92,0000-00-00 00:00:00,2015-03-31 16:43:03,1966-11-30,123663,he broke up with almost 2 months ago. I needed...,2015-05-02 06:40:38,3,2
227174,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,814786,Sex to sax ... It is very sensual....<br />\n<...,2015-03-28 12:25:36,7,1
20321,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,853081,What would your wife/husbands story be as oppo...,2015-01-07 08:22:29,7,18
391036,M,0,1,1,1,2015-03-14,2015-03-14 23:54:29,1,0000-00-00 00:00:00,2015-03-14 23:56:21,1966-11-30,154884,Sorry all you guys but i have an addiction. Lo...,2015-03-15 00:05:08,0,0
17412,M,1090,22,25,14,2014-12-17,2015-07-07 05:15:53,137,2015-02-26 06:05:21,2015-03-10 11:10:57,1966-11-30,341509,I love it when people don't know how to have a...,2015-01-06 09:26:10,3,2
412785,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,706483,"You don't bring me flowers.., Barbara Streisa...",2015-06-02 13:32:09,8,3
500929,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,84460,Personal space is required in most relationshi...,2015-06-30 14:15:44,32,14
119710,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,199161,Ellie Goulding... Love Me Like You Do..( from ...,2015-02-14 15:23:02,5,1
361863,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,693033,She said <br />\nI miss<br />\nYour kiss.<br /...,2015-05-17 14:33:26,4,2
306904,F,9,1,1,0,2015-04-27,2015-04-27 21:17:14,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1966-11-30,14065,I left Australia permanently 13 years ago. I h...,2015-04-27 21:55:28,10,3
119684,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,814786,Well I had Sax and Michael Bolton mixed in tog...,2015-02-14 15:13:14,1,0
247218,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,287202,Kenny G with baby face ...Everytime I Close My...,2015-04-05 15:11:54,3,0
137106,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,398828,<img src='http://content-img.experienceproject...,2015-02-21 16:36:55,9,5
336628,M,6,1,1,0,2014-08-19,2015-06-01 12:33:24,9,0000-00-00 00:00:00,0000-00-00 00:00:00,1966-11-30,294723,I'm so sorry you're going through this. I not...,2015-05-08 22:16:29,0,0
20404,M,90,48,189,88,2012-05-11,2015-06-25 07:12:55,358,2013-10-04 06:21:10,2013-11-26 06:47:38,1966-11-30,19015,I AM HIV+ AND I HAVE FOUND LOVE ON EP - UPDATE...,2015-01-07 09:09:47,9,5
20408,M,90,48,189,88,2012-05-11,2015-06-25 07:12:55,358,2013-10-04 06:21:10,2013-11-26 06:47:38,1966-11-30,223368,I AM HIV+ AND I HAVE FOUND LOVE ON EP - UPDATE...,2015-01-07 09:10:50,0,0
20409,M,90,48,189,88,2012-05-11,2015-06-25 07:12:55,358,2013-10-04 06:21:10,2013-11-26 06:47:38,1966-11-30,209761,I AM HIV+ AND I HAVE FOUND LOVE ON EP - UPDATE...,2015-01-07 09:11:46,4,4
10549,M,1090,22,25,14,2014-12-17,2015-07-07 05:15:53,137,2015-02-26 06:05:21,2015-03-10 11:10:57,1966-11-30,612320,You get a text and feel really good to hear fr...,2015-01-04 08:15:27,3,0
20433,M,47,39,49,47,2014-07-28,2015-07-09 22:49:24,320,2015-05-26 07:04:49,2015-05-14 13:37:41,1966-11-30,975957,"<iframe title=""YouTube video player"" class=""yo...",2015-01-07 09:28:22,0,1
263474,M,104,26,15,6,2014-03-10,2015-07-09 22:59:43,2541,2015-04-27 00:49:25,2015-07-08 12:08:41,1966-11-30,1014537,"OK, here's the deal. I've had two bad experie...",2015-04-11 16:06:39,0,0
358099,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,2422,Im now in Uniqlo joining my son to buy new stu...,2015-05-16 07:26:01,1,1
109423,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,42407,I have needed to be quiet and chilled out and ...,2015-02-10 09:06:38,4,1
352602,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,8721,Saw an old woman with loads of old stuff i got...,2015-05-14 09:05:18,8,5
106756,F,45,19,65,27,2015-01-23,2015-07-09 19:19:40,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1966-11-30,2510,First day back at work since DDay. Do I contin...,2015-02-09 06:02:32,3,2
503608,NaN,67,9,23,19,2015-03-20,2015-07-09 21:10:02,92,0000-00-00 00:00:00,2015-03-31 16:43:03,1966-11-30,25670,today I miss you. I know I've spoken to you bu...,2015-07-01 08:58:52,6,2
278736,M,104,26,15,6,2014-03-10,2015-07-09 22:59:43,2541,2015-04-27 00:49:25,2015-07-08 12:08:41,1966-11-30,1016911,Thanks to everyone. I wish you all well,2015-04-17 12:00:51,0,0
86677,M,1090,22,25,14,2014-12-17,2015-07-07 05:15:53,137,2015-02-26 06:05:21,2015-03-10 11:10:57,1966-11-30,364243,Finding someone to tell anything to seems to b...,2015-01-31 18:39:32,7,1
119526,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,237070,I love cranking up to Bill Withers.. lovely Da...,2015-02-14 13:38:44,7,8
189940,M,9,3,7,6,2015-02-12,2015-05-22 18:04:26,79,2015-02-15 19:46:08,2015-02-14 15:43:47,1966-11-30,829312,'Your Dad...'<br />\n'STOP!'<br />\n<br />\nth...,2015-03-13 23:10:18,0,0
80276,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,262523,You have something I need ...Ben Haenow<br />\...,2015-01-29 04:35:09,2,1
10926,M,47,39,49,47,2014-07-28,2015-07-09 22:49:24,320,2015-05-26 07:04:49,2015-05-14 13:37:41,1966-11-30,309783,I ain't got no money<br />\nI ain't like those...,2015-01-04 11:09:55,6,2
401001,M,47,39,49,47,2014-07-28,2015-07-09 22:49:24,320,2015-05-26 07:04:49,2015-05-14 13:37:41,1966-11-30,327938,"Yeah, oh yeah<br />\nAlright, oh, oh, oh<br />...",2015-05-29 13:34:03,2,2
360529,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,2013,I hate it when Starbucks serve me not too hot ...,2015-05-17 01:57:11,4,2
322169,NaN,67,9,23,19,2015-03-20,2015-07-09 21:10:02,92,0000-00-00 00:00:00,2015-03-31 16:43:03,1966-11-30,123663,so we have been done for 6 weeks. have talked ...,2015-05-03 19:29:32,3,3
318670,M,46,40,18,8,2013-07-29,2015-07-10 01:24:32,2023,2015-05-08 01:56:44,2015-07-02 01:35:34,1966-11-30,950,If we can get enough atheists to speak out aga...,2015-05-02 13:53:57,5,3
14664,F,2,2,4,2,2014-07-20,2015-01-05 13:33:32,3,0000-00-00 00:00:00,0000-00-00 00:00:00,1966-11-30,1649,I was with this man for a little over a year. ...,2015-01-05 13:43:04,1,1
341422,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,1025102,So it's not been too long in discovering I pac...,2015-05-10 16:08:32,5,3
348064,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,468959,I just do.... So sad I got to leave you behind...,2015-05-12 19:26:21,11,5
332717,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,285,Second meet ...location somewhere in America!!...,2015-05-07 14:37:34,15,12
357994,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,8721,Shared small amounts to 2 hardworking ladies i...,2015-05-16 06:07:13,4,0
442968,F,713,97,890,67,2014-01-03,2015-07-09 17:26:05,1913,2015-07-01 12:59:29,2015-07-09 14:45:22,1966-11-30,278319,Yes I enjoying taking photos .. The odd selfie...,2015-06-12 13:38:15,19,8
357986,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,8466,Does not want much number of friends what i wa...,2015-05-16 06:03:51,5,0
263532,M,104,26,15,6,2014-03-10,2015-07-09 22:59:43,2541,2015-04-27 00:49:25,2015-07-08 12:08:41,1966-11-30,1014546,It's a long story. I was crossdressing as a li...,2015-04-11 16:25:23,1,1
109561,F,45,19,65,27,2015-01-23,2015-07-09 19:19:40,1,0000-00-00 00:00:00,0000-00-00 00:00:00,1966-11-30,2510,Well after 11 days of nc I broke down. I can't...,2015-02-10 10:38:20,3,1
357984,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,148586,"Poached egg, beef tapa and garlic fried rice i...",2015-05-16 06:02:13,5,4
352782,F,23,11,3,1,2015-05-12,2015-05-21 23:53:10,5,0000-00-00 00:00:00,2015-05-13 06:44:48,1966-11-30,70647,My pet Yogi started sleeping in our bedroom,2015-05-14 10:40:17,5,2
177541,M,19,34,6,5,2014-06-29,2015-06-29 07:28:01,35,2014-08-28 01:36:29,2014-08-11 18:06:11,1966-11-30,233190,one that shows how love can be and should be. ...,2015-03-09 03:26:13,2,1

In [21]:
tempData = EPData[EPData['birthdate']=='1966-11-30']
tempData[['created','gender']]

           created gender
7297    2014-12-17      M
7368    2014-12-17      M
10549   2014-12-17      M
10926   2014-07-28      M
11859   2014-01-03      F
11897   2014-12-17      M
11973   2014-12-17      M
12132   2014-12-17      M
12336   2014-12-17      M
13736   2014-12-17      M
14605   2014-12-17      M
14664   2014-07-20      F
17412   2014-12-17      M
17591   2014-12-17      M
18145   2014-07-28      M
19786   2014-12-28      M
20183   2014-12-17      M
20244   2014-07-28      M
20321   2014-01-03      F
20404   2012-05-11      M
20408   2012-05-11      M
20409   2012-05-11      M
20433   2014-07-28      M
31582   2014-12-28      M
41807   2014-12-17      M
43077   2014-12-17      M
46310   2014-07-28      M
51247   2014-07-28      M
62034   2014-07-28      M
62349   2014-01-03      F
...            ...    ...
460736  2015-06-08      F
472449  2015-02-03      F
472453  2015-02-03      F
472461  2015-02-03      F
472463  2015-02-03      F
472482  2015-02-03      F
472499  2015-02-03      F
472527  2015-02-03      F
475079  2014-07-28      M
475091  2014-07-28      M
477059  2014-01-03      F
477575  2014-07-28      M
481343  2014-01-03      F
487812  2014-03-10      M
488500  2014-12-08      M
494799  2015-06-28      F
496463  2014-01-03      F
500521  2014-01-03      F
500621  2014-01-03      F
500929  2014-01-03      F
501546  2015-06-28      F
503608  2015-03-20    NaN
507659  2014-01-03      F
512052  2015-06-28      F
512100  2015-07-03      F
514576  2014-01-03      F
519857  2014-01-03      F
520442  2015-03-20    NaN
522731  2014-10-13      M
528220  2014-01-03      F

[243 rows x 2 columns]

In [83]:
import sys
def makeUserGroupDict(data, uidCol, gidCol):
    print "starting function"
    sys.stdout.flush()
    data = data.sort(columns='uid')
    print "Finished sorting!"
    sys.stdout.flush()
    userDict = {}
    dictUID = data.iloc[0,uidCol]
    userDict[dictUID] = {}
    print "Starting to fill dict"
    sys.stdout.flush()
    for irow in range(0,data.shape[0]):
        if irow%100 == 0:
            print "Row number is ", irow, " of ", data.shape[0]
            sys.stdout.flush()
        currentUID = data.iloc[irow,uidCol]
        if dictUID != currentUID:
            dictUID = currentUID
            userDict[dictUID] = {}
        gid = data.iloc[irow,gidCol]
        if gid in userDict[dictUID]:
            userDict[dictUID][gid] += 1
        else:
            userDict[dictUID][gid] = 1
            
    return userDict

In [23]:
goodData = dataWithUserIDs[~(dataWithUserIDs['uid']==0)]
goodData

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
0,0,0,0,F,210,54,25,2,2014-12-20,2015-04-03 12:45:01,...,0000-00-00 00:00:00,1997-03-31,124249,I just want my mom to hug me and say that she ...,2015-01-01 00:00:10,0,0,18,9343578,False
1,1,1,1,F,25,9,2,0,2014-08-28,2015-04-15 22:32:36,...,0000-00-00 00:00:00,1994-03-31,5276,I don't know why this is happening right now. ...,2015-01-01 00:00:46,0,0,21,8866629,False
2,2,3,3,M,153,2,6,5,2014-12-13,2015-06-01 20:34:52,...,2014-12-13 08:37:11,1993-11-30,58852,HAPPY NEW YEARS !!!!!!!!!!!!!!! !!!!!!!!!...,2015-01-01 00:02:39,1,2,21,9318824,False
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
7,7,8,8,M,250,255,1,0,2014-11-29,2015-03-25 09:23:41,...,0000-00-00 00:00:00,1982-11-30,962002,"Be of good character, should have an eighth gr...",2015-01-01 00:06:00,0,1,32,9270416,False
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
16,16,17,17,M,401,429,1,0,2014-11-29,2015-04-02 03:17:34,...,0000-00-00 00:00:00,1982-11-30,957283,By far the most economical home heating proced...,2015-01-01 00:10:14,0,1,32,9270002,False
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
18,18,19,19,M,426,458,2,0,2014-11-27,2015-03-23 22:36:26,...,0000-00-00 00:00:00,1982-11-30,957417,Although the price of propane does rise and tu...,2015-01-01 00:10:23,0,1,32,9263763,False
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
28,28,29,29,M,7,1,1,0,2014-12-31,2015-01-01 12:19:54,...,0000-00-00 00:00:00,1974-04-30,972255,Ok here is some background. When I was a kid I...,2015-01-01 00:14:17,0,0,41,9383083,False
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99969,99969,105764,105764,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,368260,I know im part wolf...I've known since 3rd gra...,2015-02-08 19:55:07,1,4,14,9520293,True
99970,99970,105765,105765,M,57,13,13,13,2015-02-07,2015-04-03 17:16:36,...,0000-00-00 00:00:00,1999-02-28,526490,ITS ABOUT TO BEGIN <br />\nIM TOO EXCITED,2015-02-08 19:56:00,4,2,16,9515708,True
99971,99971,105766,105766,M,357,72,347,260,2014-03-04,2015-07-09 20:23:50,...,2015-01-22 23:54:23,1998-07-31,926420,"If I told you I've never been kissed, would yo...",2015-02-08 19:56:55,2,2,16,7975284,True
99972,99972,105767,105767,F,17,8,22,8,2015-01-28,2015-02-09 10:35:03,...,0000-00-00 00:00:00,1997-05-31,80727,YES I WILL BE 18 WITH 2 KIDS. <br />\nI AM NOT...,2015-02-08 19:57:06,2,3,18,9481709,False
99973,99973,105768,105768,M,29,8,16,8,2015-01-24,2015-07-09 23:30:08,...,2015-03-11 18:55:52,1998-01-31,532453,My parents will never make me fat,2015-02-08 19:57:49,1,2,17,9468107,False
99974,99974,105769,105769,F,16,11,4,3,2014-11-17,2015-07-04 10:13:58,...,2015-03-22 19:57:20,1975-03-31,990553,Even though I'm clearly gay I still get approa...,2015-02-08 19:58:45,0,0,40,9226696,True
99975,99975,105770,105770,M,847,294,244,63,2013-06-03,2015-07-09 23:12:02,...,2015-07-01 16:06:23,1973-03-31,332,<b> Then and Now â€¦</b><br />\n<br />\nReflec...,2015-02-08 19:58:49,23,8,42,6418405,True
99976,99976,105771,105771,F,107,52,164,41,2011-10-18,2015-06-02 08:06:38,...,2014-01-15 11:53:11,1991-10-31,301,"I was dreaming I was on a pathway, looking dow...",2015-02-08 19:59:11,0,3,23,4314790,True
99977,99977,105772,105772,M,700,53,35,1,2014-07-06,2015-07-09 22:32:46,...,0000-00-00 00:00:00,2000-03-31,370,"And yet again I'm in the bathroom, on the floo...",2015-02-08 20:00:04,2,1,15,8552640,True
99979,99979,105774,105774,F,605,88,327,72,2011-05-10,2015-07-10 00:29:54,...,2014-03-14 03:23:19,1997-03-07,9644,The MTA just loves prices hikes so much that t...,2015-02-08 20:01:31,0,0,18,3823094,True
99980,99980,105775,105775,F,1259,416,361,11,2014-11-16,2015-07-09 22:17:06,...,2015-05-30 00:43:51,1983-09-30,157654,When I realized I'm finally tired of seeing pe...,2015-02-08 20:01:36,1,1,31,9221295,False
99981,99981,105776,105776,T,371,671,194,12,2014-06-16,2015-07-06 14:09:22,...,0000-00-00 00:00:00,1995-10-31,1431,It's impossible for me to listen to this song ...,2015-02-08 20:01:52,1,0,19,8436456,True
99982,99982,105777,105777,M,29145,10881,1908,1892,2012-05-08,2015-07-09 20:44:29,...,2015-07-08 21:34:40,1954-12-31,160523,â€œConstant kindness can accomplish much. As t...,2015-02-08 20:02:24,3,1,60,4982507,True
99983,99983,105778,105778,M,16,168,212,12,2012-06-12,2015-07-09 18:22:22,...,2015-07-09 16:44:58,1953-08-31,1009,A man walks into his bedroom and sees his wife...,2015-02-08 20:02:38,13,8,61,5100778,True
99984,99984,105779,105779,M,11,1,2,0,2015-02-08,2015-02-18 10:37:42,...,0000-00-00 00:00:00,1976-12-31,990554,"I've been married for over 3yrs, together for ...",2015-02-08 20:02:43,1,0,38,9520256,False
99985,99985,105780,105780,F,234,18,86,9,2013-06-01,2015-06-26 15:00:44,...,2015-02-08 14:07:08,1994-05-31,966492,It actually takes a lot of gumption to train a...,2015-02-08 20:02:59,0,1,21,6409573,True
99986,99986,105781,105781,F,571,81,252,42,2015-01-29,2015-07-09 18:33:28,...,2015-07-09 17:44:09,1975-09-30,265395,I feel like it's getting worse :( ......stupid...,2015-02-08 20:04:22,0,0,39,9484984,True
99987,99987,105782,105782,F,66,24,6,0,2011-08-11,2015-03-17 01:26:00,...,2012-02-27 07:23:48,1997-03-07,183,I was 17 years old when my dad passed away. I ...,2015-02-08 20:04:44,1,0,18,4114668,False
99988,99988,105783,105783,F,175,17,8,0,2014-12-17,2015-07-09 17:29:29,...,0000-00-00 00:00:00,1996-07-31,578568,My cover is very rough and appears to be care-...,2015-02-08 20:04:56,3,2,18,9334674,True
99989,99989,105784,105784,F,156,137,208,34,2014-12-31,2015-07-03 17:53:18,...,2015-03-27 23:19:54,1994-08-31,2923,"Okay, so me and my boyfriend saw this place wi...",2015-02-08 20:05:46,0,0,20,9380300,True
99990,99990,105786,105786,F,52,8,9,5,2011-02-02,2015-04-29 04:21:01,...,0000-00-00 00:00:00,1997-03-07,709324,"Self explanatory, given my meds aren't doing a...",2015-02-08 20:07:21,0,0,18,3472819,False
99991,99991,105787,105787,F,605,523,11,10,2013-12-27,2015-07-09 20:37:58,...,2015-07-09 15:50:31,1971-09-30,417107,I do...<br />\n<br />\nBut I don't accept your...,2015-02-08 20:07:48,2,1,43,7645822,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99993,99993,105789,105789,M,226,173,82,4,2013-05-20,2015-07-10 00:12:13,...,2015-01-07 03:23:02,1995-10-31,47240,They don't respond when I text them. I just ha...,2015-02-08 20:08:30,3,1,19,6369871,True
99994,99994,105790,105790,F,196,70,177,75,2012-05-28,2015-07-09 23:31:17,...,2014-06-18 12:59:05,1995-11-30,48401,I love to talk. I want someone I can talk to l...,2015-02-08 20:08:44,2,1,19,5050032,True
99995,99995,105791,105791,U,5691,1251,141,24,2011-01-24,2015-07-08 07:00:53,...,2014-11-27 21:55:28,1969-09-30,387568,http://thenarcissisticlife.com/do-i-have-a-nar...,2015-02-08 20:10:39,4,2,45,3443350,True
99996,99996,105792,105792,M,52,46,87,5,2014-01-24,2015-07-09 10:39:54,...,0000-00-00 00:00:00,2000-07-31,5577,I have a pretty long story about it in the com...,2015-02-08 20:10:44,2,1,14,7783433,True
99997,99997,105793,105793,F,1713,91,300,181,2013-12-21,2015-07-09 15:28:47,...,2015-05-25 22:47:23,2000-05-31,163874,I as upset one day and i walked past a lady an...,2015-02-08 20:12:43,5,0,15,7620182,True
99998,99998,105794,105794,M,21,324,134,73,2013-12-19,2015-07-09 19:31:40,...,2015-07-06 21:28:07,1964-01-31,133597,Don't quite know how to express my enjoyment t...,2015-02-08 20:12:56,7,1,51,7609350,True
99999,99999,105795,105795,F,72,26,52,29,2014-02-02,2015-06-23 06:09:15,...,2015-06-23 06:54:02,1979-11-30,7465,"All of my life, I have always known there woul...",2015-02-08 20:14:34,0,0,35,7826707,True

In [24]:
goodData = goodData[goodData['certainty']==True]
goodData

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
30,30,31,31,M,239,61,49,48,2013-07-17,2015-07-09 14:35:49,...,2015-01-02 21:49:33,1959-06-30,972256,I hope it's a good year for everyone,2015-01-01 00:14:46,1,1,56,6609242,True
31,31,32,32,M,171,100,81,53,2014-12-22,2015-07-10 00:32:09,...,0000-00-00 00:00:00,1995-11-30,2389,My new years resolution is to quit my nasty ch...,2015-01-01 00:14:59,0,1,19,9351351,True
32,32,33,33,F,75,9,11,2,2014-12-24,2015-01-07 06:24:26,...,0000-00-00 00:00:00,1983-10-31,117528,EP is a cesspool of depravity and a killground...,2015-01-01 00:15:02,12,17,31,9357495,True
33,33,34,34,U,215,104,67,56,2014-11-17,2015-07-09 21:41:57,...,2015-06-30 22:03:52,1968-04-30,160526,Let's face it<br />\n A pretty face and sexy b...,2015-01-01 00:15:30,2,1,47,9226988,True
35,35,36,36,M,72,92,49,21,2009-10-10,2015-05-31 23:44:23,...,2015-01-03 05:23:40,1977-10-31,8436,Tonight I made Kung Pao chicken<br />\n<br />\...,2015-01-01 00:16:31,5,1,37,2050477,True
36,36,37,37,M,46,43,52,33,2014-09-03,2015-05-09 19:57:03,...,2014-12-29 00:05:00,1997-12-31,1340,It's about an hour and a half away from the Ne...,2015-01-01 00:16:56,4,0,17,8905023,True
38,38,39,39,M,446,23,39,20,2013-08-09,2015-04-27 21:06:05,...,2014-07-27 20:53:29,1978-07-31,640484,Maybe she'll think my eyes are red because I'm...,2015-01-01 00:17:25,0,0,36,6769181,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99963,99963,105758,105758,F,155,84,33,0,2015-01-29,2015-02-21 06:13:36,...,0000-00-00 00:00:00,1982-01-31,31916,i am survivor of sexually abused<br />\nby my ...,2015-02-08 19:51:39,1,0,33,9483556,True
99964,99964,105759,105759,F,675,48,96,1,2015-01-11,2015-07-09 22:35:08,...,2015-07-08 19:51:43,1997-05-31,55518,Ive made homemade mac & cheese two nights in a...,2015-02-08 19:51:58,1,0,18,9422865,True
99965,99965,105760,105760,M,86,13,5,3,2015-01-19,2015-03-06 23:39:16,...,0000-00-00 00:00:00,1962-10-31,62225,i havent played a video game in years but i us...,2015-02-08 19:52:12,0,0,52,9452878,True
99966,99966,105761,105761,M,64,25,29,24,2014-09-22,2015-07-09 20:16:36,...,2015-07-09 16:44:24,1999-06-30,990552,I want a chub to smother me with his fat,2015-02-08 19:52:56,2,1,16,8997675,True
99967,99967,105762,105762,U,31,9,15,7,2013-04-01,2015-06-25 19:46:49,...,2015-06-12 14:35:55,1994-09-30,45404,Pokemon is awesome. I grew up watching the ori...,2015-02-08 19:54:20,8,5,20,6192070,True
99968,99968,105763,105763,F,605,88,327,72,2011-05-10,2015-07-10 00:29:54,...,2014-03-14 03:23:19,1997-03-07,378558,I have friends and people say I'm cute but at ...,2015-02-08 19:55:05,2,1,18,3823094,True
99969,99969,105764,105764,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,368260,I know im part wolf...I've known since 3rd gra...,2015-02-08 19:55:07,1,4,14,9520293,True
99970,99970,105765,105765,M,57,13,13,13,2015-02-07,2015-04-03 17:16:36,...,0000-00-00 00:00:00,1999-02-28,526490,ITS ABOUT TO BEGIN <br />\nIM TOO EXCITED,2015-02-08 19:56:00,4,2,16,9515708,True
99971,99971,105766,105766,M,357,72,347,260,2014-03-04,2015-07-09 20:23:50,...,2015-01-22 23:54:23,1998-07-31,926420,"If I told you I've never been kissed, would yo...",2015-02-08 19:56:55,2,2,16,7975284,True
99974,99974,105769,105769,F,16,11,4,3,2014-11-17,2015-07-04 10:13:58,...,2015-03-22 19:57:20,1975-03-31,990553,Even though I'm clearly gay I still get approa...,2015-02-08 19:58:45,0,0,40,9226696,True
99975,99975,105770,105770,M,847,294,244,63,2013-06-03,2015-07-09 23:12:02,...,2015-07-01 16:06:23,1973-03-31,332,<b> Then and Now â€¦</b><br />\n<br />\nReflec...,2015-02-08 19:58:49,23,8,42,6418405,True
99976,99976,105771,105771,F,107,52,164,41,2011-10-18,2015-06-02 08:06:38,...,2014-01-15 11:53:11,1991-10-31,301,"I was dreaming I was on a pathway, looking dow...",2015-02-08 19:59:11,0,3,23,4314790,True
99977,99977,105772,105772,M,700,53,35,1,2014-07-06,2015-07-09 22:32:46,...,0000-00-00 00:00:00,2000-03-31,370,"And yet again I'm in the bathroom, on the floo...",2015-02-08 20:00:04,2,1,15,8552640,True
99979,99979,105774,105774,F,605,88,327,72,2011-05-10,2015-07-10 00:29:54,...,2014-03-14 03:23:19,1997-03-07,9644,The MTA just loves prices hikes so much that t...,2015-02-08 20:01:31,0,0,18,3823094,True
99981,99981,105776,105776,T,371,671,194,12,2014-06-16,2015-07-06 14:09:22,...,0000-00-00 00:00:00,1995-10-31,1431,It's impossible for me to listen to this song ...,2015-02-08 20:01:52,1,0,19,8436456,True
99982,99982,105777,105777,M,29145,10881,1908,1892,2012-05-08,2015-07-09 20:44:29,...,2015-07-08 21:34:40,1954-12-31,160523,â€œConstant kindness can accomplish much. As t...,2015-02-08 20:02:24,3,1,60,4982507,True
99983,99983,105778,105778,M,16,168,212,12,2012-06-12,2015-07-09 18:22:22,...,2015-07-09 16:44:58,1953-08-31,1009,A man walks into his bedroom and sees his wife...,2015-02-08 20:02:38,13,8,61,5100778,True
99985,99985,105780,105780,F,234,18,86,9,2013-06-01,2015-06-26 15:00:44,...,2015-02-08 14:07:08,1994-05-31,966492,It actually takes a lot of gumption to train a...,2015-02-08 20:02:59,0,1,21,6409573,True
99986,99986,105781,105781,F,571,81,252,42,2015-01-29,2015-07-09 18:33:28,...,2015-07-09 17:44:09,1975-09-30,265395,I feel like it's getting worse :( ......stupid...,2015-02-08 20:04:22,0,0,39,9484984,True
99988,99988,105783,105783,F,175,17,8,0,2014-12-17,2015-07-09 17:29:29,...,0000-00-00 00:00:00,1996-07-31,578568,My cover is very rough and appears to be care-...,2015-02-08 20:04:56,3,2,18,9334674,True
99989,99989,105784,105784,F,156,137,208,34,2014-12-31,2015-07-03 17:53:18,...,2015-03-27 23:19:54,1994-08-31,2923,"Okay, so me and my boyfriend saw this place wi...",2015-02-08 20:05:46,0,0,20,9380300,True
99991,99991,105787,105787,F,605,523,11,10,2013-12-27,2015-07-09 20:37:58,...,2015-07-09 15:50:31,1971-09-30,417107,I do...<br />\n<br />\nBut I don't accept your...,2015-02-08 20:07:48,2,1,43,7645822,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99993,99993,105789,105789,M,226,173,82,4,2013-05-20,2015-07-10 00:12:13,...,2015-01-07 03:23:02,1995-10-31,47240,They don't respond when I text them. I just ha...,2015-02-08 20:08:30,3,1,19,6369871,True
99994,99994,105790,105790,F,196,70,177,75,2012-05-28,2015-07-09 23:31:17,...,2014-06-18 12:59:05,1995-11-30,48401,I love to talk. I want someone I can talk to l...,2015-02-08 20:08:44,2,1,19,5050032,True
99995,99995,105791,105791,U,5691,1251,141,24,2011-01-24,2015-07-08 07:00:53,...,2014-11-27 21:55:28,1969-09-30,387568,http://thenarcissisticlife.com/do-i-have-a-nar...,2015-02-08 20:10:39,4,2,45,3443350,True
99996,99996,105792,105792,M,52,46,87,5,2014-01-24,2015-07-09 10:39:54,...,0000-00-00 00:00:00,2000-07-31,5577,I have a pretty long story about it in the com...,2015-02-08 20:10:44,2,1,14,7783433,True
99997,99997,105793,105793,F,1713,91,300,181,2013-12-21,2015-07-09 15:28:47,...,2015-05-25 22:47:23,2000-05-31,163874,I as upset one day and i walked past a lady an...,2015-02-08 20:12:43,5,0,15,7620182,True
99998,99998,105794,105794,M,21,324,134,73,2013-12-19,2015-07-09 19:31:40,...,2015-07-06 21:28:07,1964-01-31,133597,Don't quite know how to express my enjoyment t...,2015-02-08 20:12:56,7,1,51,7609350,True
99999,99999,105795,105795,F,72,26,52,29,2014-02-02,2015-06-23 06:09:15,...,2015-06-23 06:54:02,1979-11-30,7465,"All of my life, I have always known there woul...",2015-02-08 20:14:34,0,0,35,7826707,True

In [25]:
goodDataSorted = goodData.sort(columns='uid')
goodDataSorted

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
69383,69383,73372,73372,F,1412,733,1561,338,2006-08-28,2015-07-08 14:26:11,...,2015-07-01 16:50:09,1979-03-12,13512,It might take Face powder to catch a man... bu...,2015-01-26 12:45:51,16,5,36,1062,True
50974,50974,53949,53949,F,30,28,88,53,2006-10-11,2015-02-05 22:57:31,...,2013-08-11 13:54:07,1989-03-09,247,Should probably preface this with the note tha...,2015-01-19 05:43:53,3,1,26,2168,True
44768,44768,47303,47303,F,2,3,0,0,2006-11-13,2015-01-16 20:21:56,...,2006-11-13 08:55:18,1989-03-09,181576,I am addicted to psychics and I am going to tr...,2015-01-16 20:24:17,1,1,26,3243,True
22952,22952,24230,24230,F,9,7,14,3,2006-11-27,2015-03-10 16:50:28,...,2011-01-31 23:13:13,1993-03-08,9648,I dreamt that i was having lower abdomen pains...,2015-01-08 16:17:39,1,3,22,6193,True
592,592,611,611,F,249,206,176,158,2007-02-11,2015-06-19 08:37:58,...,2014-10-25 12:15:38,1964-03-15,972333,I have care giver and her and I been together ...,2015-01-01 05:31:03,0,0,51,44448,True
30338,30338,32050,32050,F,25,26,29,7,2007-03-22,2015-07-06 09:25:02,...,2014-01-29 22:36:40,1989-03-09,2510,he said it. he said he loves me. he said we ar...,2015-01-11 11:12:22,18,4,26,47289,True
50084,50084,52991,52991,F,25,26,29,7,2007-03-22,2015-07-06 09:25:02,...,2014-01-29 22:36:40,1989-03-09,2510,what is wrong with me?!! why do I open my big ...,2015-01-18 21:29:12,0,3,26,47289,True
62602,62602,66152,66152,F,25,26,29,7,2007-03-22,2015-07-06 09:25:02,...,2014-01-29 22:36:40,1989-03-09,2510,"so after my word vomit on Sunday, he was dista...",2015-01-23 22:22:45,5,2,26,47289,True
78678,78678,83202,83202,F,59,126,202,108,2007-03-28,2015-05-02 04:04:38,...,2013-01-14 09:53:46,1979-03-12,63676,Science has been given too much credit. It ha...,2015-01-30 08:33:07,4,1,36,47664,True
93054,93054,98464,98464,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,8450,12 Ways You Can Love Yourself Now<br />\nLearn...,2015-02-05 17:03:54,2,1,49,49208,True
93040,93040,98449,98449,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,6156,I have been in recovery now for quite a few 24...,2015-02-05 16:54:40,4,1,49,49208,True
92440,92440,97826,97826,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,310,Outlander by Diana Gabaldon is my all time fav...,2015-02-05 10:37:38,1,2,49,49208,True
94277,94277,99761,99761,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,310,<img src='http://content-img.experienceproject...,2015-02-06 07:16:05,1,1,49,49208,True
94893,94893,100408,100408,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,17806,NOT ALL FEAR IS BAD<br />\nWhen we attain enli...,2015-02-06 14:16:24,0,0,49,49208,True
91420,91420,96711,96711,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,453672,"<iframe title=""YouTube video player"" class=""yo...",2015-02-04 20:56:46,0,1,49,49208,True
94794,94794,100309,100309,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,989529,<img src='http://content-img.experienceproject...,2015-02-06 13:07:39,0,0,49,49208,True
92462,92462,97848,97848,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,9902,I am definitely suffering. Severe depression ...,2015-02-05 10:55:51,2,0,49,49208,True
94760,94760,100275,100275,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,989529,ACCEPTANCE ~ Accepting ~ Accept ~ <br />\nPrac...,2015-02-06 12:44:24,0,0,49,49208,True
91410,91410,96701,96701,F,161,179,161,77,2007-04-12,2015-02-06 12:33:56,...,2014-11-22 09:34:36,1966-02-28,2332,I'd like to share with you a Buddhist meditati...,2015-02-04 20:50:36,5,2,49,49208,True
59611,59611,63003,63003,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,321718,"<iframe title=""YouTube video player"" class=""yo...",2015-01-22 16:41:46,28,22,53,50049,True
62769,62769,66334,66334,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,321718,"<iframe title=""YouTube video player"" class=""yo...",2015-01-23 23:38:09,5,8,53,50049,True
97240,97240,102884,102884,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,989996,As a forward observer with the 1st of the 11th...,2015-02-07 15:55:39,12,13,53,50049,True
38673,38673,40848,40848,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,980251,Alright. I might block me because I am overly ...,2015-01-14 12:37:51,13,11,53,50049,True
25137,25137,26537,26537,M,803,641,1247,1064,2007-04-21,2015-07-09 18:03:55,...,2015-07-08 18:53:46,1961-12-31,976977,Isn't that wonderful? I think something taste...,2015-01-09 12:40:18,18,13,53,50049,True
95070,95070,100601,100601,M,7,3,1,0,2007-05-20,2015-02-25 11:04:18,...,2015-01-29 11:02:16,2001-12-31,522535,Sometimes life sucks. And theres nothing you c...,2015-02-06 16:05:18,0,0,13,53997,True
76395,76395,80803,80803,M,7,3,1,0,2007-05-20,2015-02-25 11:04:18,...,2015-01-29 11:02:16,2001-12-31,397229,I am in 7th grade and in algebra. It is really...,2015-01-29 10:57:29,0,4,13,53997,True
88423,88423,93516,93516,M,7,3,1,0,2007-05-20,2015-02-25 11:04:18,...,2015-01-29 11:02:16,2001-12-31,82621,"Just this christmas i got tickets to see the, ...",2015-02-03 13:24:32,1,0,13,53997,True
54752,54752,57900,57900,F,258,42,480,452,2007-05-21,2015-07-05 12:20:05,...,2015-06-18 09:53:06,1993-03-08,165,I miss being with a woman...not just physicall...,2015-01-20 16:27:31,23,4,22,54180,True
28723,28723,30346,30346,M,23,17,21,18,2007-06-13,2015-07-09 18:32:27,...,2014-01-13 17:00:00,1973-10-31,645,I wish I had higher self esteem and more self ...,2015-01-10 19:55:37,6,4,41,59589,True
48803,48803,51602,51602,F,813,153,387,312,2007-06-29,2015-06-27 17:45:29,...,2015-03-15 19:11:58,1991-11-30,474530,"My relationship with my mom is... problematic,...",2015-01-18 12:19:02,1,0,23,77830,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99675,99675,105453,105453,M,34,1,1,0,2015-02-08,2015-06-11 21:21:21,...,0000-00-00 00:00:00,1995-02-28,1376,any ladies in Chico want a baby?,2015-02-08 16:45:57,0,0,20,9519393,True
99416,99416,105189,105189,F,9,1,1,0,2015-02-08,2015-02-09 11:17:52,...,0000-00-00 00:00:00,1942-09-30,1994,Looking for a correspondance with a mature les...,2015-02-08 14:41:55,0,1,72,9519415,True
99395,99395,105168,105168,M,1,1,1,0,2015-02-08,2015-02-08 14:27:27,...,0000-00-00 00:00:00,1968-04-30,45456,I think Brian Williams will have a difficult t...,2015-02-08 14:35:03,0,2,47,9519429,True
99457,99457,105230,105230,F,141,3,11,6,2015-02-08,2015-02-09 16:14:31,...,0000-00-00 00:00:00,1997-07-31,117528,I just came here to meet new people ya knoww. ...,2015-02-08 15:02:01,2,0,17,9519442,True
99512,99512,105287,105287,F,141,3,11,6,2015-02-08,2015-02-09 16:14:31,...,0000-00-00 00:00:00,1997-07-31,233,Me: My house smells like upsexy <br />\nMe: Wh...,2015-02-08 15:28:56,3,2,17,9519442,True
99479,99479,105253,105253,F,141,3,11,6,2015-02-08,2015-02-09 16:14:31,...,0000-00-00 00:00:00,1997-07-31,646363,Wow. That transformation tho ðŸ˜³,2015-02-08 15:13:24,17,6,17,9519442,True
99465,99465,105238,105238,M,9,1,1,0,2015-02-08,2015-02-18 11:33:39,...,2015-02-18 11:34:45,1976-11-30,91854,I too have SM. At first I was terrified that s...,2015-02-08 15:06:00,0,0,38,9519463,True
99516,99516,105291,105291,M,35,2,2,1,2015-02-08,2015-02-09 23:51:06,...,0000-00-00 00:00:00,1972-06-30,1768,By the trAilor now<br />\nSo I can put you to bed,2015-02-08 15:31:36,0,0,43,9519477,True
99485,99485,105259,105259,M,35,2,2,1,2015-02-08,2015-02-09 23:51:06,...,0000-00-00 00:00:00,1972-06-30,1768,Please kiss you And love in pAssion while we b...,2015-02-08 15:16:52,0,0,43,9519477,True
99511,99511,105286,105286,F,58,4,47,0,2015-02-08,2015-07-08 15:28:02,...,0000-00-00 00:00:00,1993-07-31,556167,Hello talk to me and I been a slave before,2015-02-08 15:28:18,7,7,21,9519593,True
99584,99584,105360,105360,T,40,1,1,0,2015-02-08,2015-02-08 15:51:59,...,0000-00-00 00:00:00,1999-05-31,133398,"I only live with my dad, am a only child, and ...",2015-02-08 16:06:01,0,2,16,9519690,True
99637,99637,105415,105415,F,35,6,51,3,2015-02-08,2015-07-04 12:11:45,...,0000-00-00 00:00:00,1974-06-30,1637,I met my cousin for the first time when I was ...,2015-02-08 16:29:43,7,6,41,9519778,True
99744,99744,105529,105529,M,11,2,2,1,2015-02-08,2015-03-17 01:14:08,...,2015-02-08 18:08:27,1991-04-30,990499,"Hey, I dunno whats up with me, but in all my p...",2015-02-08 17:35:42,0,0,24,9519809,True
99738,99738,105522,105522,T,207,3,13,6,2015-02-08,2015-06-29 22:33:48,...,2015-06-12 23:31:34,1986-05-31,876505,"When I was but just a little boy, I always fel...",2015-02-08 17:28:15,0,1,29,9519883,True
99739,99739,105523,105523,M,22,7,14,13,2015-02-08,2015-07-01 16:05:20,...,2015-02-09 22:41:22,1993-06-30,293509,I know I have somes werewolf abilities grows i...,2015-02-08 17:32:12,0,2,22,9519954,True
99781,99781,105567,105567,F,51,17,67,11,2015-02-08,2015-07-08 19:02:41,...,0000-00-00 00:00:00,1999-07-31,534595,I've only ever been in one relationship with a...,2015-02-08 17:58:22,5,3,15,9519984,True
99766,99766,105551,105551,F,1173,19,54,27,2015-02-08,2015-02-26 18:33:24,...,0000-00-00 00:00:00,1989-12-31,39601,Can't sleep untill 7 am then owersleep almost ...,2015-02-08 17:51:00,2,4,25,9519992,True
99874,99874,105666,105666,F,38,10,2,0,2015-02-08,2015-06-14 17:46:54,...,0000-00-00 00:00:00,1981-12-31,722404,I have a coworker who drags in late because sh...,2015-02-08 18:58:55,2,2,33,9520006,True
99898,99898,105690,105690,M,7,1,1,0,2015-02-08,2015-02-18 23:55:26,...,0000-00-00 00:00:00,1995-10-31,27388,I remember thinking as I held two magnets sout...,2015-02-08 19:10:16,0,0,19,9520125,True
99953,99953,105748,105748,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,86984,Still Miss It Sometimes But I Was Wronged-Dece...,2015-02-08 19:45:50,0,2,45,9520131,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99913,99913,105705,105705,F,6,1,1,0,2015-02-08,2015-03-01 19:13:57,...,0000-00-00 00:00:00,1990-01-31,152979,"After almost 2 years of dating, 1 year being l...",2015-02-08 19:21:55,0,3,25,9520133,True
99845,99845,105635,105635,M,27,1,1,0,2015-02-08,2015-02-08 19:08:25,...,0000-00-00 00:00:00,1955-02-28,990527,<img src='http://content-img.experienceproject...,2015-02-08 18:40:56,0,1,60,9520145,True
99863,99863,105655,105655,F,7,2,1,0,2015-02-08,2015-02-08 18:53:21,...,2015-02-08 18:44:52,1985-12-31,861164,"<iframe title=""YouTube video player"" class=""yo...",2015-02-08 18:52:25,1,0,29,9520173,True
99857,99857,105649,105649,F,7,2,1,0,2015-02-08,2015-02-08 18:53:21,...,2015-02-08 18:44:52,1985-12-31,89265,i had a myelogram in november 2014. when i cam...,2015-02-08 18:49:14,0,1,29,9520173,True
99922,99922,105714,105714,F,134,2,4,0,2015-02-08,2015-02-13 19:39:46,...,0000-00-00 00:00:00,1989-02-28,7258,I've recently discovered that I have had PTSD ...,2015-02-08 19:34:27,1,3,26,9520225,True
99958,99958,105753,105753,F,178,1,23,6,2015-02-08,2015-03-06 20:04:00,...,0000-00-00 00:00:00,2000-09-30,1912,"To everyone I'm just the ""goody goody"" or ""the...",2015-02-08 19:47:05,10,5,14,9520286,True
99969,99969,105764,105764,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,368260,I know im part wolf...I've known since 3rd gra...,2015-02-08 19:55:07,1,4,14,9520293,True
99931,99931,105725,105725,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,728632,I feel like a wolf.....i long to run and smell...,2015-02-08 19:39:20,0,0,14,9520293,True
99961,99961,105756,105756,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,629012,I am part wolf....I've known this since I was ...,2015-02-08 19:47:48,0,0,14,9520293,True

In [26]:
goodData.shape

(75673, 22)

In [33]:
goodDataSubset = goodData.iloc[0:10000,:]

In [34]:
userDict = makeUserGroupDict(goodDataSubset, 20, 14)

In [35]:
userDict

{9068545: {557163: 1},
 9297924: {115562: 1},
 9385901: {53805: 1},
 8888331: {36156: 1},
 9388046: {25978: 1},
 9388051: {332: 1},
 8936110: {1431: 1},
 5881878: {973354: 1},
 6635543: {133371: 1},
 8126489: {1783: 1},
 2029794: {241469: 1},
 9371677: {692409: 1},
 9170949: {2510: 1},
 8478752: {128197: 1},
 7471139: {972453: 1},
 9379877: {2779: 1},
 9296561: {973362: 1},
 9379883: {973082: 1},
 9348469: {128760: 1, 157943: 1},
 9388078: {50460: 1},
 9306159: {392478: 1},
 6103088: {973946: 1},
 8437809: {183: 1},
 9347127: {108256: 1},
 9379898: {180597: 1},
 9363515: {627398: 1},
 7774268: {1409: 1},
 8675389: {23323: 1},
 7561279: {32430: 1},
 7823426: {2425: 1},
 9199627: {752095: 1},
 6856773: {323567: 1},
 9379912: {668250: 1},
 9388105: {717557: 1},
 8634442: {63246: 1},
 9396301: {117528: 1},
 9396302: {109654: 1},
 5685328: {880544: 1, 911206: 1},
 9394872: {973587: 1},
 9011282: {973241: 1},
 7839827: {318328: 1},
 9396308: {973780: 1},
 5625051: {2389: 1},
 9388119: {972827: 1},
 7938137: {35507: 1},
 9388123: {2288: 1},
 8192093: {46447: 1},
 8865162: {852193: 1},
 7340127: {1431: 1},
 8364128: {395178: 1},
 9306209: {68: 1},
 9330788: {703085: 1},
 8650853: {974494: 1},
 8413287: {380152: 1},
 8290409: {267560: 1},
 9379946: {972721: 1},
 9379948: {685948: 1},
 9396334: {35461: 1, 128333: 1},
 9248881: {626880: 1},
 9076850: {292095: 1},
 5709939: {972840: 1},
 9199732: {4504: 1},
 9388149: {823007: 1},
 9314422: {766755: 1},
 8935268: {824130: 1},
 8274316: {42844: 1},
 5562492: {361027: 1},
 7424053: {590676: 1},
 4440191: {572813: 1},
 9396354: {1703: 1},
 3661955: {973993: 1},
 7635077: {17917: 1},
 8405126: {974418: 1},
 8085639: {11788: 1},
 6348942: {3897: 1},
 8691856: {984: 1},
 9379986: {72975: 1},
 7264476: {233: 1},
 8269849: {13999: 1},
 9158808: {8726: 1},
 6670340: {554517: 1},
 9330846: {135341: 1},
 2171042: {592832: 1},
 6504615: {692409: 1},
 9394887: {474257: 1},
 9388204: {79604: 1},
 1494581: {48953: 1},
 9306287: {35943: 1},
 5749448: {448642: 1},
 6529203: {973345: 1},
 8970423: {511123: 1},
 9380024: {53644: 1},
 9339067: {216969: 1},
 8216764: {381025: 1},
 6643902: {1716: 1},
 9096366: {5831: 1},
 9183424: {109: 1},
 8569026: {843967: 1},
 9216195: {644547: 1},
 9293434: {39601: 1},
 9388232: {826970: 1},
 9222860: {189134: 1},
 6701265: {974505: 1},
 9371683: {696461: 1},
 6299864: {27583: 1},
 8798426: {972636: 1},
 9052380: {327536: 1},
 8437981: {832506: 1},
 5325023: {789639: 1},
 9126112: {16185: 1},
 6889697: {255523: 1},
 6721574: {562316: 1},
 8303522: {618: 1},
 8637137: {22325: 1},
 9086666: {1431: 1},
 9371881: {659449: 1},
 9085163: {42573: 1},
 9060589: {685948: 1},
 8855791: {615862: 1},
 9388275: {310: 1},
 8446197: {320664: 1},
 9068792: {6129: 1},
 7407963: {106271: 1},
 8026837: {193494: 1},
 5923077: {5725: 1},
 9388295: {336562: 1},
 9298186: {73884: 1},
 8274187: {288629: 1},
 8241421: {62612: 1},
 9000468: {328733: 1},
 9191697: {974139: 1},
 5988628: {1261: 1},
 8241429: {956857: 1},
 8626454: {241154: 1},
 9003288: {4603: 1},
 9380122: {973608: 1},
 9199663: {114586: 1},
 8446237: {38077: 1},
 6963488: {293608: 1},
 8167713: {57701: 1},
 8028451: {972279: 1},
 9298212: {61: 1},
 9199909: {974347: 1},
 8892465: {79832: 1},
 7962921: {193494: 1},
 8798506: {166260: 1},
 7602475: {193494: 1},
 7856428: {552770: 1},
 7389486: {29294: 1},
 9396530: {5577: 1},
 9085237: {81891: 1},
 4407608: {570246: 1},
 9388345: {117528: 1},
 5882170: {259315: 1},
 7547615: {6022: 1},
 5808445: {2334: 1},
 8905023: {109: 1},
 6406466: {973390: 1},
 9314629: {81594: 1},
 8462664: {973768: 1},
 9336204: {22308: 1},
 6207177: {762291: 1},
 9166049: {563364: 1},
 9320444: {851219: 1},
 7831886: {26138: 1},
 5071185: {911061: 1},
 2580818: {59360: 1},
 9363796: {414878: 1},
 9355607: {23323: 1},
 9077080: {9648: 1},
 9388380: {930: 1},
 6111581: {686868: 1},
 9273694: {236824: 1},
 8307041: {2510: 1},
 7962979: {973342: 1},
 9388388: {31049: 1},
 7696444: {200359: 1},
 8110442: {2013: 1},
 9167212: {260948: 1},
 5210478: {141767: 1},
 7938415: {454917: 1},
 8249715: {340: 1},
 7596187: {9020: 1},
 7774582: {3153: 1},
 9109881: {61: 1},
 9085306: {220893: 1},
 9216379: {453246: 1},
 6191381: {106715: 1},
 9380222: {46471: 1},
 7376960: {786925: 1},
 8585603: {832787: 1},
 9290116: {158183: 1},
 9396825: {646363: 1},
 8555244: {714733: 1},
 9388426: {676056: 1},
 7561612: {123420: 1},
 7799181: {2510: 1},
 9101714: {500543: 1},
 9396628: {532566: 1},
 8290711: {109: 1},
 3293592: {974131: 1},
 1319323: {74137: 1},
 9347485: {4504: 1},
 8855621: {950: 1},
 8872352: {973405: 1},
 5063077: {79604: 1},
 9394929: {1039: 1},
 9068971: {2510: 1},
 8077740: {354786: 1},
 9380274: {168844: 1},
 9175475: {7470: 1},
 7340471: {589745: 1},
 9101752: {973843: 1},
 9355705: {793952: 1},
 3342778: {109: 1},
 9164191: {468561: 1},
 5505469: {57797: 1},
 8404717: {792631: 1},
 7954885: {972707: 1},
 5611974: {828259: 1},
 9393281: {30161: 1},
 7610825: {667883: 1},
 8888779: {537200: 1},
 9380300: {397495: 1},
 9397666: {599269: 1},
 7365071: {193494: 1},
 9331159: {155139: 1},
 8880600: {57814: 1},
 5820026: {973994: 1},
 9396700: {974440: 1},
 9388509: {3116: 1},
 4923870: {5805: 1},
 9331169: {27583: 1},
 9306594: {46410: 1},
 9195242: {62502: 1},
 9388522: {2510: 1},
 9388526: {26160: 1},
 4391407: {147547: 1},
 7840242: {751175: 1},
 9347571: {393195: 1, 760230: 1},
 8118773: {61: 1},
 9085432: {1768: 1},
 7250004: {43825: 1},
 8380923: {295071: 1},
 9355772: {547727: 1},
 1607082: {973370: 1},
 7504382: {606666: 1},
 9019903: {972457: 1},
 9175559: {208546: 1},
 5251594: {608103: 1},
 8027734: {974016: 1},
 8356365: {293509: 1},
 9339406: {55673: 1},
 9388559: {274458: 1},
 8913424: {457037: 1},
 1589778: {147547: 1},
 9191955: {152127: 1},
 9069078: {60049: 1},
 7209495: {394376: 1},
 5100778: {1009: 1},
 9388571: {6612: 1},
 9364003: {440082: 1},
 1974822: {903048: 1},
 6191654: {18719: 1},
 7684652: {131253: 1},
 2818605: {940485: 1},
 7143517: {1009: 1},
 8503856: {166260: 1},
 9249329: {166260: 1},
 7889460: {13434: 1},
 7963191: {102852: 1},
 3113528: {973070: 1},
 4547129: {4325: 1},
 7594559: {176803: 1},
 9396800: {197631: 1},
 7553120: {525832: 1},
 9387284: {774365: 1},
 8225353: {441356: 1},
 9396810: {225519: 1},
 9372236: {974398: 1},
 4571726: {952149: 1},
 8233552: {38854: 1},
 9372243: {642775: 1},
 9167447: {2510: 1},
 8609892: {318884: 1},
 5530202: {43748: 1},
 9396827: {24246: 1},
 9248984: {4603: 1},
 9183837: {968221: 1},
 4104800: {8889: 1},
 9390864: {117528: 1},
 9396834: {1037: 1},
 9151076: {135625: 1},
 8692325: {369588: 1},
 8847974: {236615: 1},
 2359911: {46972: 1},
 9380456: {147372: 1},
 9233002: {159574: 1},
 9380459: {964037: 1},
 9352637: {577530: 1},
 2597183: {3014: 1},
 6677106: {972790: 1},
 9380467: {31373: 1},
 9183860: {296125: 1},
 5784182: {395178: 1},
 9395442: {1039: 1},
 9290361: {642093: 1},
 9200252: {972829: 1},
 9364093: {23761: 1},
 8799680: {638562: 1},
 6873735: {438507: 1},
 9396874: {233190: 1},
 9380491: {972801: 1},
 9339533: {591578: 1},
 9118352: {973102: 1},
 8266385: {231443: 1},
 9282195: {791202: 1},
 7553685: {4603: 1},
 9274007: {1536: 1},
 8733336: {35004: 1},
 7611033: {946362: 1},
 8344712: {233190: 1},
 9233051: {666674: 1},
 9218842: {439402: 1},
 7338775: {974475: 1},
 9347743: {117528: 1},
 6634032: {1431: 1},
 5259939: {59893: 1},
 9303494: {625998: 1},
 9371761: {790543: 1},
 8364713: {973224: 1},
 6775467: {41: 1},
 8389293: {285: 1},
 8274606: {974192: 1},
 8258225: {16727: 1},
 7733363: {1009: 1},
 4080308: {973298: 1},
 9347768: {335: 1},
 9233082: {32755: 1},
 9389514: {2744: 1},
 5658351: {38854: 1},
 9349855: {9041: 1},
 9388742: {117528: 1},
 6480584: {34871: 1},
 4440778: {180983: 1},
 8757963: {192135: 1},
 9195640: {785061: 1},
 3580628: {488278: 1},
 9388757: {14825: 1},
 8273245: {765052: 1},
 9384561: {534997: 1},
 9388760: {474654: 1},
 9380571: {324419: 1},
 8790749: {399560: 1},
 7217889: {19494: 1},
 9061092: {233: 1},
 9241317: {7258: 1},
 5718762: {157324: 1},
 8405748: {972747: 1},
 4254948: {333389: 1},
 7684856: {395178: 1},
 9224953: {830649: 1},
 6095611: {332: 1},
 6603519: {974417: 1},
 8422144: {188413: 1},
 3818244: {19494: 1},
 8274693: {1960: 1},
 9347846: {4603: 1},
 9184007: {7420: 1},
 7826220: {630480: 1},
 8102666: {1960: 1},
 9283906: {175793: 1},
 9344191: {100216: 1},
 8149805: {3340: 1},
 8774417: {64391: 1},
 9388818: {333277: 1},
 9302589: {465002: 1},
 8851819: {299282: 1},
 9036573: {692461: 1},
 9105542: {112362: 1},
 6193959: {705553: 1},
 9364264: {233: 1},
 9184044: {599269: 1},
 9399090: {199502: 1},
 6243118: {118728: 1},
 9397112: {974117: 1},
 9356083: {766000: 1},
 9388853: {596233: 1},
 5014329: {54: 1},
 9208634: {973600: 1},
 9397051: {1647: 1},
 9397052: {2404: 1},
 9388861: {4603: 1},
 6800190: {335822: 1},
 6095683: {8830: 1},
 9397062: {442584: 1},
 9390903: {571750: 1},
 8389452: {42844: 1},
 7570255: {101938: 1},
 238416: {224848: 1},
 9390904: {1662: 1},
 9184739: {973508: 1},
 7152469: {853432: 1},
 8520534: {942068: 1},
 7444536: {136425: 1},
 9339741: {440080: 1},
 9069406: {2126: 1},
 6783839: {244: 1},
 9372513: {552041: 1},
 7889763: {734615: 1},
 9388900: {859248: 1},
 6882149: {195107: 1},
 9364327: {53200: 1},
 4735848: {631392: 1},
 7611243: {513601: 1},
 7857005: {2704: 1},
 9364334: {174899: 1},
 7619439: {174754: 1},
 9200496: {577159: 1},
 9337236: {9395: 1},
 7824243: {311370: 1},
 9397108: {162768: 1},
 9397111: {157109: 1},
 8930168: {559296: 1},
 9397114: {10031: 1},
 6167617: {182813: 1},
 8979324: {2510: 1},
 8930174: {33901: 1},
 9380735: {63991: 1},
 7177089: {16858: 1},
 9377259: {972735: 1},
 9274244: {2241: 1},
 8299398: {349825: 1},
 3220361: {331761: 1},
 8127371: {232315: 1},
 9298830: {158764: 1},
 9259360: {496487: 1},
 9118610: {785256: 1},
 9397141: {791979: 1},
 9339800: {973263: 1},
 7144345: {377292: 1},
 7644063: {214865: 1},
 9397152: {102643: 1},
 9356193: {7270: 1},
 9225122: {242389: 1},
 9192355: {2881: 1},
 9397156: {252158: 1},
 9249702: {96165: 1},
 9257896: {533684: 1},
 4326316: {38024: 1},
 7570350: {17895: 1},
 9388975: {117528: 1},
 9388978: {222207: 1},
 2077543: {30368: 1},
 9377919: {610851: 1},
 7938998: {627239: 1},
 8725431: {116836: 1},
 8471480: {259569: 1},
 9069497: {974054: 1},
 9319925: {438507: 1},
 8225728: {335: 1},
 9375904: {45527: 1},
 9112395: {166348: 1},
 9036741: {887: 1},
 9380807: {674645: 1},
 5912055: {973725: 1},
 8954832: {2923: 1},
 4518051: {8631: 1},
 6448084: {1649: 1},
 7177184: {984: 1},
 9389031: {171317: 1},
 8340456: {341222: 1},
 8922089: {4603: 1},
 8086506: {74708: 1},
 9389035: {5364: 1},
 4318189: {951492: 1},
 9397231: {9607: 1},
 9372657: {972785: 1},
 6988786: {4996: 1},
 8721194: {482325: 1},
 9298936: {771623: 1},
 9061369: {973753: 1},
 6594372: {1431: 1},
 6702081: {8726: 1},
 9159685: {493264: 1},
 9323527: {439222: 1},
 9331720: {54471: 1},
 8143885: {2510: 1},
 9315342: {1843: 1},
 9298959: {792344: 1},
 9389073: {649778: 1},
 8250387: {771623: 1},
 4761999: {2108: 1},
 5669909: {809: 1},
 8848409: {2108: 1},
 7169050: {12083: 1},
 9333594: {727237: 1},
 9397278: {791979: 1},
 8061983: {738: 1},
 7980066: {5882: 1},
 8422435: {164: 1},
 4908068: {53305: 1},
 9108789: {830392: 1},
 9192488: {740097: 1},
 7857199: {887: 1},
 8725552: {249286: 1},
 9086001: {25750: 1, 232504: 1, 659240: 1},
 9159730: {347473: 1},
 2605235: {332: 1},
 9351040: {22708: 1},
 5928457: {1431: 1},
 9274432: {707237: 1},
 6874177: {4737: 1},
 9389122: {15512: 1},
 9319947: {691: 1},
 5375044: {487396: 1},
 9389125: {69229: 1},
 5659728: {57763: 1},
 9384119: {59784: 1},
 9395212: {582056: 1},
 9258063: {451979: 1},
 9380944: {63027: 1},
 7881811: {28660: 1},
 5596246: {43748: 1},
 9389144: {17505: 1},
 6710368: {564963: 1},
 7226466: {1716: 1},
 7663803: {631779: 1},
 5719142: {4603: 1},
 8889447: {395400: 1},
 9380968: {109: 1},
 8856681: {32341: 1},
 5948522: {102852: 1},
 9276263: {16641: 1},
 8791148: {753267: 1},
 9372782: {27113: 1},
 8731496: {15032: 1},
 8987762: {1261: 1},
 9364596: {194665: 1},
 9400510: {148317: 1},
 9274486: {1431: 1},
 9364601: {3055: 1},
 7734395: {4753: 1},
 6079612: {822394: 1},
 9282686: {171317: 1},
 7570560: {376: 1},
 7292033: {8726: 1},
 8340610: {625472: 1},
 8021123: {81955: 1},
 9389190: {296: 1},
 9397383: {279522: 1},
 8026988: {570250: 1},
 9389196: {9280: 1},
 8446146: {4504: 1},
 7898257: {496759: 1},
 9389202: {904675: 1},
 9356435: {420: 1},
 9395054: {34649: 1},
 8152216: {480208: 1},
 9356442: {181747: 1},
 6228847: {17709: 1},
 9397404: {96437: 1},
 8701093: {956386: 1},
 8733865: {17471: 1},
 9389226: {273881: 1},
 9389232: {1261: 1},
 9397425: {46994: 1},
 9233586: {382788: 1},
 1664542: {164785: 1},
 6841527: {829312: 1},
 9290938: {698345: 1},
 7374011: {86456: 1},
 9258173: {562447: 1},
 9209022: {973564: 1},
 9395061: {534997: 1},
 8529088: {43825: 1},
 7644355: {293608: 1},
 6882500: {973525: 1},
 7535478: {913466: 1},
 9184454: {579960: 1},
 4891847: {558999: 1},
 7206682: {658803: 1},
 5741431: {786783: 1},
 2168354: {616034: 1},
 8602832: {42844: 1},
 8153976: {912107: 1},
 8070357: {536653: 1},
 7922902: {57379: 1},
 9209049: {311: 1},
 8914138: {927873: 1},
 3638492: {109: 1},
 9127133: {28635: 1},
 8258782: {2510: 1},
 7087327: {192767: 1, 386276: 1, 473800: 1},
 9397476: {880814: 1},
 9274598: {809: 1},
 8439660: {344880: 1},
 9372907: {610851: 1},
 5833967: {762291: 1},
 8455408: {206887: 1},
 8316146: {233: 1},
 9340150: {376017: 1},
 9274375: {966345: 1},
 9340154: {3153: 1},
 9397499: {23867: 1},
 8631850: {12525: 1},
 9274624: {258493: 1},
 4015371: {88051: 1},
 5039372: {198483: 1},
 8848653: {254443: 1},
 8987919: {506210: 1},
 8389904: {30197: 1},
 8242449: {7258: 1},
 9086228: {858639: 1},
 7349525: {502228: 1},
 9400538: {199979: 1},
 9331999: {779718: 1},
 8906016: {763: 1},
 6625246: {43546: 1},
 7726371: {168933: 1},
 8955174: {2108: 1},
 6668508: {3539: 1},
 8809351: {973788: 1},
 8996141: {141172: 1},
 7054638: {620454: 1},
 3908911: {34901: 1},
 9243528: {261634: 1},
 8709429: {9607: 1},
 5686583: {300297: 1},
 8848697: {274157: 1},
 9315643: {160526: 1},
 9389376: {527118: 1},
 9381186: {6190: 1},
 9151812: {763: 1},
 9094472: {67567: 1},
 9028937: {7770: 1},
 9266507: {42844: 1},
 9241933: {237109: 1},
 9241935: {577661: 1},
 9397584: {12159: 1},
 8037713: {680873: 1},
 8865108: {147095: 1},
 9345407: {16219: 1},
 5326167: {12654: 1},
 2843992: {972917: 1},
 9094489: {23323: 1},
 9389402: {5064: 1},
 9381211: {15349: 1},
 7365980: {1009: 1},
 9119076: {828002: 1},
 9364839: {346597: 1},
 9323880: {856092: 1},
 8971626: {771281: 1},
 9397611: {767180: 1},
 1312108: {973413: 1},
 7825631: {19494: 1},
 8815983: {809: 1},
 8275312: {99561: 1},
 6910173: {8611: 1},
 9356661: {61: 1},
 8144247: {120801: 1},
 5645693: {362670: 1},
 9397630: {252158: 1},
 8816010: {59107: 1},
 8578443: {26632: 1},
 9029008: {6022: 1},
 9389460: {251048: 1},
 9066520: {27113: 1},
 6989207: {2805: 1},
 9180740: {846238: 1},
 8676765: {562421: 1},
 9397663: {973962: 1},
 5342624: {973859: 1},
 8029602: {861756: 1},
 4025243: {829312: 1},
 9004455: {2223: 1},
 8836565: {133064: 1},
 9389483: {845841: 1},
 6219182: {608001: 1},
 9397679: {583200: 1},
 4285874: {148683: 1},
 5891508: {655620: 1},
 9299381: {2241: 1},
 8177079: {284570: 1},
 7500020: {21019: 1},
 6620603: {637431: 1},
 9393738: {148219: 1},
 7046590: {375439: 1},
 4965824: {7753: 1},
 6309313: {834128: 1},
 9401458: {181: 1},
 8234436: {832323: 1},
 8938950: {129204: 1},
 6620748: {587487: 1},
 9143754: {6466: 1},
 7422200: {326643: 1},
 7916471: {974430: 1},
 6874583: {193494: 1},
 9313188: {287243: 1},
 9381338: {443922: 1},
 8750671: {331417: 1},
 5055964: {973781: 1},
 8898013: {1000: 1},
 7849439: {61764: 1},
 8177121: {574396: 1},
 8103395: {118120: 1},
 9389649: {363662: 1},
 8182695: {906042: 1},
 9381356: {765052: 1},
 8905592: {798874: 1},
 9397745: {21233: 1},
 6366709: {446858: 1},
 9283062: {395: 1},
 9320021: {33424: 1},
 5056000: {800571: 1},
 3524097: {809: 1},
 9397847: {26160: 1},
 6342157: {102852: 1},
 7218703: {547660: 1},
 7644688: {973817: 1},
 9111057: {262541: 1},
 8816146: {972779: 1},
 9020949: {43338: 1},
 8267286: {292851: 1},
 9389594: {324204: 1},
 8997807: {1544: 1},
 4744732: {763: 1},
 9389598: {42844: 1},
 9382832: {809: 1},
 4662818: {658751: 1},
 7976213: {14153: 1},
 7972389: {635161: 1},
 5334566: {8155: 1, 33927: 1},
 8537642: {51328: 1},
 7579181: {17036: 1},
 9397807: {7569: 1},
 5162548: {35125: 1},
 8906293: {10548: 1},
 2508342: {293505: 1},
 8095288: {14000: 1},
 9395774: {974062: 1},
 7766282: {942068: 1},
 9315936: {245: 1},
 6070539: {972812: 1},
 5416516: {332: 1},
 9124790: {536551: 1},
 6792776: {6025: 1},
 9225801: {852354: 1},
 7543854: {604826: 1},
 755276: {706459: 1},
 8627791: {620653: 1},
 6683576: {972446: 1},
 9397843: {117528: 1},
 8478990: {6952: 1},
 8570454: {41: 1},
 4023895: {771959: 1},
 9397849: {821852: 1},
 9397854: {973959: 1},
 9345856: {6613: 1},
 9119329: {629187: 1},
 9307747: {17163: 1},
 9397861: {17163: 1},
 8832615: {8466: 1},
 9332328: {847658: 1},
 5064297: {2053: 1},
 5113450: {88130: 1},
 9291371: {166260: 1},
 7759468: {282015: 1},
 3860079: {984: 1},
 9340528: {19212: 1},
 6637171: {33901: 1},
 6071924: {800825: 1},
 9355540: {33901: 1},
 4422678: {3160: 1},
 6915710: {273618: 1},
 6669953: {972499: 1},
 5826178: {806746: 1},
 9391041: {149937: 1},
 4335212: {1431: 1},
 9365131: {622655: 1},
 5700546: {70995: 1},
 8332943: {2510: 1},
 9388312: {436588: 1},
 7382675: {423: 1},
 5957269: {7420: 1},
 9381526: {4603: 1},
 9383502: {16446: 1},
 6719137: {402771: 1},
 9127586: {576911: 1},
 8660648: {109186: 1},
 9184938: {689947: 1},
 7785415: {540639: 1},
 8423084: {74661: 1},
 9021103: {9538: 1},
 9086640: {839923: 1},
 8758961: {972679: 1},
 8349362: {399427: 1},
 9397875: {112156: 1},
 8234676: {36690: 1},
 9201333: {687814: 1},
 8436681: {365646: 1},
 5727929: {226782: 1},
 7752650: {216037: 1},
 6496544: {164: 1},
 7915202: {7070: 1},
 9021123: {30000: 1},
 9105942: {589009: 1},
 7726789: {147547: 1},
 9348806: {62236: 1},
 9232673: {147547: 1},
 7955487: {9440: 1},
 6088393: {2510: 1},
 9070282: {122859: 1},
 8260557: {741492: 1},
 5826257: {648757: 1},
 9332434: {7270: 1},
 6467875: {133398: 1},
 9373397: {5314: 1},
 8750812: {36879: 1},
 9012957: {12521: 1},
 9397982: {282425: 1},
 8546016: {792071: 1},
 8791777: {531262: 1},
 8324834: {3933: 1},
 9331403: {972702: 1},
 9393788: {887: 1},
 4982507: {799761: 1},
 5259033: {226278: 1},
 5413842: {2648: 1},
 7505647: {138917: 1},
 9348848: {1009: 1},
 7147816: {196957: 1},
 7415538: {189667: 1},
 9210835: {973420: 1},
 9381622: {71419: 1},
 9307895: {430908: 1},
 9398011: {974019: 1},
 9389820: {791979: 1},
 9381630: {651866: 1},
 9398016: {3219: 1},
 8890113: {18336: 1},
 9392071: {90: 1},
 2629931: {60578: 1, 598688: 1},
 7522054: {2011: 1},
 9389697: {464215: 1},
 7489288: {424396: 1},
 9357065: {589745: 1},
 5760778: {183: 1},
 4802315: {55831: 1},
 7751436: {193494: 1},
 2131586: {339318: 1},
 9053969: {42844: 1},
 8222339: {117528: 1},
 7603989: {972673: 1},
 8988438: {602512: 1},
 8537879: {541043: 1, 851913: 1},
 7345548: {1431: 1},
 6663130: {151334: 1},
 9201441: {587712: 1},
 8333021: {233: 1},
 9357091: {286589: 1},
 9398054: {780833: 1},
 9340713: {364580: 1},
 9059006: {625998: 1},
 9397895: {846290: 1},
 8906542: {117528: 1},
 9217839: {958556: 1},
 9004849: {206687: 1},
 9381683: {622: 1},
 9381685: {236337: 1},
 8767287: {570842: 1},
 5015352: {686868: 1},
 9324345: {646363: 1},
 9386975: {306223: 1},
 4728639: {225367: 1},
 9381696: {140590: 1},
 7104325: {12964: 1},
 5539654: {284463: 1},
 2557767: {2917: 1},
 6104904: {25949: 1},
 9299785: {150686: 1},
 9387054: {974061: 1},
 9316172: {5247: 1},
 9217869: {603913: 1},
 9381517: {17036: 1},
 8972112: {540797: 1},
 9376143: {182528: 1},
 9398101: {665612: 1},
 9293490: {63626: 1},
 9389913: {27583: 1},
 9389914: {973093: 1},
 8406875: {325215: 1},

In [38]:
totalEntries = 0
for key in userDict.keys():
    dictLen = len(userDict[key])
    print dictLen
    totalEntries += dictLen

In [47]:
for i in range(0,2):
    print i
i

1

In [50]:
goodData.iloc[0:150,[14,20]]

        gid      uid
3    970365  9367848
4    262541  7581701
5    261634  8626454
6     88442  8267845
8    368043  9166441
9     36977  8128714
10      495  9374607
11   565765  9318024
12   293608  9087949
13   473848  9382904
14   488521  9166429
15   627239  7938998
17     3941  9364093
19   395178  8149149
20   395247  8449220
21   293608  9087949
22    59004  9379414
23      335  9335149
24   427042  8939668
25   675119  9357924
26   293608  8167713
27   173000  7812690
29      185  9184454
30   972256  6609242
31     2389  9351351
32   117528  9357495
33   160526  9226988
35     8436  2050477
36     1340  8905023
38   640484  6769181
..      ...      ...
153  363594  8876773
156  270467  8128714
157    9074  9238698
159  592832  2171042
160    9041  9383214
161  972276  8929122
162   14065  8147946
163    7258  8242449
164    1647  8367344
166    1340  9290938
167  555013  9052745
168   18708  9238698
169  967473  3505192
170  279355  8128714
171  118799  9298830
172  443149  8128714
174   15798  9258063
175  972277  6900282
177     182  8128714
179  420223  8498982
181   13643  8128714
182  453278  4086293
183   46251  8745133
184  166260  8503856
185  972279  8028451
186  972277  6900282
188    1960  8367344
189   57540  9108214
190  453278  4086293
191  153452  8939668

[150 rows x 2 columns]

In [51]:
userDict2 = makeUserGroupDict(goodData.iloc[0:150,:],20,14)

In [52]:
userDict2

{2050477: {8436: 1},
 2171042: {592832: 1},
 2338798: {972263: 1},
 2529477: {293463: 1},
 2992395: {104699: 1},
 3505192: {967473: 1},
 4086293: {453278: 1},
 4308942: {61: 1},
 5749365: {233: 1},
 5783256: {239092: 1},
 5876098: {27995: 1},
 5897203: {298475: 1},
 6053020: {293608: 1},
 6504361: {17036: 1},
 6609242: {972256: 1},
 6683320: {7366: 1},
 6749444: {84950: 1},
 6769181: {640484: 1},
 6900282: {972277: 1},
 6926900: {2510: 1},
 7046590: {834927: 1},
 7382675: {12159: 1},
 7516104: {972264: 1},
 7581701: {262541: 1},
 7684856: {395178: 1},
 7733234: {17709: 1},
 7812690: {173000: 1},
 7889763: {291932: 1},
 7938998: {627239: 1},
 8028451: {972279: 1},
 8128714: {13643: 1},
 8147946: {14065: 1},
 8149149: {395178: 1},
 8155992: {156353: 1},
 8167713: {293608: 1},
 8242449: {7258: 1},
 8258225: {16727: 1},
 8267845: {203939: 1},
 8367344: {1960: 1},
 8384457: {395178: 1},
 8446685: {51293: 1},
 8449220: {395247: 1},
 8498982: {420223: 1},
 8503856: {166260: 1},
 8626454: {261634: 1},
 8678482: {200183: 1},
 8680692: {707237: 1},
 8745133: {46251: 1},
 8748958: {274318: 1},
 8844030: {47620: 1},
 8876773: {363594: 1},
 8898013: {1000: 1},
 8905023: {1340: 1},
 8929122: {972276: 1},
 8934237: {76430: 1},
 8939668: {153452: 1},
 8941440: {157992: 1},
 9052745: {555013: 1},
 9069078: {60049: 1},
 9072106: {421539: 1},
 9086001: {25750: 1, 232504: 1, 659240: 1},
 9087949: {293608: 1},
 9108214: {57540: 1},
 9156227: {10962: 1},
 9166429: {488521: 1},
 9166441: {368043: 1},
 9173747: {56871: 1},
 9184454: {185: 1},
 9226988: {160526: 1},
 9238698: {18708: 1},
 9244456: {743337: 1},
 9252134: {128712: 1},
 9258063: {15798: 1},
 9290938: {1340: 1},
 9298830: {118799: 1},
 9299381: {121118: 1},
 9311038: {51443: 1},
 9311606: {117528: 1},
 9317696: {69229: 1},
 9318024: {565765: 1},
 9326417: {956743: 1},
 9328102: {122615: 1},
 9331999: {779718: 1},
 9335149: {335: 1},
 9351351: {2389: 1},
 9355705: {16539: 1},
 9357495: {229654: 1},
 9357924: {675119: 1},
 9363796: {708: 1},
 9364093: {3941: 1},
 9364264: {942068: 1},
 9364327: {53200: 1},
 9367848: {970365: 1},
 9374607: {495: 1},
 9376143: {558242: 1},
 9379414: {59004: 1},
 9381696: {140590: 1},
 9382904: {473848: 1},
 9383100: {42740: 1},
 9383214: {9041: 1}}

In [54]:
len(userDict2)

100

In [55]:
totalEntries = 0
for key in userDict2.keys():
    totalEntries += len(userDict2[key])

In [56]:
totalEntries

102

In [57]:
goodDataSorted = goodData.sort(columns='uid')

In [58]:
goodDataSorted.iloc[0:25,[14,20]]

          gid    uid
69383   13512   1062
50974     247   2168
44768  181576   3243
22952    9648   6193
592    972333  44448
30338    2510  47289
50084    2510  47289
62602    2510  47289
78678   63676  47664
93054    8450  49208
93040    6156  49208
92440     310  49208
94277     310  49208
94893   17806  49208
91420  453672  49208
94794  989529  49208
92462    9902  49208
94760  989529  49208
91410    2332  49208
59611  321718  50049
62769  321718  50049
97240  989996  50049
38673  980251  50049
25137  976977  50049
95070  522535  53997

In [59]:
userDict3 = makeUserGroupDict(goodDataSorted.iloc[0:25,:],20,14)

In [62]:
userDict3[49208]

{310: 2, 2332: 1, 6156: 1, 8450: 1, 9902: 1, 17806: 1, 453672: 1, 989529: 2}

In [63]:
totalEntries = 0
for ukey in userDict3.keys():
    for gkey in userDict3[ukey].keys():
        totalEntries += userDict3[ukey][gkey]

In [64]:
totalEntries

25

In [84]:
userDict4 = makeUserGroupDict(goodData.iloc[0:25,:],20,14)

In [85]:
goodData.iloc[0:25,[14,20]]

       gid      uid
3   970365  9367848
4   262541  7581701
5   261634  8626454
6    88442  8267845
8   368043  9166441
9    36977  8128714
10     495  9374607
11  565765  9318024
12  293608  9087949
13  473848  9382904
14  488521  9166429
15  627239  7938998
17    3941  9364093
19  395178  8149149
20  395247  8449220
21  293608  9087949
22   59004  9379414
23     335  9335149
24  427042  8939668
25  675119  9357924
26  293608  8167713
27  173000  7812690
29     185  9184454
30  972256  6609242
31    2389  9351351

In [86]:
userDict4

{6609242: {972256: 1},
 7581701: {262541: 1},
 7812690: {173000: 1},
 7938998: {627239: 1},
 8128714: {36977: 1},
 8149149: {395178: 1},
 8167713: {293608: 1},
 8267845: {88442: 1},
 8449220: {395247: 1},
 8626454: {261634: 1},
 8939668: {427042: 1},
 9087949: {293608: 2},
 9166429: {488521: 1},
 9166441: {368043: 1},
 9184454: {185: 1},
 9318024: {565765: 1},
 9335149: {335: 1},
 9351351: {2389: 1},
 9357924: {675119: 1},
 9364093: {3941: 1},
 9367848: {970365: 1},
 9374607: {495: 1},
 9379414: {59004: 1},
 9382904: {473848: 1}}

In [87]:
len(userDict4)

24

In [69]:
len(goodData.iloc[0:25,:])

25

In [88]:
totalEntries = 0
for ukey in userDict4.keys():
    for gkey in userDict4[ukey].keys():
        totalEntries += userDict4[ukey][gkey]

In [89]:
totalEntries

25

In [72]:
temp = goodData.iloc[0:25,:]

In [74]:
tempSorted = temp.sort(columns = 'uid')

In [75]:
tempSorted.iloc[:,[14,20]]

       gid      uid
30  972256  6609242
4   262541  7581701
27  173000  7812690
15  627239  7938998
9    36977  8128714
19  395178  8149149
26  293608  8167713
6    88442  8267845
20  395247  8449220
5   261634  8626454
24  427042  8939668
21  293608  9087949
12  293608  9087949
14  488521  9166429
8   368043  9166441
29     185  9184454
11  565765  9318024
23     335  9335149
31    2389  9351351
25  675119  9357924
17    3941  9364093
3   970365  9367848
10     495  9374607
22   59004  9379414
13  473848  9382904

In [76]:
userDict4[9087949]

{293608: 1}

In [77]:
userDict5 = makeUserGroupDict(tempSorted,20,14)

In [78]:
len(userDict5)

24

In [79]:
userDict5[9087949]

{293608: 2}

In [80]:
temp.sort(columns='uid')

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
30,30,31,31,M,239,61,49,48,2013-07-17,2015-07-09 14:35:49,...,2015-01-02 21:49:33,1959-06-30,972256,I hope it's a good year for everyone,2015-01-01 00:14:46,1,1,56,6609242,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
31,31,32,32,M,171,100,81,53,2014-12-22,2015-07-10 00:32:09,...,0000-00-00 00:00:00,1995-11-30,2389,My new years resolution is to quit my nasty ch...,2015-01-01 00:14:59,0,1,19,9351351,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True

In [81]:
temp.iloc[0,20]

9367848

In [82]:
temp

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
30,30,31,31,M,239,61,49,48,2013-07-17,2015-07-09 14:35:49,...,2015-01-02 21:49:33,1959-06-30,972256,I hope it's a good year for everyone,2015-01-01 00:14:46,1,1,56,6609242,True
31,31,32,32,M,171,100,81,53,2014-12-22,2015-07-10 00:32:09,...,0000-00-00 00:00:00,1995-11-30,2389,My new years resolution is to quit my nasty ch...,2015-01-01 00:14:59,0,1,19,9351351,True

In [93]:
groupNameFile = "/Users/dharshid/CDIPS_Project/data/group_names.csv"
groupNames = pd.read_csv(groupNameFile,names=['gid','group_name'],header=None)

In [94]:
groupNames

            gid                                         group_name
0            20                                            Love U2
1            21                                     Love Dane Cook
2            22                               Love Pablo Francisco
3            23                                  Love George Lopez
4            24                                    Love Bill Cosby
5            25                      Had In-office Teeth Whitening
6            26                                    Love Chris Rock
7            27                              Love David Hasselhoff
8            28                               Love Stephen Colbert
9            29                                  Love John Stewart
10           30                                 Love Conan O'brien
11           31                                      Love Jay Leno
12           32                               Love David Letterman
13           33                                   Love Kara Monaco
14           34                          Love Arrested Development
15           35                                  Love David Blaine
16           36                 Love Jang And Associates Dentistry
17           37                        Had My Wisdom Teeth Removed
18           38                            Have Ulcerative Colitis
19           39                                      Hate Dentists
20           40                                       Went Surfing
21           41                                      Have Insomnia
22           42                              Live In San Francisco
23           43                                Had a Sigmoidoscopy
24           44                               Went to a U2 Concert
25           45         Did a Bowel Preparation For a Medical Exam
26           46                        Went to Stanford University
27           47                    Moved Across Country For My Job
28           48                                  Vomited In My Car
29           49                           Passed Out From Drinking
...         ...                                                ...
853966  1048161        Have Held Onto My Dad And Step Dads Weiners
853967  1048162                             My Dad Came On My Face
853968  1048163                   My Step Dad Paul Came On My Face
853969  1048164                            Gave My Dad A Lap Dance
853970  1048165                           How A Real Man Should Be
853971  1048166                           Hate Drive Through Jerks
853972  1048167                     Put My Dads Weiner In My Mouth
853973  1048168                          My Dad Skeeted On My Face
853974  1048169                             Feel Sadness Right Now
853975  1048170                             Need A Good Female Pet
853976  1048171      Live In Alabama Any Ladies Close To Northport
853977  1048172                        Found My Crossdressing Name
853978  1048173                         Like How Nietzsche Said It
853979  1048174                                      Love Own Cumm
853980  1048175                      Really Love These Song Lyrics
853981  1048176        Like Listening To Music When I Am Depressed
853982  1048177           Am Influenced By You More Than You Think
853983  1048178                     Bad Breath - The Kiss Of Death
853984  1048179                    Life Teaches Some Tough Lessons
853985  1048180                            Am Having Love Problems
853986  1048181                                          'M Blinda
853987  1048182                                        Always Feel
853988  1048183                 Trust People Who I Shouldn't Trust
853989  1048184                            Am Finding It Difficult
853990  1048185                                        Call It Now
853991  1048186                    Just Say Something About Soccer
853992  1048187                      Listen To Music When Cleaning
853993  1048188  Brush My Teeth To The Rhythm Of Road Construct...
853994  1048189                   Like This Price Of Soccer Jersey
853995  1048190                  Have Played The Yellow Light Game

[853996 rows x 2 columns]

In [95]:
tempSorted

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
30,30,31,31,M,239,61,49,48,2013-07-17,2015-07-09 14:35:49,...,2015-01-02 21:49:33,1959-06-30,972256,I hope it's a good year for everyone,2015-01-01 00:14:46,1,1,56,6609242,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
31,31,32,32,M,171,100,81,53,2014-12-22,2015-07-10 00:32:09,...,0000-00-00 00:00:00,1995-11-30,2389,My new years resolution is to quit my nasty ch...,2015-01-01 00:14:59,0,1,19,9351351,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True

In [101]:
tempGID = tempSorted['gid'].values

In [ ]:
tempGID