In [24]:
import sys
# Without following 2 lines, I cannot do something like EPData[EPData['uid']==0] 
# with a dataframe EPData
# See http://stackoverflow.com/questions/28983608/how-to-create-a-pandas-dataframe-containing-columns-with-special-characters  for further explanation
reload(sys)
sys.setdefaultencoding('utf-8') 
import pandas as pd
dataWithUserIDs = pd.read_csv("/Users/dharshid/CDIPS_Project/data/First100000_with_id.csv")

In [25]:
dataWithUserIDs.columns

Index([u'Unnamed: 0', u'Unnamed: 0.1', u'Unnamed: 0.1', u'gender',
       u'num_groups', u'num_entries', u'num_fans', u'num_friends', u'created',
       u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments', u'age', u'uid',
       u'certainty'],
      dtype='object')

In [26]:
dataWithUserIDs

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
0,0,0,0,F,210,54,25,2,2014-12-20,2015-04-03 12:45:01,...,0000-00-00 00:00:00,1997-03-31,124249,I just want my mom to hug me and say that she ...,2015-01-01 00:00:10,0,0,18,9343578,False
1,1,1,1,F,25,9,2,0,2014-08-28,2015-04-15 22:32:36,...,0000-00-00 00:00:00,1994-03-31,5276,I don't know why this is happening right now. ...,2015-01-01 00:00:46,0,0,21,8866629,False
2,2,3,3,M,153,2,6,5,2014-12-13,2015-06-01 20:34:52,...,2014-12-13 08:37:11,1993-11-30,58852,HAPPY NEW YEARS !!!!!!!!!!!!!!! !!!!!!!!!...,2015-01-01 00:02:39,1,2,21,9318824,False
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
7,7,8,8,M,250,255,1,0,2014-11-29,2015-03-25 09:23:41,...,0000-00-00 00:00:00,1982-11-30,962002,"Be of good character, should have an eighth gr...",2015-01-01 00:06:00,0,1,32,9270416,False
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
16,16,17,17,M,401,429,1,0,2014-11-29,2015-04-02 03:17:34,...,0000-00-00 00:00:00,1982-11-30,957283,By far the most economical home heating proced...,2015-01-01 00:10:14,0,1,32,9270002,False
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
18,18,19,19,M,426,458,2,0,2014-11-27,2015-03-23 22:36:26,...,0000-00-00 00:00:00,1982-11-30,957417,Although the price of propane does rise and tu...,2015-01-01 00:10:23,0,1,32,9263763,False
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
28,28,29,29,M,7,1,1,0,2014-12-31,2015-01-01 12:19:54,...,0000-00-00 00:00:00,1974-04-30,972255,Ok here is some background. When I was a kid I...,2015-01-01 00:14:17,0,0,41,9383083,False
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,99970,105765,105765,M,57,13,13,13,2015-02-07,2015-04-03 17:16:36,...,0000-00-00 00:00:00,1999-02-28,526490,ITS ABOUT TO BEGIN <br />\nIM TOO EXCITED,2015-02-08 19:56:00,4,2,16,9515708,True
99971,99971,105766,105766,M,357,72,347,260,2014-03-04,2015-07-09 20:23:50,...,2015-01-22 23:54:23,1998-07-31,926420,"If I told you I've never been kissed, would yo...",2015-02-08 19:56:55,2,2,16,7975284,True
99972,99972,105767,105767,F,17,8,22,8,2015-01-28,2015-02-09 10:35:03,...,0000-00-00 00:00:00,1997-05-31,80727,YES I WILL BE 18 WITH 2 KIDS. <br />\nI AM NOT...,2015-02-08 19:57:06,2,3,18,9481709,False
99973,99973,105768,105768,M,29,8,16,8,2015-01-24,2015-07-09 23:30:08,...,2015-03-11 18:55:52,1998-01-31,532453,My parents will never make me fat,2015-02-08 19:57:49,1,2,17,9468107,False
99974,99974,105769,105769,F,16,11,4,3,2014-11-17,2015-07-04 10:13:58,...,2015-03-22 19:57:20,1975-03-31,990553,Even though I'm clearly gay I still get approa...,2015-02-08 19:58:45,0,0,40,9226696,True
99975,99975,105770,105770,M,847,294,244,63,2013-06-03,2015-07-09 23:12:02,...,2015-07-01 16:06:23,1973-03-31,332,<b> Then and Now â€¦</b><br />\n<br />\nReflec...,2015-02-08 19:58:49,23,8,42,6418405,True
99976,99976,105771,105771,F,107,52,164,41,2011-10-18,2015-06-02 08:06:38,...,2014-01-15 11:53:11,1991-10-31,301,"I was dreaming I was on a pathway, looking dow...",2015-02-08 19:59:11,0,3,23,4314790,True
99977,99977,105772,105772,M,700,53,35,1,2014-07-06,2015-07-09 22:32:46,...,0000-00-00 00:00:00,2000-03-31,370,"And yet again I'm in the bathroom, on the floo...",2015-02-08 20:00:04,2,1,15,8552640,True
99978,99978,105773,105773,F,586,257,719,561,2009-07-05,2015-06-23 13:26:13,...,2015-04-19 15:19:36,1992-06-30,758,No amount of tears I've cried or many prayers ...,2015-02-08 20:01:12,5,1,23,0,True
99979,99979,105774,105774,F,605,88,327,72,2011-05-10,2015-07-10 00:29:54,...,2014-03-14 03:23:19,1997-03-07,9644,The MTA just loves prices hikes so much that t...,2015-02-08 20:01:31,0,0,18,3823094,True
99980,99980,105775,105775,F,1259,416,361,11,2014-11-16,2015-07-09 22:17:06,...,2015-05-30 00:43:51,1983-09-30,157654,When I realized I'm finally tired of seeing pe...,2015-02-08 20:01:36,1,1,31,9221295,False
99981,99981,105776,105776,T,371,671,194,12,2014-06-16,2015-07-06 14:09:22,...,0000-00-00 00:00:00,1995-10-31,1431,It's impossible for me to listen to this song ...,2015-02-08 20:01:52,1,0,19,8436456,True
99982,99982,105777,105777,M,29145,10881,1908,1892,2012-05-08,2015-07-09 20:44:29,...,2015-07-08 21:34:40,1954-12-31,160523,â€œConstant kindness can accomplish much. As t...,2015-02-08 20:02:24,3,1,60,4982507,True
99983,99983,105778,105778,M,16,168,212,12,2012-06-12,2015-07-09 18:22:22,...,2015-07-09 16:44:58,1953-08-31,1009,A man walks into his bedroom and sees his wife...,2015-02-08 20:02:38,13,8,61,5100778,True
99984,99984,105779,105779,M,11,1,2,0,2015-02-08,2015-02-18 10:37:42,...,0000-00-00 00:00:00,1976-12-31,990554,"I've been married for over 3yrs, together for ...",2015-02-08 20:02:43,1,0,38,9520256,False
99985,99985,105780,105780,F,234,18,86,9,2013-06-01,2015-06-26 15:00:44,...,2015-02-08 14:07:08,1994-05-31,966492,It actually takes a lot of gumption to train a...,2015-02-08 20:02:59,0,1,21,6409573,True
99986,99986,105781,105781,F,571,81,252,42,2015-01-29,2015-07-09 18:33:28,...,2015-07-09 17:44:09,1975-09-30,265395,I feel like it's getting worse :( ......stupid...,2015-02-08 20:04:22,0,0,39,9484984,True
99987,99987,105782,105782,F,66,24,6,0,2011-08-11,2015-03-17 01:26:00,...,2012-02-27 07:23:48,1997-03-07,183,I was 17 years old when my dad passed away. I ...,2015-02-08 20:04:44,1,0,18,4114668,False
99988,99988,105783,105783,F,175,17,8,0,2014-12-17,2015-07-09 17:29:29,...,0000-00-00 00:00:00,1996-07-31,578568,My cover is very rough and appears to be care-...,2015-02-08 20:04:56,3,2,18,9334674,True
99989,99989,105784,105784,F,156,137,208,34,2014-12-31,2015-07-03 17:53:18,...,2015-03-27 23:19:54,1994-08-31,2923,"Okay, so me and my boyfriend saw this place wi...",2015-02-08 20:05:46,0,0,20,9380300,True
99990,99990,105786,105786,F,52,8,9,5,2011-02-02,2015-04-29 04:21:01,...,0000-00-00 00:00:00,1997-03-07,709324,"Self explanatory, given my meds aren't doing a...",2015-02-08 20:07:21,0,0,18,3472819,False
99991,99991,105787,105787,F,605,523,11,10,2013-12-27,2015-07-09 20:37:58,...,2015-07-09 15:50:31,1971-09-30,417107,I do...<br />\n<br />\nBut I don't accept your...,2015-02-08 20:07:48,2,1,43,7645822,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99993,99993,105789,105789,M,226,173,82,4,2013-05-20,2015-07-10 00:12:13,...,2015-01-07 03:23:02,1995-10-31,47240,They don't respond when I text them. I just ha...,2015-02-08 20:08:30,3,1,19,6369871,True
99994,99994,105790,105790,F,196,70,177,75,2012-05-28,2015-07-09 23:31:17,...,2014-06-18 12:59:05,1995-11-30,48401,I love to talk. I want someone I can talk to l...,2015-02-08 20:08:44,2,1,19,5050032,True
99995,99995,105791,105791,U,5691,1251,141,24,2011-01-24,2015-07-08 07:00:53,...,2014-11-27 21:55:28,1969-09-30,387568,http://thenarcissisticlife.com/do-i-have-a-nar...,2015-02-08 20:10:39,4,2,45,3443350,True
99996,99996,105792,105792,M,52,46,87,5,2014-01-24,2015-07-09 10:39:54,...,0000-00-00 00:00:00,2000-07-31,5577,I have a pretty long story about it in the com...,2015-02-08 20:10:44,2,1,14,7783433,True
99997,99997,105793,105793,F,1713,91,300,181,2013-12-21,2015-07-09 15:28:47,...,2015-05-25 22:47:23,2000-05-31,163874,I as upset one day and i walked past a lady an...,2015-02-08 20:12:43,5,0,15,7620182,True
99998,99998,105794,105794,M,21,324,134,73,2013-12-19,2015-07-09 19:31:40,...,2015-07-06 21:28:07,1964-01-31,133597,Don't quite know how to express my enjoyment t...,2015-02-08 20:12:56,7,1,51,7609350,True
99999,99999,105795,105795,F,72,26,52,29,2014-02-02,2015-06-23 06:09:15,...,2015-06-23 06:54:02,1979-11-30,7465,"All of my life, I have always known there woul...",2015-02-08 20:14:34,0,0,35,7826707,True

In [27]:
goodData = dataWithUserIDs[~(dataWithUserIDs['uid']==0)]

In [28]:
goodData = goodData[goodData['certainty']==True]

In [29]:
goodData

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
3,3,4,4,F,29,8,83,60,2014-12-27,2015-05-14 13:25:09,...,2015-05-14 13:25:34,1977-08-31,970365,Showing now if anyone is interested...message ...,2015-01-01 00:02:45,0,0,37,9367848,True
4,4,5,5,M,14,1,2,0,2013-12-13,2015-01-07 01:57:45,...,0000-00-00 00:00:00,1990-10-31,262541,I am in love with this beautiful girl.....<br ...,2015-01-01 00:03:01,10,9,24,7581701,True
5,5,6,6,F,2993,62,353,7,2014-07-18,2015-07-09 06:55:52,...,2015-03-12 17:44:25,1996-01-31,261634,My birthday is in a few weeks 18 days everyone...,2015-01-01 00:04:52,3,5,19,8626454,True
6,6,7,7,F,69,26,21,3,2014-05-10,2015-01-04 21:53:13,...,0000-00-00 00:00:00,1999-01-31,88442,I just love doctor who ok doctor who is my lif...,2015-01-01 00:05:02,0,0,16,8267845,True
8,8,9,9,F,41,80,37,4,2014-10-31,2015-05-19 06:28:05,...,0000-00-00 00:00:00,1995-02-28,368043,I struggle so hard when I put things on shelve...,2015-01-01 00:06:58,6,4,20,9166441,True
9,9,10,10,M,263,104,176,1,2014-04-07,2015-02-11 01:13:57,...,2015-02-09 23:48:44,1981-10-31,36977,i want to cry now because its too much to take,2015-01-01 00:07:04,2,1,33,8128714,True
10,10,11,11,F,167,13,52,5,2014-12-29,2015-04-06 11:38:05,...,0000-00-00 00:00:00,1995-08-31,495,I had a summer fling with this dude like we he...,2015-01-01 00:07:21,0,0,19,9374607,True
11,11,12,12,M,304,25,49,29,2014-12-13,2015-07-06 07:37:41,...,0000-00-00 00:00:00,1962-10-31,565765,Celebrating New Years in the nude. I hope to s...,2015-01-01 00:08:02,2,2,52,9318024,True
12,12,13,13,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yeah!â€¦â€...,2015-01-01 00:08:13,0,0,14,9087949,True
13,13,14,14,F,26,14,6,4,2014-12-31,2015-05-29 18:45:41,...,0000-00-00 00:00:00,1999-05-31,473848,"It was a long time ago, it doesnt hurt today, ...",2015-01-01 00:08:42,2,5,16,9382904,True
14,14,15,15,F,118,100,69,6,2014-10-31,2015-05-09 03:00:09,...,0000-00-00 00:00:00,1996-10-31,488521,Omg his music is something else it makes me fe...,2015-01-01 00:09:21,1,1,18,9166429,True
15,15,16,16,F,1601,10,95,7,2014-02-25,2015-07-02 14:51:38,...,2015-03-11 14:16:29,1983-12-31,627239,No place far enough. <br />\nI ve crossed ocea...,2015-01-01 00:10:00,1,0,31,7938998,True
17,17,18,18,F,751,6,84,41,2014-12-26,2015-07-01 16:00:39,...,2015-04-07 23:12:16,2001-04-30,3941,"I just hate being lied to, to me it's one of t...",2015-01-01 00:10:19,4,0,14,9364093,True
19,19,20,20,F,177,10,28,13,2014-04-12,2015-07-05 15:25:45,...,0000-00-00 00:00:00,1997-04-30,395178,Spending New Year's with my family and my dogs...,2015-01-01 00:10:35,0,0,18,8149149,True
20,20,21,21,F,58,17,12,0,2014-06-19,2015-02-19 13:51:27,...,2014-12-10 15:48:27,2001-09-30,395247,My friend bailed on me at last moment. ðŸ˜•ðŸ˜,2015-01-01 00:10:43,1,0,13,8449220,True
21,21,22,22,F,26,45,15,2,2014-10-13,2015-05-22 17:39:39,...,0000-00-00 00:00:00,2000-12-31,293608,Happy new year! To staying up late! Yay!!!. . ...,2015-01-01 00:11:10,0,0,14,9087949,True
22,22,23,23,F,87,8,7,1,2014-12-30,2015-02-01 21:00:01,...,0000-00-00 00:00:00,1998-02-28,59004,"Never have, and only got one from my mother to...",2015-01-01 00:12:43,2,2,17,9379414,True
23,23,24,24,M,239,69,117,84,2014-12-18,2015-07-09 16:51:14,...,2015-06-08 23:04:15,2000-01-31,335,i know...this may sound a little inapropriat3....,2015-01-01 00:12:46,1,1,15,9335149,True
24,24,25,25,F,140,13,78,39,2014-09-10,2015-03-03 06:32:42,...,2015-02-07 21:54:05,1992-11-30,427042,"I'll add you back once you add me,but once you...",2015-01-01 00:12:54,0,1,22,8939668,True
25,25,26,26,F,374,279,226,19,2014-12-24,2015-07-09 07:49:05,...,2015-06-14 14:29:03,1990-07-31,675119,I'm drunk right now and it feel good I'm layin...,2015-01-01 00:13:33,3,2,24,9357924,True
26,26,27,27,F,247,22,246,9,2014-04-16,2015-07-09 22:58:23,...,0000-00-00 00:00:00,1999-10-31,293608,Happy new year! Wish you guys all the best,2015-01-01 00:14:04,2,1,15,8167713,True
27,27,28,28,F,9,7,10,0,2014-01-30,2015-07-09 21:44:17,...,2014-01-31 18:00:38,1991-12-31,173000,After everything I went through in 2014...hear...,2015-01-01 00:14:05,0,0,23,7812690,True
29,29,30,30,F,300,37,38,9,2014-11-05,2015-05-30 15:58:28,...,2015-02-24 02:13:59,1999-06-30,185,"All I want for this New Year is to feel safe, ...",2015-01-01 00:14:45,3,1,16,9184454,True
30,30,31,31,M,239,61,49,48,2013-07-17,2015-07-09 14:35:49,...,2015-01-02 21:49:33,1959-06-30,972256,I hope it's a good year for everyone,2015-01-01 00:14:46,1,1,56,6609242,True
31,31,32,32,M,171,100,81,53,2014-12-22,2015-07-10 00:32:09,...,0000-00-00 00:00:00,1995-11-30,2389,My new years resolution is to quit my nasty ch...,2015-01-01 00:14:59,0,1,19,9351351,True
32,32,33,33,F,75,9,11,2,2014-12-24,2015-01-07 06:24:26,...,0000-00-00 00:00:00,1983-10-31,117528,EP is a cesspool of depravity and a killground...,2015-01-01 00:15:02,12,17,31,9357495,True
33,33,34,34,U,215,104,67,56,2014-11-17,2015-07-09 21:41:57,...,2015-06-30 22:03:52,1968-04-30,160526,Let's face it<br />\n A pretty face and sexy b...,2015-01-01 00:15:30,2,1,47,9226988,True
35,35,36,36,M,72,92,49,21,2009-10-10,2015-05-31 23:44:23,...,2015-01-03 05:23:40,1977-10-31,8436,Tonight I made Kung Pao chicken<br />\n<br />\...,2015-01-01 00:16:31,5,1,37,2050477,True
36,36,37,37,M,46,43,52,33,2014-09-03,2015-05-09 19:57:03,...,2014-12-29 00:05:00,1997-12-31,1340,It's about an hour and a half away from the Ne...,2015-01-01 00:16:56,4,0,17,8905023,True
38,38,39,39,M,446,23,39,20,2013-08-09,2015-04-27 21:06:05,...,2014-07-27 20:53:29,1978-07-31,640484,Maybe she'll think my eyes are red because I'm...,2015-01-01 00:17:25,0,0,36,6769181,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99963,99963,105758,105758,F,155,84,33,0,2015-01-29,2015-02-21 06:13:36,...,0000-00-00 00:00:00,1982-01-31,31916,i am survivor of sexually abused<br />\nby my ...,2015-02-08 19:51:39,1,0,33,9483556,True
99964,99964,105759,105759,F,675,48,96,1,2015-01-11,2015-07-09 22:35:08,...,2015-07-08 19:51:43,1997-05-31,55518,Ive made homemade mac & cheese two nights in a...,2015-02-08 19:51:58,1,0,18,9422865,True
99965,99965,105760,105760,M,86,13,5,3,2015-01-19,2015-03-06 23:39:16,...,0000-00-00 00:00:00,1962-10-31,62225,i havent played a video game in years but i us...,2015-02-08 19:52:12,0,0,52,9452878,True
99966,99966,105761,105761,M,64,25,29,24,2014-09-22,2015-07-09 20:16:36,...,2015-07-09 16:44:24,1999-06-30,990552,I want a chub to smother me with his fat,2015-02-08 19:52:56,2,1,16,8997675,True
99967,99967,105762,105762,U,31,9,15,7,2013-04-01,2015-06-25 19:46:49,...,2015-06-12 14:35:55,1994-09-30,45404,Pokemon is awesome. I grew up watching the ori...,2015-02-08 19:54:20,8,5,20,6192070,True
99968,99968,105763,105763,F,605,88,327,72,2011-05-10,2015-07-10 00:29:54,...,2014-03-14 03:23:19,1997-03-07,378558,I have friends and people say I'm cute but at ...,2015-02-08 19:55:05,2,1,18,3823094,True
99969,99969,105764,105764,F,134,11,7,2,2015-02-08,2015-03-27 07:24:13,...,0000-00-00 00:00:00,2001-02-28,368260,I know im part wolf...I've known since 3rd gra...,2015-02-08 19:55:07,1,4,14,9520293,True
99970,99970,105765,105765,M,57,13,13,13,2015-02-07,2015-04-03 17:16:36,...,0000-00-00 00:00:00,1999-02-28,526490,ITS ABOUT TO BEGIN <br />\nIM TOO EXCITED,2015-02-08 19:56:00,4,2,16,9515708,True
99971,99971,105766,105766,M,357,72,347,260,2014-03-04,2015-07-09 20:23:50,...,2015-01-22 23:54:23,1998-07-31,926420,"If I told you I've never been kissed, would yo...",2015-02-08 19:56:55,2,2,16,7975284,True
99974,99974,105769,105769,F,16,11,4,3,2014-11-17,2015-07-04 10:13:58,...,2015-03-22 19:57:20,1975-03-31,990553,Even though I'm clearly gay I still get approa...,2015-02-08 19:58:45,0,0,40,9226696,True
99975,99975,105770,105770,M,847,294,244,63,2013-06-03,2015-07-09 23:12:02,...,2015-07-01 16:06:23,1973-03-31,332,<b> Then and Now â€¦</b><br />\n<br />\nReflec...,2015-02-08 19:58:49,23,8,42,6418405,True
99976,99976,105771,105771,F,107,52,164,41,2011-10-18,2015-06-02 08:06:38,...,2014-01-15 11:53:11,1991-10-31,301,"I was dreaming I was on a pathway, looking dow...",2015-02-08 19:59:11,0,3,23,4314790,True
99977,99977,105772,105772,M,700,53,35,1,2014-07-06,2015-07-09 22:32:46,...,0000-00-00 00:00:00,2000-03-31,370,"And yet again I'm in the bathroom, on the floo...",2015-02-08 20:00:04,2,1,15,8552640,True
99979,99979,105774,105774,F,605,88,327,72,2011-05-10,2015-07-10 00:29:54,...,2014-03-14 03:23:19,1997-03-07,9644,The MTA just loves prices hikes so much that t...,2015-02-08 20:01:31,0,0,18,3823094,True
99981,99981,105776,105776,T,371,671,194,12,2014-06-16,2015-07-06 14:09:22,...,0000-00-00 00:00:00,1995-10-31,1431,It's impossible for me to listen to this song ...,2015-02-08 20:01:52,1,0,19,8436456,True
99982,99982,105777,105777,M,29145,10881,1908,1892,2012-05-08,2015-07-09 20:44:29,...,2015-07-08 21:34:40,1954-12-31,160523,â€œConstant kindness can accomplish much. As t...,2015-02-08 20:02:24,3,1,60,4982507,True
99983,99983,105778,105778,M,16,168,212,12,2012-06-12,2015-07-09 18:22:22,...,2015-07-09 16:44:58,1953-08-31,1009,A man walks into his bedroom and sees his wife...,2015-02-08 20:02:38,13,8,61,5100778,True
99985,99985,105780,105780,F,234,18,86,9,2013-06-01,2015-06-26 15:00:44,...,2015-02-08 14:07:08,1994-05-31,966492,It actually takes a lot of gumption to train a...,2015-02-08 20:02:59,0,1,21,6409573,True
99986,99986,105781,105781,F,571,81,252,42,2015-01-29,2015-07-09 18:33:28,...,2015-07-09 17:44:09,1975-09-30,265395,I feel like it's getting worse :( ......stupid...,2015-02-08 20:04:22,0,0,39,9484984,True
99988,99988,105783,105783,F,175,17,8,0,2014-12-17,2015-07-09 17:29:29,...,0000-00-00 00:00:00,1996-07-31,578568,My cover is very rough and appears to be care-...,2015-02-08 20:04:56,3,2,18,9334674,True
99989,99989,105784,105784,F,156,137,208,34,2014-12-31,2015-07-03 17:53:18,...,2015-03-27 23:19:54,1994-08-31,2923,"Okay, so me and my boyfriend saw this place wi...",2015-02-08 20:05:46,0,0,20,9380300,True
99991,99991,105787,105787,F,605,523,11,10,2013-12-27,2015-07-09 20:37:58,...,2015-07-09 15:50:31,1971-09-30,417107,I do...<br />\n<br />\nBut I don't accept your...,2015-02-08 20:07:48,2,1,43,7645822,True
99992,99992,105788,105788,F,18,3,1,0,2015-02-08,2015-02-10 18:20:19,...,0000-00-00 00:00:00,1969-11-30,489047,Actually I had 4. Identical twin boys I had at...,2015-02-08 20:07:54,0,0,45,9520131,True
99993,99993,105789,105789,M,226,173,82,4,2013-05-20,2015-07-10 00:12:13,...,2015-01-07 03:23:02,1995-10-31,47240,They don't respond when I text them. I just ha...,2015-02-08 20:08:30,3,1,19,6369871,True
99994,99994,105790,105790,F,196,70,177,75,2012-05-28,2015-07-09 23:31:17,...,2014-06-18 12:59:05,1995-11-30,48401,I love to talk. I want someone I can talk to l...,2015-02-08 20:08:44,2,1,19,5050032,True
99995,99995,105791,105791,U,5691,1251,141,24,2011-01-24,2015-07-08 07:00:53,...,2014-11-27 21:55:28,1969-09-30,387568,http://thenarcissisticlife.com/do-i-have-a-nar...,2015-02-08 20:10:39,4,2,45,3443350,True
99996,99996,105792,105792,M,52,46,87,5,2014-01-24,2015-07-09 10:39:54,...,0000-00-00 00:00:00,2000-07-31,5577,I have a pretty long story about it in the com...,2015-02-08 20:10:44,2,1,14,7783433,True
99997,99997,105793,105793,F,1713,91,300,181,2013-12-21,2015-07-09 15:28:47,...,2015-05-25 22:47:23,2000-05-31,163874,I as upset one day and i walked past a lady an...,2015-02-08 20:12:43,5,0,15,7620182,True
99998,99998,105794,105794,M,21,324,134,73,2013-12-19,2015-07-09 19:31:40,...,2015-07-06 21:28:07,1964-01-31,133597,Don't quite know how to express my enjoyment t...,2015-02-08 20:12:56,7,1,51,7609350,True
99999,99999,105795,105795,F,72,26,52,29,2014-02-02,2015-06-23 06:09:15,...,2015-06-23 06:54:02,1979-11-30,7465,"All of my life, I have always known there woul...",2015-02-08 20:14:34,0,0,35,7826707,True

In [30]:
from numpy import loadtxt
top50Groups = loadtxt("/Users/dharshid/CDIPS_Project/data/top50groups.txt",comments="#",delimiter="\n",unpack=False)

In [39]:
top50Groups = top50Groups.astype(int)
top50Groups

array([  1728, 154884,  11525,   5382,    763,    233,    649, 974071,
        17036,  76430,   2108, 828259, 426065,    335,   8083,   2510,
         8726,   1431, 117528,     68,  23323,  42844,   2334,    887,
       102852, 646363,  43748,    165, 364326,   1009, 166260,    809,
         2475, 193494,   1261,   4527,   2534, 233190, 147547,   1843,
          984,  15349,    950,   5577,    332,  25529,  51387,   1340,
          109,   4603])

In [62]:
top50GroupData = goodData[goodData['gid']==top50Groups[0]]
top50GroupData = top50GroupData.append(goodData[goodData['gid']==top50Groups[1]],ignore_index=True)
top50GroupData

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1,gender,num_groups,num_entries,num_fans,num_friends,created,last_login,...,last_circle_activity,birthdate,gid,content,date_posted,votes,num_comments,age,uid,certainty
0,591,610,610,F,33,13,16,9,2014-12-29,2015-01-21 14:53:03,...,2014-12-30 07:15:41,1999-07-31,1728,Hi everyone! I encourage you all to have your ...,2015-01-01 05:30:24,9,0,15,9372801,True
1,1473,1577,1577,F,29,25,76,24,2014-06-28,2015-07-09 13:28:16,...,0000-00-00 00:00:00,1994-12-31,1728,It's a cold rain falling outside today,2015-01-01 13:59:15,9,3,20,8506518,True
2,3587,3819,3819,F,33,13,16,9,2014-12-29,2015-01-21 14:53:03,...,2014-12-30 07:15:41,1999-07-31,1728,Hey guys! So I started a photo journal account...,2015-01-02 07:30:48,5,0,15,9372801,True
3,4874,5186,5186,M,489,122,35,4,2012-03-19,2015-07-09 15:12:47,...,2015-05-23 02:30:58,1986-08-31,1728,Just a pic of a street I live on nothing special.,2015-01-02 17:11:57,9,1,28,4808448,True
4,5724,6101,6101,F,2492,1195,879,115,2014-08-14,2015-06-15 00:20:43,...,0000-00-00 00:00:00,2001-02-28,1728,Here a pic I took ^_^ of me,2015-01-02 23:09:34,30,28,14,8790749,True
5,5735,6113,6113,F,2492,1195,879,115,2014-08-14,2015-06-15 00:20:43,...,0000-00-00 00:00:00,2001-02-28,1728,Here a pic of me <br />\nMy mirror is scratch ...,2015-01-02 23:13:57,4,2,14,8790749,True
6,6089,6484,6484,M,119,37,52,49,2014-10-26,2015-07-09 22:32:39,...,2015-06-26 05:21:28,1995-05-31,1728,<img src='http://content-img.experienceproject...,2015-01-03 01:46:55,2,1,20,9144324,True
7,6780,7224,7224,F,153,27,411,13,2011-11-27,2015-07-09 21:26:55,...,2015-06-25 22:53:28,1965-11-30,1728,<img src='http://content-img.experienceproject...,2015-01-03 09:22:19,0,1,49,4437833,True
8,6796,7241,7241,F,153,27,411,13,2011-11-27,2015-07-09 21:26:55,...,2015-06-25 22:53:28,1965-11-30,1728,<img src='http://content-img.experienceproject...,2015-01-03 09:30:33,6,1,49,4437833,True
9,6804,7250,7250,F,153,27,411,13,2011-11-27,2015-07-09 21:26:55,...,2015-06-25 22:53:28,1965-11-30,1728,<img src='http://content-img.experienceproject...,2015-01-03 09:33:56,5,2,49,4437833,True
10,6813,7260,7260,F,153,27,411,13,2011-11-27,2015-07-09 21:26:55,...,2015-06-25 22:53:28,1965-11-30,1728,<img src='http://content-img.experienceproject...,2015-01-03 09:37:45,6,3,49,4437833,True
11,6823,7271,7271,F,153,27,411,13,2011-11-27,2015-07-09 21:26:55,...,2015-06-25 22:53:28,1965-11-30,1728,<img src='http://content-img.experienceproject...,2015-01-03 09:42:46,6,4,49,4437833,True
12,6858,7312,7312,F,153,27,411,13,2011-11-27,2015-07-09 21:26:55,...,2015-06-25 22:53:28,1965-11-30,1728,<img src='http://content-img.experienceproject...,2015-01-03 10:00:43,10,6,49,4437833,True
13,6926,7389,7389,F,2492,1195,879,115,2014-08-14,2015-06-15 00:20:43,...,0000-00-00 00:00:00,2001-02-28,1728,Lol wanted to post this pic,2015-01-03 10:42:53,2,1,14,8790749,True
14,7535,8040,8040,M,1365,42,299,102,2013-05-25,2015-07-10 00:24:21,...,2015-07-03 12:31:03,1966-10-31,1728,A picture I took today at nearby Kew Gardens C...,2015-01-03 15:09:29,17,4,48,6386838,True
15,7776,8294,8294,M,416,104,26,22,2014-11-21,2015-07-08 16:14:11,...,2015-03-28 10:47:01,2000-05-31,1728,*boom*<br />\nAnd boom goes the atom bomb,2015-01-03 16:50:38,2,2,15,9241933,True
16,9164,9737,9737,F,113,18,168,32,2014-07-29,2015-07-09 23:37:41,...,2015-03-07 22:55:09,1970-01-31,1728,"The moon was out early, as it was just sunset ...",2015-01-04 00:57:26,7,1,45,8696585,True
17,10470,11094,11094,F,146,47,33,9,2015-01-01,2015-03-30 05:34:03,...,0000-00-00 00:00:00,2001-06-30,1728,Lol I have to take a picture of everything,2015-01-04 12:09:08,7,2,14,9386482,True
18,10487,11114,11114,M,431,121,28,12,2014-10-30,2015-06-26 11:00:34,...,0000-00-00 00:00:00,1984-08-31,1728,"Hanging out by the fire, our third Casino of t...",2015-01-04 12:18:15,0,0,30,9160804,True
19,11147,11808,11808,F,599,1169,205,27,2014-09-29,2015-07-09 22:58:20,...,2015-06-25 17:14:59,1972-09-30,1728,Sun dogs were out today. Pic doesn't quite ca...,2015-01-04 16:42:46,2,1,42,9028937,True
20,12370,13108,13108,F,2492,1195,879,115,2014-08-14,2015-06-15 00:20:43,...,0000-00-00 00:00:00,2001-02-28,1728,"In this picture in like ""seriously?""",2015-01-05 00:09:05,10,2,14,8790749,True
21,13206,13976,13976,M,196,28,478,387,2012-05-07,2015-07-09 13:28:09,...,2015-07-09 13:28:25,1993-05-31,1728,<img src='http://content-img.experienceproject...,2015-01-05 08:21:26,1,1,22,4980529,True
22,18140,19175,19175,M,89,90,20,11,2014-09-09,2015-07-01 19:28:37,...,0000-00-00 00:00:00,1994-08-31,1728,This is what having to pay for college out of ...,2015-01-06 21:41:45,20,4,20,8934237,True
23,19092,20179,20179,F,599,1169,205,27,2014-09-29,2015-07-09 22:58:20,...,2015-06-25 17:14:59,1972-09-30,1728,Even the dog's cold...... lol,2015-01-07 06:38:18,20,4,42,9028937,True
24,19565,20689,20689,M,62,10,69,50,2012-01-04,2015-07-09 18:45:43,...,2015-06-27 23:09:00,1954-03-18,1728,<img src='http://content-img.experienceproject...,2015-01-07 11:39:04,4,2,61,4554296,True
25,20052,21193,21193,T,38,27,16,2,2014-12-01,2015-02-05 16:38:24,...,0000-00-00 00:00:00,1997-07-31,1728,A friend/ ex co-worker and I out to lunch.,2015-01-07 15:52:05,3,1,17,9278822,True
26,20331,21483,21483,M,503,127,51,6,2015-01-06,2015-01-11 16:56:07,...,2015-01-10 03:07:43,2001-03-31,1728,If you'd care to let me take a couple of you ;),2015-01-07 17:25:48,0,0,14,9407097,True
27,21608,22829,22829,T,38,27,16,2,2014-12-01,2015-02-05 16:38:24,...,0000-00-00 00:00:00,1997-07-31,1728,I'm losing my mind. I'm with out hope. <br />\...,2015-01-08 02:59:05,3,2,17,9278822,True
28,22186,23434,23434,M,1365,42,299,102,2013-05-25,2015-07-10 00:24:21,...,2015-07-03 12:31:03,1966-10-31,1728,Sunset picture taken from the Empire State,2015-01-08 09:47:27,23,7,48,6386838,True
29,22279,23532,23532,M,4030,147,281,96,2012-06-12,2015-07-09 20:03:47,...,2015-07-09 20:49:00,1970-08-31,1728,I need to get photography lessons as I never s...,2015-01-08 10:25:13,0,0,44,5098303,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,2100,2226,2226,F,350,77,270,69,2014-06-18,2015-07-09 13:10:05,...,0000-00-00 00:00:00,2000-04-30,154884,When I was 9 I got stuck in an elevator by mys...,2015-01-01 17:59:31,6,1,15,8448580,True
81,2131,2259,2259,M,38,58,39,30,2014-08-29,2015-07-09 16:31:41,...,2014-11-09 03:11:36,1989-10-31,154884,I want to thank the Women on this website who ...,2015-01-01 18:12:46,6,2,25,8876786,True
82,11425,12099,12099,F,158,54,483,284,2013-08-09,2015-07-09 23:12:12,...,2015-07-05 23:15:35,1969-12-31,154884,"I am a musical theater (theatre) geek, an act...",2015-01-04 18:39:49,3,2,45,6772284,True
83,20295,21447,21447,F,140,71,1111,701,2012-05-17,2015-07-09 22:56:07,...,2015-05-21 14:34:32,1995-01-31,154884,I'm in a bad mood and my family is acting like...,2015-01-07 17:13:56,1,2,20,5013880,True
84,21569,22786,22786,F,454,275,788,38,2014-06-08,2015-07-10 00:29:23,...,2015-06-05 03:45:03,1996-06-30,154884,I get so jealous of young people who die early...,2015-01-08 02:35:44,5,4,19,8393146,True
85,23195,24497,24497,M,387,181,83,2,2013-08-22,2015-07-01 19:51:34,...,2014-09-27 15:59:50,1996-05-31,154884,"I once, almost caught feelings for someone I n...",2015-01-08 18:24:32,4,1,19,6874583,True
86,23294,24599,24599,F,1850,755,1470,1321,2014-09-05,2015-06-16 21:18:26,...,2015-04-28 03:49:07,1983-08-31,154884,I miss u. I wish i didnt. Im also scared of wh...,2015-01-08 19:00:37,3,1,31,8913424,True
87,34853,36812,36812,F,2276,1070,350,38,2014-09-11,2015-07-05 16:38:13,...,2014-12-22 18:28:47,1993-12-31,154884,There's a game called Presentable Liberty. It'...,2015-01-13 00:25:35,3,2,21,8941440,True
88,43090,45536,45536,F,1850,755,1470,1321,2014-09-05,2015-06-16 21:18:26,...,2015-04-28 03:49:07,1983-08-31,154884,Underneath my clothes im a girl! shhhhhhh! Don...,2015-01-16 03:52:05,15,4,31,8913424,True
89,43126,45574,45574,F,454,275,788,38,2014-06-08,2015-07-10 00:29:23,...,2015-06-05 03:45:03,1996-06-30,154884,I wish I could be back in slavery times and ki...,2015-01-16 04:27:58,5,4,19,8393146,True
90,43148,45596,45596,F,2276,1070,350,38,2014-09-11,2015-07-05 16:38:13,...,2014-12-22 18:28:47,1993-12-31,154884,"If I ever get banned from this site, then to a...",2015-01-16 04:46:54,4,3,21,8941440,True
91,50825,53793,53793,M,429,953,337,7,2013-12-17,2015-07-10 00:22:09,...,2015-05-24 19:50:25,1993-11-30,154884,I'm actually a white man<br />\n<br />\nNOT,2015-01-19 03:24:53,1,3,21,7602475,True
92,52806,55880,55880,M,191,137,152,39,2010-11-05,2015-06-10 15:39:02,...,2015-01-16 15:21:48,1979-03-12,154884,"I brought my friend on here, and got her mixed...",2015-01-19 21:03:21,6,4,36,3202380,True
93,53362,56454,56454,F,1850,755,1470,1321,2014-09-05,2015-06-16 21:18:26,...,2015-04-28 03:49:07,1983-08-31,154884,I am an alien from hijhgccclkij. Don't try to ...,2015-01-20 01:48:07,8,4,31,8913424,True
94,59617,63009,63009,M,45,2,1,0,2015-01-21,2015-02-06 22:35:05,...,0000-00-00 00:00:00,1998-08-31,154884,"I had sexual relations with my cousin, when we...",2015-01-22 16:43:59,0,1,16,9459257,True
95,62330,65864,65864,F,36,41,42,10,2009-09-02,2015-05-19 08:14:58,...,2013-11-30 18:30:25,1980-03-31,154884,I loved Ally McBeal and publicly despise it am...,2015-01-23 20:08:21,0,0,35,1943151,True
96,62983,66552,66552,M,113,42,5,1,2014-10-13,2015-06-06 20:54:04,...,0000-00-00 00:00:00,1980-05-31,154884,the voice in my head tells me i want to watch ...,2015-01-24 01:25:51,2,1,35,9091369,True
97,66648,70433,70433,F,26,44,178,21,2015-01-24,2015-07-10 01:00:23,...,0000-00-00 00:00:00,1996-07-31,154884,"I'm only 17 years old like I said on my ""I'm a...",2015-01-25 11:49:43,11,6,18,9468460,True
98,67603,71477,71477,F,266,330,505,43,2014-06-20,2015-06-13 22:25:40,...,0000-00-00 00:00:00,1994-03-31,154884,All my life I have been uncomfortable around m...,2015-01-25 19:46:26,3,2,21,8458324,True
99,67829,71715,71715,F,454,275,788,38,2014-06-08,2015-07-10 00:29:23,...,2015-06-05 03:45:03,1996-06-30,154884,I'm about to disappoint a lot of men on this w...,2015-01-25 21:10:52,3,4,19,8393146,True
100,71806,75973,75973,F,4,3,57,38,2015-01-03,2015-06-04 16:16:05,...,2015-04-09 18:00:26,1990-01-31,154884,I have a huge crush on guitarhero227. Hes a me...,2015-01-27 11:44:46,3,0,25,9394090,True
101,72461,76695,76695,M,45,2,1,0,2015-01-21,2015-02-06 22:35:05,...,0000-00-00 00:00:00,1998-08-31,154884,My sister always insisted on showering with me...,2015-01-27 17:45:25,0,2,16,9459257,True
102,75551,79922,79922,F,1232,121,224,36,2014-05-02,2015-07-10 00:53:55,...,2015-06-26 05:44:07,1995-01-31,154884,"Whenever I wear something really pretty, like ...",2015-01-28 23:32:46,0,1,20,8236203,True
103,77285,81740,81740,F,76,40,52,3,2015-01-02,2015-07-09 23:01:59,...,0000-00-00 00:00:00,1994-12-31,154884,I am a compulsive liar and I continue to lie.,2015-01-29 18:37:14,1,1,20,9390266,True
104,81652,86330,86330,F,33,4,5,0,2014-12-28,2015-05-22 12:04:53,...,2014-12-31 17:39:07,1999-08-31,154884,I am ready for a company. I am wanting to be h...,2015-01-31 16:09:08,0,1,15,9370222,True
105,84876,89754,89754,F,67,7,11,2,2015-01-30,2015-02-13 00:25:38,...,2015-01-31 23:42:53,1998-12-31,154884,"Sorry, I don't mean to be seeking attention or...",2015-02-01 23:16:12,6,4,16,9489505,True
106,85266,90154,90154,F,2276,1070,350,38,2014-09-11,2015-07-05 16:38:13,...,2014-12-22 18:28:47,1993-12-31,154884,This is an email I just composed to a friend I...,2015-02-02 03:56:42,0,1,21,8941440,True
107,88224,93310,93310,F,561,133,233,184,2014-12-24,2015-07-09 22:56:15,...,2015-01-24 13:58:37,2000-04-30,154884,My guilty pleasure is rap and heavy metal,2015-02-03 11:24:15,6,0,15,9357609,True
108,95023,100551,100551,F,263,19,17,17,2015-02-06,2015-06-24 03:40:05,...,2015-03-02 06:56:32,1978-08-31,154884,"I love helping others, and often times make th...",2015-02-06 15:44:56,1,1,36,9511376,True
109,96591,102199,102199,U,29,68,14,1,2012-05-25,2015-07-08 13:00:07,...,2014-10-29 07:06:17,1970-03-31,154884,This afternoon I was about a minute away from ...,2015-02-07 09:40:30,0,1,45,5038359,True

In [64]:
top50GroupData = goodData[goodData['gid']==top50Groups[0]]
for i in range(1,50):
    top50GroupData = top50GroupData.append(goodData[goodData['gid']==top50Groups[i]],ignore_index=True)

In [70]:
top50GroupData.columns

Index([u'Unnamed: 0', u'Unnamed: 0.1', u'Unnamed: 0.1', u'gender',
       u'num_groups', u'num_entries', u'num_fans', u'num_friends', u'created',
       u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments', u'age', u'uid',
       u'certainty'],
      dtype='object')

In [75]:
uidColNum = 20
gidColNum = 14
top50GroupData.iloc[1,[14,20]]

gid       1728
uid    8506518
Name: 1, dtype: object

In [74]:
top50GroupData.loc[1,['gid','uid']]

gid       1728
uid    8506518
Name: 1, dtype: object

In [77]:
import userGroupDict

In [81]:
top50GroupSorted = top50GroupData.sort(columns='uid')

In [93]:
topGroupSubset = top50GroupSorted.iloc[0:5000,:]
topGroupSubset.shape

(5000, 22)

In [94]:
userGroup = userGroupDict.makeUserGroupDict(topGroupSubset, uidColNum, gidColNum)

In [97]:
keyList = userGroup.keys()

In [98]:
keyList[0:5]

[1040397, 7790607, 6438929, 8142866, 4661267]

In [104]:
userGroup[keyList[4]]

{887: 1}

In [105]:
import numpy as np
zeroMatrix = np.zeros((2,3))

In [106]:
zeroMatrix

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [113]:
userSeries = topGroupSubset.iloc[0:20, 20]

In [114]:
userSeries

2951      47289
3133      47289
3239      47289
7538      54180
7359     318563
11214    477629
10031    488234
10030    488234
11102    493465
9383     500393
9666     500393
6270     500393
6271     500393
9714     500393
8692     500393
9115     500393
11136    572098
413      612408
2519     612408
11972    612408
Name: uid, dtype: int64

In [117]:
len(userSeries.unique())

9

In [118]:
x = np.random.randint(9, size=(3, 3))

In [119]:
x

array([[1, 2, 5],
       [8, 2, 0],
       [4, 3, 6]])

In [120]:
x[0,1] += 1

In [121]:
x

array([[1, 3, 5],
       [8, 2, 0],
       [4, 3, 6]])

In [122]:
top50Groups[0:7]

array([  1728, 154884,  11525,   5382,    763,    233,    649])

In [123]:
np.__version__

'1.9.2'

In [124]:
top50GroupData.shape

(12516, 22)

In [130]:
a = np.random.randint(9, size=(3,3))

In [131]:
a

array([[1, 1, 8],
       [4, 3, 8],
       [3, 7, 1]])

In [132]:
a[0,0] = 0
a[1,2] = 0
a[2,2] = 0
a[0,1] = 0

In [133]:
a

array([[0, 0, 8],
       [4, 3, 0],
       [3, 7, 0]])

In [138]:
nonzero = np.flatnonzero(a)
nonzero

array([2, 3, 4, 6, 7])

In [142]:
b = np.put(a, nonzero, 1)
a

array([[0, 0, 1],
       [1, 1, 0],
       [1, 1, 0]])

In [143]:
M = np.loadtxt("top50GroupsMatrix.txt")

In [144]:
M

array([[  0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [  2.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   1.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   2.,   0.,   0.,   0.,   0.]])

In [145]:
import turnToBinaryMatrix

In [146]:
M1 = turnToBinaryMatrix.turnToBinaryMatrix(M)

In [147]:
M1

array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.]])